ChaoticOnyx/OnyxBay

- code/game/objects/items/weapons/teleportation.dm
- code/game/turfs/simulated/walls.dm
- code/modules/materials/materials.dm
- code/modules/research/designs/protolathe/dp-bluespace.dm
Fixes some issues with Vortex Manipulator and slightly reworks ricochet and reflect systems, e.g. adds damage distribution between proj and wall.
> RicochetsReflects rework_and_fix + Vortex fix

- code/datums/supplypacks/security.dm
- html/changelog.html
1)Нелетальное оружие (любой код)
2 шоковые винтовки и карабина. Хотел ещё добавить плазменный станер, но там херовые спрайты совсем
2)ППшки (синий код и выше)
3)Булпапы (красный код)
4)Осколочные гранаты (красный код)
5)Недавно добавленные тактические наплечники и набедренники (любой код)
+чейнджлог
> Добавил несколько охранных паков в карго

- code/game/machinery/suit_storage_unit.dm
Убрал проверку у циклера, я не знаю для чего она нужна и от чего она должна защищать, но без неё работает всё прекрасно. Ни рантаймов, ни ошибок. Но вроде бы как, вроде бы, эта проверка идёт на окраску? Ой не знаю, мне лень. Главное чтобы люди перестали ныть про эти циклеры и смогли спокойно играть за расу на шахтёрке.
> Recycler Fix

- code/modules/mob/living/silicon/robot/robot_modules.dm
Ну теперь должно быть без проебанной табуляции.
> Мейк щитборгс грейт эгейн

- code/modules/modular_computers/file_system/programs/generic/supply.dm
> Костыли & Велосипеды: Емаг карго консоли фикс

- code/game/machinery/camera/presets.dm
- maps/exodus/exodus_presets.dm
- maps/shared/exodus_torch/presets.dm
Позволит смотреть все камеры станции одновременно, без бейской жопоебли.
> Мастер-нетворк для камер

- code/datums/supplypacks/medical.dm
- code/datums/supplypacks/miscellaneous.dm
- code/datums/supplypacks/science.dm
- code/game/objects/items/weapons/storage/firstaid.dm
- code/modules/reagents/reagent_containers/pill.dm
1)Добавил в код таблеточки глюкозы и гироналина
2)Добавил пачки этих таблеток в рандомизированный пак в карго
3)Добавил шприцемёты и картриджи в медицинские заказы
4)Добавил серьёзную пользу от емагнутого карго, можно заказывать телекристаллы. Оптом дешевле!
5)В ящик токсинщиков докинул вентилей
6)Хирургические инструменты, которые и так можно заказывать, кинул в удобную коробочку
> Добавил новые таблеточки и несколько новых заказов в карго

- code/game/antagonist/outsider/ert.dm
- code/game/antagonist/outsider/mercenary.dm
- code/game/antagonist/outsider/raider.dm
- code/game/antagonist/station/changeling.dm
- code/game/antagonist/station/cult_god.dm
- code/game/antagonist/station/cultist.dm
- code/game/antagonist/station/loyalist.dm
- code/game/antagonist/station/revolutionary.dm
- code/game/antagonist/station/traitor.dm
Уменьшил число создаваемых игрой антагов.
Запретил мерчам быть ролью. 
Повысил количество целей для Генокрада.
> Antag Balance

- code/game/objects/items/stacks/medical.dm
Теперь в пачке не 5 бинтиков, а 10. То же самое касается и мази, улучшенных наборов. А всё потому что на серьёзную рану порой тратится сразу весь стак из 5, это прям вызывает боль. И в хирургии можно тоже пролюбить все бинты
> Увеличил количество бинтов и других расходников в стаках

- code/modules/organs/external/machine.dm
Сменил сильно улучшенную батарейку у киборг-людей на обыкновенную. [Батарейку можно улучшить, вытащив microbattery из туловища, открутив отвёрткой и вытащив ломом. Не забудьте закрутить новую батарейку отвёрткой.]
> Full Body Prosthetic cell nerf

- code/game/objects/items/devices/modkit.dm
Реворк модкитов. Теперь можно из одного предмета с помощью него создавать другой. Как пример добавил модкит, который апгрейдит тактический тазер до улучшенного егана.
> Реворк модкитов

- code/modules/projectiles/gun.dm
Стрелять из оружия можно без харм интента
> Fire at will

- code/game/turfs/simulated/wall_shuttle.dm
- code/modules/shuttles/shuttle.dm
Под уголками и после удаления теперь правильные турфы.
> Фикс турфов под шаттлами

- code/datums/uplink/highly_visible_and_dangerous_weapons.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- Убрал магнум из магазина триторов.
- Забрал термалки у ХоСа и отдал их Детективу.
> Crime Balance

- code/game/machinery/autolathe.dm
- code/game/machinery/biogenerator.dm
- code/game/machinery/bioprinter.dm
- code/game/machinery/kitchen/gibber.dm
- code/game/machinery/mass_driver.dm
- code/game/machinery/pipe/pipe_dispenser.dm
- code/game/machinery/robot_fabricator.dm
- code/game/machinery/seed_extractor.dm
- code/game/machinery/suit_storage_unit.dm
- code/game/mecha/mech_fabricator.dm
- code/modules/detectivework/microscope/dnascanner.dm
- code/modules/hydroponics/seed_storage.dm
- code/modules/integrated_electronics/machine_printer.dm
- code/modules/mining/machine_vending.dm
- code/modules/paperwork/faxmachine.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/reagents/dispenser/dispenser2.dm
- code/modules/research/circuitprinter.dm
- code/modules/research/destructive_analyzer.dm
- code/modules/research/protolathe.dm
Поправил слои у машинерии, теперь объекты которые из них должны выпадать не будут прятаться под ними же.
> Machinery Layers

- code/modules/random_map/automata/caves.dm
> You struct the damp wall, its soaked with blood

- code/game/machinery/cryopod.dm
> Cryopod fix

- code/modules/mob/living/silicon/robot/robot_items.dm
При прервании выбрасывания предмета больше не багается
> robot rack fix

- code/game/gamemodes/changeling/changeling_powers.dm
- code/modules/clothing/under/jobs/security.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Починил время спавна цианида и убрал седативный эффект от дедстинга.
Дермалпатча ХоСа защищает от удара бутылкой
> Убрал возможность генокраду жрать макак.

- code/game/machinery/Sleeper.dm
- code/game/objects/items/weapons/circuitboards/machinery/machinery_circuitboards.dm
- nano/templates/sleeper.tmpl
Улучшение слиппера путём замены на улучшенные деталки в нём. Для получения новых синтезов нужно улучшать манипулятор и сканнер, а для стазиса конденсатор. Всё просто.
Емагнутый слиппер позволяет ввести Лексорин, а также заблокировать консоль. (Беднягу можно вытащить путём разбора самого слиппера.)
#103
> Sleeper Upgrading

- code/modules/modular_computers/computers/modular_computer/damage.dm
Фикс старого бага с дюпом стали.
https://github.com/Rampoch/Chaotic-Onyx/issues/272
> Modular Computer steel dupe fix

- code/modules/tables/rack.dm
https://github.com/Rampoch/Chaotic-Onyx/issues/294
> Rack plastic dupe fix

- code/modules/mob/living/simple_animal/hostile/asteroid/basilisk.dm
> Нерф Василиска

- code/game/antagonist/antagonist_factions.dm
- code/game/objects/structures/morgue.dm
- code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
- code/modules/projectiles/targeting/targeting_overlay.dm
- code/modules/projectiles/targeting/targeting_triggers.dm
- code/modules/random_map/automata/caves.dm
#84 #18 
#42 #59 
Помимо этого при прицеливании можно стрелять с хелп интентом
убрал лишнее сообщение которое я использовал для дебага спавна астероида
> milestone fixes

- code/modules/projectiles/projectile/magnetic.dm
Наконец то ученые перестанут делать только его (наверно)
> Нерф реилгана

- code/modules/organs/internal/_internal.dm
> Synth organs are now vulnerable to EMP

- code/modules/organs/organ.dm
> organ emp hotfix

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/modularchangling.dm
Поменял цену и расход для некоторых абилок, зафиксил часть описаний абилок и сообщений в чатик на менее корявые. 
Соре за стопицот коммитов.
> Генкобаланс и фиксы некоторых надписей

- code/modules/client/preference_setup/global/01_ui.dm
Меняет дефолтный фпс
60 фпс слишком много и движение становится заторможеным
> default fps fix

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/modularchangling.dm
> Armblade nerf

- code/game/gamemodes/changeling/helpcode.dm
> Cleaned debug messages

- code/modules/reagents/Chemistry-Reagents.dm
Уберает сообщения при овердозе у препаратов которые не имеют овердоза
> overdose tooltip fix

- code/game/supplyshuttle.dm
> Никаких больше каргобаллов за таллеры

- code/modules/detectivework/tools/sample_kits.dm
Я тут беру отпечатки, а не обмазываюсь об револьвер
> Заебало срать волокнами (Fix #176)

- code/game/objects/items/devices/flash.dm
- code/modules/projectiles/guns/energy/stun.dm
Добавлен фаерделей на тазер, теперь никаких киборгов-пулеметчиков.
На 50% увеличино время стана от флешки.
> небольшие нерфы киборгов

- code/datums/sound_player.dm
- code/game/machinery/jukebox.dm
Убираем лаги, добавляем стриминг аудиофайлов.
> jukebox streaming

- .travis.yml
> Научил травис чекать карту

- code/modules/power/cell.dm
- code/modules/research/designs/protolathe/dp-engineering.dm
Новая фигня для научного отдела.
> Блюспейс батарейка

- code/game/gamemodes/changeling/helpcode.dm
- code/modules/research/rdconsole.dm
Маленький фикс абилок типа infest и paralyse
> Маленький фикс доступа в РнД и фикс генокрадов

- code/_onclick/other_mobs.dm
- code/game/machinery/adv_med.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/surgery/limb_reattach.dm
фикс адванседсканнера
фикс симплэнималов
фикс фантомного бедра
> S0m3 f1x3s

- code/modules/research/protolathe.dm
> Фиксы протолата, но это не точно

- html/changelog.html
https://github.com/ChaoticOnyx/OnyxBay/commit/a1a5d800d1a6f1ad99e1c9a66779bc6687d87b8e Вот для этого
> Забытый мной changelog для фиксов тоби

- code/game/objects/structures/mirror.dm
- code/modules/admin/DB ban/functions.dm
- code/modules/admin/topic.dm
- code/modules/mob/grab/normal/grab_normal.dm
- code/modules/mob/new_player/new_player.dm
Да как это говно заставить только один коммит послать, я ебал.
> Гендерная тирания

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/helpcode.dm
- code/game/gamemodes/changeling/modularchangling.dm
Короче я тут наваял всяких фиксоребалансофич для генок. Очень рекомендую принять до релиза Соляровского выпила инфеста, а еще советую заодно принять #399 для обновистости.
Ченджлохв доступен по ссылке бесплатно без СМС и регистрации: https://pastebin.com/najCnyEY
> Proizoshla genokrazha

- code/game/objects/items/weapons/teleportation.dm
- code/game/turfs/simulated/walls.dm
Fixes what I never had time to fix before.
Have fun.
> Final gift ricochet vortex

- code/modules/mob/mob_helpers.dm
#15 
Можно добавить еще символов, но нужно дублировать и большими буквами. Byond не может в кириллицу
> заикание для кириллицы

- code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
> Фиксы превью, но это не точно

- code/modules/modular_computers/computers/subtypes/preset_console.dm
Абсолютно каждая консоль теперь оснащена принтером. Неважно, нужен он ей или нет. На будущее пригодится.
В библиотечную консоль тоже добавлено
CHANGELOG https://pastebin.com/RJfwF3bV
> Принтеры в каждый дом!

- code/game/machinery/jukebox.dm
- code/modules/admin/DB ban/functions.dm
- code/modules/admin/topic.dm
Мы сделали вам реверт реверта, чтобы ревертировать реверты, пока ревертируем реверт
Reverts ChaoticOnyx/OnyxBay#303
> Revert "Реверт джубокса"

- code/modules/mob/new_player/new_player.dm
> Фиксим трейты

- code/game/gamemodes/changeling/absorbed_dna.dm
- code/game/gamemodes/changeling/changeling_powers.dm
Контрибуторская фигура на месте замри
> Фиксим три

- code/modules/reagents/reagent_containers/hypospray.dm
- code/modules/reagents/reagent_containers/syringes.dm
- Больше нельзя взаимодействовать с автоинъекторами с помощью шприцов.
> Объективно лучшее обновление за историю Chaotic Onyx

- code/datums/sound_player.dm
- code/game/machinery/jukebox.dm
- code/modules/client/preference_setup/global/preferences.dm
Нуфф сейд. На локалочке потестил, работает. С инструментами вроде не должно работать
> Jukebox Preferences

- code/modules/reagents/reagent_containers/dropper.dm
Какой-то дебил подумал, что будет хорошей идеей разделить проверки для шприцов и пипеток.
> Объективно лучшее обновление за историю Chaotic Onyx pt.2

- code/modules/lobby_music/issomebodysinging.dm
- sound/serversound_list.txt
Добавляет в ротацию лобби-музыки I.S.S. by Chris Hadfield and BNL
https://www.youtube.com/watch?v=AvAnfi8WpVE
> Is Somebody Singing?

- code/datums/outfits/jobs/medical.dm
> Большое обновление химии

- code/_onclick/hud/robot.dm
- code/game/area/areas.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/external/_external_damage.dm
- code/modules/organs/external/stump.dm
- code/modules/organs/internal/stomach.dm
- code/modules/reagents/Chemistry-Reagents.dm
- Рантаймы 
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы 
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы 
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы 
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- Рантаймы
- fuck your cunt you shit eating cocksucker man eat a dong fucking mass ending shitfuck eat penis in your fuckface and shitout abortion of fuck and do shit in your ass you cock fuck shit monkey ass wanker from the depths of shit
> Runtimes Suck

- code/modules/client/preference_setup/global/preferences.dm
- code/modules/projectiles/projectile.dm
В преференсах можно выключить звук хитмаркеров.
> Hitmarker preference

- code/game/gamemodes/changeling/absorbed_dna.dm
- code/game/gamemodes/changeling/changeling_powers.dm
Reverts ChaoticOnyx/OnyxBay#447
> Revert филькиного кода

- code/game/machinery/doors/windowdoor.dm
Ходи по ссылке http://upgradefromwindows.com
> Фикс форточек

- code/modules/mob/living/carbon/human/update_icons.dm
...или нет. What you gonna do?
> Фиксит пропадающую одежду

- code/game/gamemodes/changeling/absorbed_dna.dm
- code/game/gamemodes/changeling/changeling_powers.dm
- code/modules/augmentation/prosthetic/bioprosthetic/weapons.dm
Пофикшены проблемы трейтов. Пофикшено то, что фейковый армблейд из за того, что кто то любит трогать циферки, был почти настоящим - из за 10 форса и остроты.
> fix changeling and traits

- code/game/objects/items/devices/scanners.dm
Охуетительная идея -- переконвертить тип в строку, а потом забыть его обратно в тип преобразовать.
> Should fix mass spectrometers

- code/game/sound.dm
- code/modules/admin/secrets/random_events/trigger_CompanyProvocation.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- maps/exodus/exodus_areas.dm
- maps/exodus/exodus_shuttles.dm
- maps/shared/exodus_torch/loadout/loadout_uniform.dm
Починил отступы в *.dm файлах, чтобы было везде одинаково. Нет особых изменений.
> T2: Intendation fixes. Now tabs everywhere

- .vscode/extensions.json
- baystation12.dme
- code/__defines/mobs.dm
- code/game/verbs/ooc.dm
- code/modules/admin/admin.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/individual_logging.dm
- code/modules/mob/living/say.dm
- code/modules/mob/mob.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/mob_helpers.dm
[Linked issue](https://github.com/ChaoticOnyx/OnyxBay/issues/20)
- Added individual mob logs (**IC** and **OOC** only for now)
- Added admin verb to view them
- Added recommended extensions for vscode devs
> T7: Say log

- code/game/area/areas.dm
- code/modules/power/lighting.dm
https://cdn.discordapp.com/attachments/563412167618199572/588410096489332765/unknown.png
https://cdn.discordapp.com/attachments/563412167618199572/588410228408713216/unknown.png
https://cdn.discordapp.com/attachments/563412167618199572/588410323606962176/unknown.png
https://cdn.discordapp.com/attachments/563412167618199572/588410661240045568/unknown.png
> Замена оверлея тревоги на смену освещения 

- baystation12.dme
- code/game/objects/items/weapons/material/swords.dm
- code/modules/mob/living/simple_animal/hostile/faithless.dm
- code/modules/mob/living/simple_animal/parrot.dm
- code/modules/spells/aoe_turf/conjure/druidic_spells.dm
- code/modules/spells/aoe_turf/disable_tech.dm
- code/modules/spells/general/radiant_aura.dm
- code/modules/spells/hand/burning_grip.dm
- code/modules/spells/spellbook/druid.dm
- code/modules/spells/spellbook/standard.dm
- code/modules/spells/spellbook/warlock.dm
- code/modules/spells/targeted/projectile/fireball.dm
- code/modules/spells/targeted/projectile/passage.dm
- code/modules/spells/targeted/shapeshift.dm
- code/modules/spells/targeted/torment.dm
Разнерфил часть абилок визарда, добавил новую экспериментальную книжку, вытащил некоторые неиспользуемые абилки из архива.
> Оживляем визардов

- code/modules/mob/living/carbon/human/species/outsider/vox.dm
> "Починил" все спрайты воксов тремя строчками.

- code/game/antagonist/station/changeling.dm
- code/game/gamemodes/changeling/changeling_powers.dm
Сам сломал, не сам заметил, сам починил
> Returned changelings back where they belong

- code/controllers/configuration.dm
- code/modules/admin/DB ban/functions.dm
- code/modules/admin/IsBanned.dm
- code/modules/admin/banjob.dm
- code/modules/admin/topic.dm
- code/procs/dbcore.dm
- config/example/config.txt
Разделил баны по серверам. Забанить теперь можно либо на этом конкретном сервере либо на всех сразу ~вообще всех~
Обновил банпанель.
> DB BANS: mankind divided

- code/modules/mob/living/carbon/human/update_icons.dm
> Убираем блевотное размытие

- code/game/jobs/job/civilian.dm
Mime can cast invisible walls now.
> Job - Mime - Spell "Invisible Wall"

- code/game/objects/items/weapons/storage/backpack.dm
- code/modules/power/singularity/singularity.dm
По реквесту Маркуса, бэг оф холдинг получил свой функционал назад. Сингулярность больше не будет представлять опасность только для одного уровня станции.
> Сингулярность теперь умеет путешествовать между z-уровнями, а бох получил свои фичи назад.

- code/game/objects/items/weapons/tape.dm
Фикс исправляет удаление клейкой ленты. Также исправляет артефакты в поведении солнечных панелей, как следствие.
> Фикс клейкой ленты и бумаги.

- code/modules/reagents/reagent_containers/pill.dm
Починил стейт невидимой таблетки с цианидом у мерков и дедсквада. _В потайном кармане его обуви мы обнаружили таблетку цианида..._
> Фикс спрайта капсулы с цианидом

- code/controllers/configuration.dm
- code/game/world.dm
- config/example/config.txt
> Выпил джукбокса примите срочно

- baystation12.dme
- code/modules/admin/admin_verbs.dm
- code/modules/events/event_container.dm
- code/modules/events/pestilence.dm
- code/modules/virus2/effect.dm
Добавил случайные события с заражением экипажа станции заранее заготовленными и разнообразными патогенами.
**Космический Ретровирус** — Распространяет генетический код нулевого пациента по всей станции.
**Холод 9** — Заболевание, которое будет постепенно понижать температуру тела жертвы в дополнение к острым респираторным симптомам.
**Грипп** — Распространенное заболевание, вызывающее усталость и высокую температуру.
**Космический Артеривирус** - Заболевание, вызывающее острую физическую слабость и проблемы с костями у жертвы.
**Ксеновирус** — Хорошо изученное биологическое оружие, созданное фанатиками для сдерживания популяции ксеносов в далеком космосе.
**Хиссвирус** — Редкое заболевание, вызывающее животный голод у представителей Унати.
**Мышечная Гонка** — Заболевания, заставляющее …
> Вспышки вирусов в виде внутриигровых событий

- code/__defines/_planes+layers.dm
- code/game/turfs/flooring/flooring_premade.dm
Проблем с коврами и тенями теперь быть не должно.
> Фикс декалей и ковров.

- code/game/machinery/cryopod.dm
> **_ГЕНОКРАДЫ СОСАТЬ!_**
**Warning: a lot of copypaste ahead.**
Короче буду бля, запрещаем вытаскивать тушки из крио для тех, у кого нет доступа в охранку, также и с робо-крио, но плюс к этому робоптушники могут вытаскивать
разумеется это дерьмо можно емагнуть
теперь также можно просто перетащить свою вырвиглазную картинку персонажа на криоворе и со временем тебя туда перекинет
ну и relaymove, куда без него в это тяжелое время?
> Ограждение для криоподов

- baystation12.dme
- code/game/machinery/kitchen/microwave.dm
> Починен UI микроволновки.

- code/modules/client/preference_setup/traits/trait_defines.dm
Ограничил дефекты речи по реквесту Татарина.
> Теперь можно выбирать только один дефект речи

- code/_helpers/unsorted.dm
- code/modules/client/preference_setup/general/03_body.dm
Добавил стрелки для переключения волос на голове и лице
> Улучшение интерфейса создания персонажа

- code/game/gamemodes/objective.dm
- code/modules/psychotronics/loot.dm
- code/modules/psychotronics/psychoscope.dm
- Фикс иконок психоскопа
- Добавлены цели трейторам украсть психоскоп и нейромод
- Добавлен стартовый брифкейз для РД с психоскопом
> Фикс иконки психоскопа, цели трейторам, стартовый кейс

- code/game/gamemodes/objective.dm
> Убран обжектив на нейромод

- code/modules/clothing/under/jobs/security.dm
> Кастомный плащ для НайнАнимаса

- code/game/objects/explosion.dm
- code/game/sound.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/projectile.dm
- Звук стрельбы оружия БЕЗ глушителя будет гарантировано услышан в пределах трёх экранов.
- Оружие с глушителем слышно только в пределах видимости.
- Немного улучшены звуки взрывов и пошатывания станции.
> Небольшие фиксы звуков взрывов и стрельбы

- code/modules/spells/spellbook/cleric.dm
- code/modules/spells/spellbook/spatial.dm
- code/modules/spells/spellbook/standard.dm
- code/modules/spells/spellbook/warlock.dm
Одни впиливают, другие выпиливают. Комитет смешного постановил, что чудо-кольцо с бесконечным инвизом слишком смешное, и не нужно до полноценного ребаланса (которого никогда не будет).
> Круговорот фич на Ониксе

- code/datums/communication/ooc.dm
- code/modules/client/client_procs.dm
- code/modules/client/darkmode.dm
- code/modules/client/preference_setup/global/preferences.dm
- interface/skin.dmf
- Возможность изменять позицию чата
- Пофикшен цвет админ ООС
> Interface features

- code/game/jobs/job/captain.dm
- code/game/jobs/job/engineering.dm
- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
- code/game/jobs/job/security.dm
>А давайте мы вернём ограничение кодом заходить за глав персонажами моложе двадцати пяти лет, и это гениальнейшим образом решит часть проблем.
done
> Ограничение минимального возраста главы

- code/game/antagonist/antagonist.dm
- code/modules/admin/admin.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/organ.dm
- code/modules/projectiles/ammunition.dm
- Постепенная смерть органов
- Случайное смещение у гильз
> Фичи И Фиксы

- code/modules/mob/living/bot/bot.dm
- code/modules/mob/living/bot/secbot.dm
> Офицер Бипски теперь играбельный

- code/_onclick/hud/human.dm
- code/game/gamemodes/changeling/helpcode.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/organs/organ.dm
- Механические органы не гниют
- У биоструктуры время гниения - 15 минут
> Исправление гниения органов

- code/controllers/configuration.dm
- code/modules/admin/admin_verbs.dm
- code/modules/projectiles/projectile.dm
> Бросаем пулю в обидчика или новый верб в fun

- code/game/machinery/doors/firedoor.dm
- code/modules/donations/examine.dm
- code/modules/onyxchat/browserOutput.dm
- code/modules/onyxchat/browserassets/css/browserOutput_marines.css
- code/modules/onyxchat/browserassets/css/browserOutput_white.css
- code/modules/onyxchat/browserassets/css/styles_template.css
- Все файлы стилей приведены к одной структуре
- Удалены лишние стили
- Создан шаблон для стилей чата
- Доработана тема маринов
- Цвета во всех темах максимально одинаковы (ООС, радиоканалы и тд)
- Пофикшен экзамай
> Рефакторинг стилей чата и фиксики

- code/modules/mob/living/carbon/give.dm
> Фикс логической ошибки в give

- code/modules/integrated_electronics/subtypes/arithmetic.dm
- code/modules/integrated_electronics/subtypes/lists.dm
> Фиксим интегральные платы

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/Chemistry-Recipes.dm
> Добавил иммунокорректор

- code/modules/organs/organ.dm
> Твик иммунитета

- code/game/objects/structures/inflatable.dm
> Надувные стенки теперь не вечны

- code/__defines/shields.dm
- code/datums/wires/shield_generator.dm
- code/modules/shield_generators/floor_diffuser.dm
- code/modules/shield_generators/handheld_diffuser.dm
- code/modules/shield_generators/modes.dm
- code/modules/shield_generators/shield.dm
- code/modules/shield_generators/shield_generator.dm
> Фикс диффузоров

- baystation12.dme
> Отрубил wip-карту

- code/modules/clothing/head/collectable.dm
- code/modules/clothing/head/misc_special.dm
> Фиксим котоушки

- code/game/antagonist/outsider/wizard.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/energy/special.dm
> Забираем у мага пушки и продвинутые девайсы

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> immunocorrector-tweak

- code/__defines/chemistry.dm
- code/datums/uplink/stealthy_and_inconspicuous_weapons.dm
- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/paperwork/pen.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
- code/modules/reagents/Chemistry-Recipes.dm
> Парализующий реагент и парализующая ручка в аплинк

- code/modules/clothing/under/miscellaneous.dm
- code/modules/ventcrawl/ventcrawl.dm
> Contortionist's jumpsuit hotfix

- code/game/machinery/rechargestation.dm
> Зарядка ригов в станции для обслуживания боргов

- code/modules/mob/living/silicon/ai/malf.dm
> Малф больше не удаляет свои собственные вербы

- code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
> Фиксим удаление ордеров

- code/game/objects/items/weapons/storage/storage.dm
> Подписываем свои рюкзаки и фиксим рантайм

- code/game/gamemodes/cult/ritual.dm
- code/game/gamemodes/cult/runes.dm
- code/game/gamemodes/cult/talisman.dm
> Добавляем талисман гипноза культистам

- code/modules/food/recipes_microwave.dm
- code/modules/hydroponics/seed_datums.dm
- removes bug with watermelon seeds
- fixes path to bananas
> fix(recipes): fix all recipes with bananas and watermelons

- code/game/objects/items/cryobag.dm
> fix(cryobag): fix wrong path

- code/modules/client/preference_setup/general/03_body.dm
- code/modules/client/preferences.dm
- and now you can use cybernetic stomachs
> fix(preference): remove runtime with synthetics saves

- .travis.yml
> Когда пробелы

- code/game/objects/structures/window.dm
- code/modules/clothing/head/collectable.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/species/station/monkey.dm
- code/modules/projectiles/gun.dm
> tweak(chimps): make pun even more annoying

- code/modules/mob/living/carbon/human/species/station/monkey.dm
> tweak(chimps): make monkeys more curious

- code/modules/mob/living/carbon/human/species/species.dm
Фикс дизарм армблейда
close #1022
> fix(changeling): fix armblade disarm

- code/game/objects/items/stacks/medical.dm
Фиксим сломанные многоразовые медицинские модули, которые не перезаряжались.
fix #615
> fix(medical cyborg): fix consumables modules

- code/game/objects/random/random.dm
Появление синди-вещей со смешным шансом в техах и гетто.
> /random spawn tweak

- code/modules/ventcrawl/ventcrawl.dm
> fix(ventcrawl): repair monkey ventcrawl

- .travis.yml
Рекурсивный глоб уже юзался в мапах, а оказалось, что он не работает. ~~Рекурсивный глоб в мапы тоже я притащил.~~ Мопед не мой.
> Когда пробелы-то

- code/procs/announce.dm
> Где звуки смены кода

- code/modules/mob/living/carbon/human/species/station/monkey.dm
> fix(chimps): optimize and add container interaction checking

- code/modules/client/preference_setup/global/preferences.dm
- code/modules/synthesized_instruments/sound_token.dm
- html/changelogs/instr_pref.yml
Течёт кровь из ушей из-за музыки в баре? Не беда.
> Преф на музыкальные инструменты

- code/controllers/subsystems/ping.dm
- code/modules/onyxchat/browserassets/html/browserOutput.html
Временно отключил пинги.
Во-первых, они спамят сервер. Во-вторых, сервер пытается записывать эти хрефы в логи, из-за чего хрефы в принципе не логируются.
Пока совсем закомментировал, посмотрим как это отразится на лагах и потом включим обратно, но чуть более адекватным способом, чтобы сервер не ложился.
fix #1082
can affect issue #1090
> fix(log): disable ping due high load on server

- baystation12.dme
- code/__defines/subsystems.dm
- code/_global_vars/configuration.dm
- code/controllers/configuration.dm
- code/modules/admin/admin_ranks.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/permissionverbs/permissionedit.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- code/modules/donations/new/donations.dm
- code/modules/donations/new/donator.dm
Подключаемся к БД с донатами и загружаем оттуда информацию по донатерам.
Также пофиксил пару старых запросов, которые не работали с MySQL 8.0
> Новая система донатов: подключаем БД

- code/game/gamemodes/changeling/helpcode.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/organ.dm
> Igor's decay revert

- code/modules/projectiles/projectile/bullets.dm
Теперь она наносит примерно 120 дамага в упор (чаще всего хватает на гиб) и 60-80 с трех тайлов (хватает чтобы уронить). Броня соответственно существенно снижает дамаг, так как дробь не имеет armor piercing`а.
close #1122
> Разнерф дроби

- baystation12.dme
- code/modules/client/ping.dm
Добавил новую команду "ping", которая показывает чуть менее рандомные числа, чем раньше это делал гунчат.
> feat(ping): new "ping" command

- code/game/objects/items/weapons/stunbaton.dm
> Стан от прилетевшей в хлебало включенной стан дубинки

- code/modules/mob/living/carbon/resist.dm
> Фикс кулдауна при попытке встать резистом со стула

- code/modules/events/pestilence.dm
- code/modules/virus2/effect.dm
**-- возможен кринж с кодом из-за его возраста --**
Simple: новый эффект, заставляющий экран бедняги повернуться либо налево, либо направо.
Ну а так же новая болезнь в контейнер слабых заболеваний, спавнящийся при мини-ивенте. Болезнь зовётся "Космическая мигрень". Да, лучше не мог придумать. В этой самой болезни лежит этот новый эффект. Без этого никак.
С балансом особо не разбирался, так что _может_ стоит глянуть на такие выставленные переменные как chance и delay у вируса и эффекта.
> Дезориентирующий вирус 

- code/modules/clothing/spacesuits/rig/modules/modules.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
> runtime rig fix

- code/game/objects/items/weapons/storage/storage_ui/default.dm
> Фикс смешных мышеловок

- baystation12.dme
Кодеры ниче не могут сами smh.
resolve #1154
**ПРИНЯВ ПР - НЕ ЗАБУДЬ ОТКЛЮЧИТЬ СЛЕДУЮЩИЕ КОНФИГИ:**
- map_switching
- auto_map_switching
- auto_map_vote
> Убрал строчку

- code/game/objects/random/random.dm
> Нотка паранойи

- code/game/antagonist/outsider/actors.dm
- code/game/response_team.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/mob/observer/ghost/ghost.dm
Добавил проверку на наличие бана на актеров у игрока.
Переделал их в проки и привязал их к призракам и игрокам в лобби.
Так же закинул их во вкладку 'OOC', куда им и место.
Также должен пофиксить один глупый баг, который сюда палить не буду. Если нужно узнать, что за баг - пишите в приватный канал в дискорде со слапом.
> Трогаем Join as Actor & Join Response Team вербы.

- code/game/gamemodes/malfunction/newmalf_ability_trees/tree_manipulation.dm
- code/game/machinery/newscaster.dm
- code/game/objects/items/weapons/tanks/tanks.dm
- code/modules/events/money_spam.dm
- code/modules/mob/mob_helpers.dm
- maps/exodus/derelicts/lar_maria/lar_maria.dm
> Удаляем вопросики

- code/modules/client/preference_setup/general/06_flavor.dm
Ну вообще я тоже считаю что в флаворах должна быть чисто внешность, примите когда решите там.........
> Критикал фиксы критикал бага (ООЦ в флаворах)

- code/controllers/subsystems/ticker.dm
- code/game/antagonist/blob/blob.dm
- code/game/antagonist/blob/blobs/node.dm
- code/game/antagonist/blob/theblob.dm
- code/game/gamemodes/game_mode.dm
- code/game/mecha/mecha.dm
- code/game/objects/items/bodybag.dm
- code/game/objects/structures.dm
- code/game/objects/structures/crates_lockers/closets.dm
- code/modules/mob/blob.dm
**Исправление багов, указанных в этом иссуе:**
fix #968
Поскольку в том иссуе это не написано, напишу здесь: этот ПР также исправляет окончание раунда, в случае, если блоб захватил необходимое количество тайлов.
> Фиксы блоба.

- code/modules/projectiles/gun.dm
мне нехуй было делать
почему баг: да потому что стерео проёбано
> делаем фар шоту направление источника в одно слово

- code/game/turfs/simulated/wall_shuttle.dm
- code/modules/shuttles/shuttle.dm
И оно даже работает.
чё баг: сабж чти
> фикс уголков шаттлов

- code/game/objects/random/random.dm
- ревёрт шанса удоления карты
- фикс весов на спавн карто4ки в разных местах комнатки
close #1391
close #1387 too
Почему оно существует: ну охуенная идея проб50% на спавн спейр карты айди. теперь то и хуй шаттл в случае чего выпишешь, да и доступ повысишь в ночнораунде
> Ревёрт паранойи

- code/game/objects/items/weapons/storage/fancy.dm
- code/game/objects/items/weapons/storage/lockbox.dm
- code/game/objects/items/weapons/storage/storage.dm
> denied to open a vialbox when it locked

- code/game/objects/explosion.dm
посмотрел, поглядел, поменял одно, удалил другое. 3/7/14 слышится отлично с расстояния ~3 экрана, а может быть и больше. Остальное подстраивается само
баг почему: читай сабж. не понял? смешай 1 куб калия и  1 куб воды на сегодняшнем билде и спамь этим как угарелый. поздравляю, все думают что на станции завелись террористы взрывающие лимитки
close #1400
> пидорасы прокающие взрывы 0 0 0 и срущие на всю станцию звуками

- code/modules/client/client_procs.dm
- code/modules/donations/new/donations.dm
Добавляем функционал для привязки бьонда к дискорд-аккаунту.
> feat(donations): link discord account with byond

- code/_helpers/mobs.dm
- code/game/machinery/OpTable.dm
- code/modules/surgery/surgery.dm
Поскольку синтетикам больно, да и сама фича с раздеванием несколько страшная, а мы с вами находимся в далеком будущем - я решил добавить специальный верб для операционного стола, который позволяет за короткий промежуток быстро и ловко снять всю одежду с пациента.
К тому же одежда теперь полностью блокирует операцию, убирая мемные провалы.
Решил отказаться от идеи с нижним бельем.
Также исправил показываемое название органа на котором находится мешающая проведению операции одежда.
conflict #1454 
close #1357
> Доделываем фичу с необходимостью снимать одежду для хирургии.

- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/drinkingglass/drinkingglass.dm
- code/modules/reagents/reagent_containers/food/drinks.dm
- code/modules/reagents/reagent_containers/glass.dm
> Добавляем возможность выливать/обливать из напитков

- code/game/gamemodes/changeling/changeling_powers.dm
fix #1531 
fix #1054 
fix #1009
> Фикс способности Division у генокрада

- code/datums/vote/vote.dm
> Забыл закрыть тег.

- code/_global_vars/lists/objects.dm
- code/game/objects/items/weapons/teleportation.dm
Убраны поиски по всему миру, которые вызывали лютейшие лаги, код немного претерпел рефакторинг, убрано неработающие ограничение на количество вортексов.  Заменены леталовские СПАНы на СПАНы бея(которые используются в большинстве вариантов).
И мемас в честь лагающего вортекса:
> removing vortex lag issues

- code/modules/power/solar.dm
- maps/exodus/exodus_areas.dm
Также пофиксил авто-запуск солнечных панелей на телекоммах, так что энергия будет идти и её конечно же будет хватать.
> Убираем бесконечную энергию на телекоммах.

- html/create_object.html
> Оптимизация create_object.html

- baystation12.dme
- code/_global_vars/lists/areas.dm
- code/controllers/evacuation/evacuation.dm
- code/game/area/Space Station 13 areas.dm
- code/game/area/areas.dm
- code/modules/power/lighting.dm
На 100% меньше страшных оверлеев.
Возможно свет не самый удачный подобрал, но это всё ещё лучше чем вырвиглазное дерьмо.
close #1318
> Изменяем свет в коридорах при эвакуации

- code/game/objects/items/weapons/storage/firstaid.dm
Портирована  возможность с Бэя доставать таблетки из бутылки с таблетками при помощи активации её в руке
> Pills here

- code/modules/admin/EAMS.dm
осталось лишь сделать лимит очередь и вообще переехать на фрауд
> eams proxy check

- code/game/turfs/turf.dm
Немного изменил механику кравла. Вместо перетаскивания используется клик.
> Кравл через клик

- code/game/machinery/kitchen/cooking_machines/_cooker.dm
- code/game/machinery/kitchen/microwave.dm
> Fixes #1584

- code/modules/projectiles/gun.dm
я инвалид, у меня рак
* Бтв, огнестрел без чембера вызывал смешной иф который на самом деле не работал и поджигал с убийством))))
> HOTfix handle sucide

- baystation12.dme
- code/__defines/languages.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/bluespace_tech.dm
- code/modules/multiz/movement.dm
Полезная фича, позволяющая заспавниться на месте будучи гостой, дабы что-то протестировать. Имеется возможность прохождения сквозь стены, полный доступ, godmode, xray, в общем всё необходимое для того, чтобы что-то протестировать.
Взято с Эриса, с поправками на кодстайл.
ПР: [ссылка](https://github.com/discordia-space/CEV-Eris/pull/1780).
> [PORT] Блюспейс-техник.

- code/game/antagonist/antagonist_factions.dm
- code/game/antagonist/antagonist_helpers.dm
- code/game/gamemodes/cult/cultify/turf.dm
- code/game/jobs/job_controller.dm
- code/game/machinery/doors/windowdoor.dm
- code/game/mecha/mech_fabricator.dm
- code/game/objects/effects/decals/Cleanable/fuel.dm
- code/game/objects/effects/decals/cleanable.dm
- code/game/objects/items/blueprints.dm
- code/game/objects/items/devices/floor_painter.dm
- code/game/objects/items/weapons/melee/energy.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/food/recipes_microwave.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/observer/ghost/ghost.dm
- code/modules/modular_computers/file_system/programs/engineering/atmos_control.dm
- code/modules/nano/nanoui.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/external/head.dm
- code/modules/organs/organ.dm
- code/modules/projectiles/guns/energy.dm
- code/modules/recycling/disposal.dm
- code/modules/research/rdconsole.dm
- code/modules/research/rdmachines.dm
- code/modules/security levels/keycard authentication.dm
- code/modules/virus2/disease2.dm
- code/modules/xenoarcheaology/tools/ano_device_battery.dm
- code/modules/xenoarcheaology/tools/artifact_harvester.dm
fix #1581 fix #1285
fix #1541 
fix #1576 
fix #1376 fix #1203 
fix #1561 
fix #850 
fix #1487 
fix #1505 
fix #480 
fix #1528 (вообще-то удаляется, просто со временем, в сообщении теперь будет говориться о том, что нужно просто подождать.)
fix #1255 
fix #910 
fix #909 
fix #277
fix #1604 
Пофикшены дергающиеся стеклянные двери.
Пофикшены различные рантаймы, описание в названиях самих коммитов.
> Ящик багфиксов.

- code/datums/communication/pray.dm
- code/modules/donations/new/donator.dm
- code/modules/emojis/emoji_parse.dm
> tweak(ooc): emojis available only for patrons with tier Scientist and greater

- code/game/verbs/who.dm
- code/modules/client/preference_setup/global/preferences.dm
- В радужном who показывается текущая профессия у живого моба, если таковая есть.
- Добавил педальский преференс на отключение радуги в who.
- Лист снова в алфавитном порядке.
- Вернул на место `(?)`
> Наболевший педальский who.

- code/game/mecha/equipment/tools/tools.dm
- code/game/objects/structures/rock.dm
- code/modules/mob/living/silicon/robot/robot_items.dm
> Зачем вызывать деструктор

- code/modules/research/rdmachines.dm
> Фикс названия реагента у рнд.

- code/modules/projectiles/guns/energy.dm
> Фикс иконок у Energy Gun

- code/modules/power/power_usage.dm
> Убираем регистрацию `moved event` у всей машинерии

- code/game/antagonist/antagonist_factions.dm
> Фикс конвертирования у ревы.

- code/modules/surgery/organs_internal.dm
> Фикс проводимых операций на мёртвых органах.

- code/_helpers/icons.dm
- code/game/machinery/newscaster.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/modules/admin/view_variables/topic.dm
- code/modules/client/asset_cache.dm
- code/modules/games/boardgame.dm
Вам было мало десятков тысяч рантаймов? Я знаю! Добавил больше ассертов.
> debug(assets): more asserts + send assets to clients instead of mobs

- code/modules/client/client_procs.dm
Как раз и от сломанных логов избавимся
> Выкидываем проходимцев с 513-ым

- code/game/objects/items/weapons/grenades/chem_grenade.dm
- code/game/objects/items/weapons/grenades/smokebomb.dm
> fix(icons_grenade)

- code/modules/mob/living/bot/secbot.dm
Бипский реагирует в 5 раз быстрее, не хармит людей, изменена область атаки с груди на ноги
close #670
> Обновление бипская

- code/modules/organs/external/_external_damage.dm
> Тактическая оптимизация

- code/game/machinery/doors/windowdoor.dm
> Фикс автозакрытия стеклянных дверей

- code/game/gamemodes/cult/ritual.dm
ну да я кровавая руна без крови, а как ты узнал?
> Возвращаем кровь кровавым рунам

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/helpcode.dm
> Фикс смешных багов у генокрадов

- code/_helpers/icons.dm
**Этот ПР выполнен по следующему реквесту:
close #1166**
Теперь же призраки могут с очень маленьким шансом оказаться на чьей-либо фотографии. Этот шанс увеличивается с силой культа на станции.
> Отображение призраков на фотографиях.

- code/modules/research/rdconsole.dm
Запрещаем игрокам выставлять бешеные значения, что могут положить сервер.
fix #1803
> Лимит для протолата

- code/modules/admin/admin_verbs.dm
- code/modules/modular_computers/file_system/programs/generic/library.dm
- nano/templates/library.tmpl
Позволяем педалям удалять истории о том, как у Вуди встала шишка. 
Удалить книги можно же через кнопку во вкладке Admin, либо же через сам модулярный компьютер с включенными правами.
> Педальная возможность удалять книги из БД.

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
Оптимизация дверей. Заместо процесса мы теперь используем таймер.
> Заменяем процесс у дверей на таймеры.

- code/modules/admin/IsBanned.dm
Защищаемся от фэйковых соединений, что могут вызвать лаги или же краш сервера.
https://github.com/tgstation/tgstation/pull/48529 https://github.com/tgstation/tgstation/pull/48583
> Защита для IsBanned()

- code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
> increase in the number of days you need to join as drone

- code/game/jobs/job/captain.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/engineering.dm
- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
- code/game/jobs/job/security.dm
- code/game/jobs/job/silicon.dm
Captain, HoP, HoS, CE, CMO, RD, AI 14 -> 30 - Меньше брейнротов на главах.
Cyborg, Warden, Detective, Security Officer 7 -> 14 - Чуть меньше щиткуров и забивающих на законы боргов.
Quartermaster, Medical Doctor 3 -> 7 - Чуть-чуть меньше слегка неопытных КМов и врачей.
Internal Affairs Agent 10 -> 14 - Чуть меньше смешных факсов.
> increasing minimal_player_age for diffirent jobs

- code/_onclick/hud/ability_screen_objects.dm
- code/_onclick/hud/movable_screen_objects.dm
Портанул фикс бага с бея: https://github.com/Baystation12/Baystation12/commit/1514a5b14e43c29704904c7e093ac413f4eafcd0
close #1825
> fix(hud): fix runtime when giving mobs abilities with HUD buttons

- code/modules/client/client_procs.dm
В клиенте BYOND есть баг, из-за которого нам бесконечно приходили подтверждения о получение кэша клиентом. Портировал костыль с ТГ, который просит клиент перестать нас спамить.
Также перенес логирование хрефов на момент сразу после проверки лимита запросов и убрал лишние логи, которые были вне проверки лимита и, теоретически, позволяют ДДОСить сервер.
fix #1818
> fix(asset): fix BYOND client spam server with asset arrival confirmations

- code/modules/projectiles/projectile.dm
должно починить застрявшие в воздухе пули нагружающие сервер и сказать чё с ними не так
(наверное)
> assert proj lag

- code/_helpers/areas.dm
- code/game/gamemodes/cult/hell_universe.dm
> Убираем возможность появления мобов Нар-Си на ЦК

- code/modules/surgery/bones.dm
> tweak(bone mender): add visible message

- code/game/machinery/teleporter.dm
- code/game/objects/effects/portals.dm
- code/modules/integrated_electronics/subtypes/manipulation.dm
ПР согласован нашим геймдизайнером. Если же у вас возникнут вопросы к ПРу - обращайтесь к @MemoryDreams. 
Изменения порталов:
- Порталы, которые были созданы ручным телепортером, имеют шанс отправить вас путешествовать во вселенной.
- Стационарные же необходимо калибровать перед каждым запуском. Сделать это можно при помощи кнопки 'Calibrate Teleporter' в контекстном меню. В противном случае, вы рискуете пропасть бесследно.
> Небезопасные телепорты.

- code/controllers/subsystems/ticker.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- code/modules/client/preference_setup/global/preferences.dm
- code/modules/onyxchat/browserOutput.dm
* Переработал полноэкранный режим. Сделал привязку к преференсам
* Означает что при заходе в игру, режим будет применяться автоматически
(при нужном условии)
* Удалил тултип в связи с его низкой популярностью и возможностью нагружать соединение сервера функцией `MouseEnter()`
* Отключил лог загрузки модифицированного чата
* Включил обновление лобби-панели после начала раунда
* Почистил файл с дефайнами клиентов
> Refactors fullscreen mode, removes tooltip

- code/game/objects/items/weapons/storage/backpack.dm
Я в рюкзаке ношу с собой
Рассветы, горы и прибой.
И Солнца зной, и ночи мрак
Влезают в старенький рюкзак.
Reverts ChaoticOnyx/OnyxBay#1809
> Ревертаем нерф боха

- code/modules/client/asset_cache.dm
Отключил подтверждение получения ассетов клиентов, т.к. периодически оно ломается и начинает спамить сервер, причем довольно часто.
К сожалению фикс с ТГ не сработал.
> fix(assets): disable assets receive confirmations

- code/modules/onyxchat/browserOutput.dm
оно зачем-то нужно, но я не знаю зачем
> tweak(onyxchat): static

- code/controllers/subsystems/garbage.dm
- code/modules/admin/verbs/debug.dm
> (tweak): harddel are disabled by default

- code/modules/power/apc.dm
Сука, ебаные, блять, долбоебы, тупорогие хуесосы, блять, чтоб вас семеро ебали, чтоб ебал сам блядский Сатана того, кто сделал гридчеки такими частыми.
https://github.com/ChaoticOnyx/OnyxBay/commit/661b5968d9fc0e24ba0c64ce61aa09723a8c965c
А ты вообще мой хуй соси в особенности, ебаный блять курлык пиздык.
Код не проверял, пишу на горящей жопе.
Исправляем вот эту ебанину в самом верху, от которой возникает 1.5 миллионов вызовов power_change у машинок.
> Stop updating the entire zone every fucking tick you stupid fucking _failure_ of an APC 

- code/game/verbs/who.dm
- code/modules/client/preference_setup/preference_setup.dm
> fix(who): remove runtime

- code/modules/security levels/keycard authentication.dm
фиксим говно хеккоча
был проёбан два из двух отосланных варов
close #1836
> fix(authpanel): sending vars fix

- code/datums/supplypacks/science.dm
Поменял доступ к ящику с вирусами, чтобы вирусолог мог его открывать.
Closes #1429
> fix(virus crate): changed virus crate access

- code/modules/paperwork/paper.dm
Поправлены радиус броска и скорость броска у скомканной бумаги.
Closes #1485
> fix(paper):changed crumpled paper throw range

- code/modules/detectivework/tools/rag.dm
Замена звука при поднятии тряпки
close #1949
> Изменение звука при поднятии тряпки

- code/modules/clothing/spacesuits/rig/modules/combat.dm
Фикс модуля-гранатомёта в РИГах. Теперь гранатомёт в РИГе работает как стандартный гранатомёт.
close #1980
> Фикс модуля-гранатомёта в РИГе.

- code/__defines/flags.dm
- code/modules/clothing/masks/breath.dm
- code/modules/clothing/masks/miscellaneous.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Исправлен баг, который позволял кушать, когда маска не опущена
close #1436
> Теперь необходимо опускать маску, чтобы поесть

- code/modules/clothing/clothing.dm
- code/modules/clothing/head/helmet.dm
- code/modules/mob/living/carbon/human/human.dm
> feat(hats): hats can fly away if you slipped

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Мыши с некоторым шансом будут кусаться, когда ты переходишь их.
close #1967
> feat(mouse): bite stepped people

- code/game/mecha/equipment/tools/tools.dm
Раньше алмазный бур для Рипли был хуже обычного, сейчас этот баг исправлен.
close #1973
> Алмазный бур для Рипли стал лучше обычного

- code/game/objects/items/weapons/candle.dm
Теперь свечи можно зажечь не только используя спички.
close #2032
> Мелкофикс зажигания свечей.

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Мыши теперь ТОЧНО будут кусать людей, переходящих их. Обосрался, починил.
> hotfix(mouse): bite stepped people 100%

- code/modules/VR/vr_gamepad.dm
> выкидываем игроков из врподов при отключении электричества

- html/changelog.html
А разгребать мне всё равно приходится.
> Кое-кто обосрался с чейнжлогами.

- code/game/antagonist/antagonist.dm
- code/game/antagonist/antagonist_helpers.dm
Симпл_животные не смогут получать трейторку.
close #2039
> fix(can_be_antagonist):simple_animals will not receive an antagonist role

- nano/templates/crew_monitor_map_content.tmpl
Фикс древнего как говно мамонта бага.
Беедауны такие беедануы.
Я кончил.
close #470
> fix(crew_monitor): more than one member on map

- code/modules/admin/topic.dm
отображение ип и сид в мореадмининфо
close #2000
> feat(adminmoreinfo): ip and cid displaying

- code/modules/client/client_procs.dm
- code/modules/projectiles/projectile/beams.dm
- interface/interface.dm
Убрал верб лор панели и ставший ненужной проверки на кол-во дней с захода игрока, согласно #1747.
Касательно 3 пункт: сборка прошла без ошибок, запуск локального сервера был успешен, не могу быть уверен, что не вызовет багов, но все упоминания верба в коде удалены.
UPD: посмотрел по пул реквестам, нашел такую же проблему, рантаймов не было, вербы не упоминаются.
close #1747
> Убираем лор панель у новичков

- code/game/machinery/jukebox.dm
Добавил Space Oddity в джукбокс по запросу
close #1615
> feat(jukebox): added new song

- code/game/antagonist/station/traitor.dm
Убрал в трейторежиме ХоПа из рестриктед проф
close #2100
> А ХОП-ТО ТРЕЙТОР!!!11

- code/game/machinery/telecomms/broadcaster.dm
две строчки спасает чаотик опукс ~~ха ха их четыре~~
логируется в логи и в индивид раунд лог
close #24
> tweak(radio): logging

- code/modules/clothing/spacesuits/rig/modules/combat.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/projectile/beams.dm
- code/modules/research/designs/protolathe/dp-mining.dm
- code/modules/research/designs/protolathe/dp-rig.dm
По просьбам людей (~31 человек) пробафал резак, добавил ему возможность гибнуть конечность, сделал его не таким бесполезным в раскопках, увеличил урон ему.
Просьба геймдизу поправить параметры, если это ломает баланс.
close #2052 , затрагивает #1095
> Усиление плазменного резака

- code/game/objects/structures/morgue.dm
someone just deserve it
close #1719
> fix(morgue tray): layer fix

- code/modules/security levels/keycard authentication.dm
похоже таймер каллы сломали передачу юзера или чё-то типо такое
но теперь то с визибл мессаджами заживём!
close #2059
> fix(auth_panel): broken to_chat changed to chad roleplay visible message

- code/modules/spells/spellbook/battlemage.dm
- code/modules/spells/spellbook/cleric.dm
- code/modules/spells/spellbook/druid.dm
- code/modules/spells/spellbook/spatial.dm
- code/modules/spells/spellbook/standard.dm
- code/modules/spells/spellbook/warlock.dm
Поднял цену у "no_clothes"
close #1092
> no_clothes_cost_fix

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Нормальная инициализация вещества "Vecuronium Bromide" (из парализаторной ручки).
closes #1672
> fix(vecuronium_bromide): Missed description

- code/controllers/subsystems/timer.dm
Если timer вызывается с пустым callback, то мы хотим знать удалили ли его до нас, а удаляем ли мы сейчас - это мы итак знаем, спасибо..
close #2220
> fix(timer): write correct qdel time when callback is null

- code/game/gamemodes/objective.dm
Немного поменял текст описаний обжективов у культа, заменил устаревшую информацию актуальной.
Связанных иссуев нет (я не нашёл).
> Актуализация описаний целей культа

- code/modules/events/blob_outbreak.dm
Теперь если у человека есть роль, то роль блоба ему не выпадает.
close #1626
> Фикс рандом ивента блоба.

- code/modules/power/apc.dm
фикс недофикшенного фикса, nuff said
related to #1913
fixes #2279
> fix(apc): energy_fail n failure_timer

- code/modules/mob/living/carbon/human/species/station/station.dm
кое кто забыл докрутить ещё пару варов
close #2158
> tweak(skrell): adjust discomfort temp

- code/datums/uplink/services.dm
похоже мистер айфромспейс решил не усложнять себе жизнь при копипасте беедаунского кода какими-то тестами
а зря
close #2314
> fix(uplink_service): sprites

- code/_macros.dm
- code/modules/onyxchat/browserassets/css/browserOutput.css
- code/modules/onyxchat/browserassets/css/browserOutput_marines.css
- code/modules/onyxchat/browserassets/css/browserOutput_white.css
- code/modules/onyxchat/browserassets/css/styles_template.css
сап /дев/, я вижу как вас заколебали скобочки и попытки запилить несколько классов за раз при помощи заёбестых макросов, потому представляем вам
**мультимакрос**
используется легко, пишите `SPAN("нужные классы", "текст")`
семпл: `SPAN("giant warning", "Нажми F1")`
старые макросы всё ещё работают но юзать не рекомендую
> The Multimacros

- code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
> fix(nanoword): preview

- code/game/gamemodes/changeling/absorbed_dna.dm
- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/helpcode.dm
Теперь генки кушают флавор вместе со внешностью и транформируются с ним. Ура.
closes #416
closes #2161
> fix(changeling flavor)

- code/modules/research/designs/protolathe/dp-weapons.dm
Мутаген просто был не объявлен. Залить мутаген на текущий момент можно только пипеткой, но оно работает как должно.
close #2338
> Починил рецепт деклонера.

- code/modules/reagents/Chemistry-Recipes.dm
Добавлен админлог у термита, спейслюба, политриника, хлорки, потассиум хлорида, потассиум хлорофорида, ЕМП, напалма.
Убран админлог у келотана и куланта.
Оставлен админлог у ЭКСПЛОУЖНА.
close #2357
> Добавил админлог при варке !!опасных!! веществ и убрал у неопасных

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Исправил ломанное название реагента `fertilizer` в ChemMaster3000
close #2265
> Починил название реагента.

- code/modules/client/preference_setup/global/03_pai.dm
- code/modules/mob/living/silicon/pai/personality.dm
- code/modules/mob/living/silicon/pai/recruit.dm
- code/modules/mob/new_player/preferences_setup.dm
Исправлены два бага в окне создания персонажа:
1. Информация о pAI не сохранялась;
2. При создании случайного тела почти всегда выпадало женское.
> fix(setup character screen)

- code/controllers/configuration.dm
- code/datums/communication/ooc.dm
- code/modules/admin/EAMS.dm
Добавил в конфиг опцию, при включении которой EAMS не даст писать в OOC.
> feat(eams): eams blocks OOC messages

- config/example/warnings/heads.html
- config/example/warnings/newcomers.html
Какой магией переносятся конфиги у Зла я не знаю, так что гарантировать работу на сервере не могу.
fixes #2415
> Фикс кодировки варнингов

- code/modules/client/preference_setup/general/06_flavor.dm
- code/modules/mob/living/carbon/human/human.dm
Откатилось из-за мержа 513 блет, вернул обратно
> fix(flavor): flavor may not include OOC notes

- maps/exodus/exodus.dm
- maps/exodus/exodus_define.dm
Отключил динамическую загрузку карт, что давно нужно было сделать, еще когда Эклипс отключали. Загрузка игры у меня на локалке ускорилась аж на 30 секунд.
> perf(build): disable dynamic maps loading

- code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> close #1364

- code/game/antagonist/antagonist_factions.dm
> Поменял местами «да» и «нет» в приглашении революционеров

- code/modules/food/recipes_microwave.dm
Рецепт чизкейка теперь соответствует рецепту на Википедии. Сделано чтобы не было недопониманий между игроком и вики.
close #1183
> fix(cheesecake): recipe

- code/game/antagonist/blob/blob.dm
- code/game/antagonist/blob/theblob.dm
- code/game/gamemodes/game_mode.dm
Блоб все еще не завершал раунд. Фиксим еще раз.
Да, в проверке на завершение любого МОДА мы должны помнить про блоб и на всякий случай проверять, а не пожрал ли блоб станцию. Надежный, качественный код. Пока просто затычку по аналогии с нюкой запилил, но весь этот треш надо рефакторить конечно.
fix #1201
> fix(blob): fix round on the blob domination

- code/game/machinery/washing_machine.dm
Стиралка теперь может стирать нижнее бельё, nuff said. Ну и ещё немного рефакторинга.
fixes #1627
> Стиралка может стирать трусы

- interface/skin.dmf
Топ 10 изменений, которых никто не просил 2: отключение шакального масштабирования.
Завез галочку в меню, возвращающую ~~мой 2007~~ масштабирование как раньше, без мыла. Поведение по умолчанию не изменилось.
> Масштабирование

- code/game/antagonist/blob/blobs/node.dm
Теперь у нода те же density и opacity что и у всех остальных составных блоба, и он уничтожается эмиттером.
resolves #2365
> fix(blob node): density

- maps/exodus/exodus_shuttles.dm
А что делать с нюкой пока не решили.
> Убрал оповещение о прибытии воксов и торговцев

- code/game/machinery/adv_med.dm
Исправил слипшийся между собой текст в распечатке медсканера и в сканере педалей.
resolves #2400
> fix(medscan)

- code/modules/error_handler/error_handler.dm
- code/modules/webhook/webhook.dm
Бот не умеет рантаймы писать, хз нафиг игорь это вообще залил.
> Реверт рантайм вебхука

- code/game/mecha/mech_fabricator.dm
Я не люблю читать одинаковые рантаймы.
close #1926
> fix_runtime(mech_fabricator)

- code/modules/food/recipes_microwave.dm
Во-первых, сделал код настолько понятным, что даже хеддев понял (да, я вместо того чтобы оставить родителей, вынес все ингредиенты прямо в торты).
Во-вторых, я поменял количество сахара на то, которое ДОЛЖНО быть по законам логики.
В-третьих, также для законов логики убрал из рецептов тортов соки фруктов и соки одновременно, оставив только фрукты.
В общем и целом, торты теперь работают как все хотели.
resolves #1367
> fix(cakes): recipes

- code/modules/client/preference_setup/general/03_body.dm
- code/modules/mob/living/carbon/human/human_defines.dm
Возвращаем классику. Должно работать и для чарактер сетапа, и для спавна. 
EDIT: на спавн теперь не работает.
> Дефолтные люди меняются с неприметных лысиков на красивых людей с short hair

- code/modules/mob/living/simple_animal/friendly/mouse.dm
> Фикс укусов мышей

- code/datums/outfits/jobs/medical.dm
- code/game/jobs/access_datum.dm
- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
- code/game/objects/items/weapons/cards_ids.dm
- code/modules/mob/living/bot/medbot.dm
- maps/exodus/exodus_jobs.dm
Ну, долой генетику, от слова совсем. Выпилил еще больше упоминаний генетики для того, чтобы убрать у главы персонала возможность дать должность Geneticist и соответственно доступ в Genetics Lab отдельно. Ну и подчистил, что у остальных теперь тоже нет доступа в несуществующий отдел.
resolves #2225
> fix(access): genetics

- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
Довольно просто сделано, но реально не хватает.
> Админверб на просмотр отправленных факсов

- code/modules/reagents/dispenser/dispenser2.dm
Всё. Больше никаких засовываний вёдер в химические раздатчики. Это нарушает законы логики, оно слишком большое чтобы туда влезать.
resolves #2068
> fix(bucket): dispenser

- code/game/machinery/kitchen/gibber.dm
Теперь её не нужно емагать, чтобы пускать на мясо людей.
(днивжи, прости, нам надоело ждать, гибать людей хочется)
Изначально хотел и выпил ограничений у мясного крюка сделать в этом ПРе, но в ходе тестирования выяснилось, что там проблемы уровня "о боже, ничего не работает, какой дебил писал этот код", так что лучше в отдельный ПР делать.
Частично выполняет #1330
> Выпил ограничений у мясорубки

- code/game/jobs/job/civilian.dm
tweak(mime): mime can change his name at the beginning of the round
close #2514
> Добавил возможность миму менять имя на раунд.

- code/datums/trading/misc.dm
- code/datums/trading/trade.dm
- code/datums/trading/unique.dm
Как мы столько лет жили с мультиплаером в ПЯТЬ ТЫСЯЧ? 
Заодно подкорректировал пару штук. Цены понижаются, пул вещей увеличивается. В теории, теперь торговцы меньше времени будут проводить за консолькой.
> Убрал абуз у торговцев, взамен облегчив им работу

- code/modules/client/preference_setup/global/preferences.dm
> Фикс преференса цвета ника

- code/datums/supplypacks/supply.dm
Скидки кончились.
resolves #2065
> Еда дорожает

- code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Оказывается, это починили три года назад… Полный порт с авроры вместе с оптимизацией. 
close #2632
> Павуки больше не создают миллион коконов

- code/modules/events/event_container.dm
- code/modules/events/event_dynamic.dm
Мой фикс не зафиксил, давайте просто отключим пауков, педали их и так отключать стараются каждый раунд. Потом пусть Эпикус ревертнет.
> Пожалуйста, помогите

- code/modules/client/preference_setup/global/05_settings.dm
В прок кидался моб вместо клиента.
fixes #2669
> Фикс рантайма в преференсах

- code/modules/mob/living/living.dm
При беге в пьяном или дизориентированном состоянии теперь есть шанс упасть в мусорку.
closes #2260
> Шанс падения в мусорку при беге в состоянии дизориентации

- code/game/machinery/newscaster.dm
- code/modules/admin/multiaccount.dm
- code/modules/flufftext/TextFilters.dm
- code/modules/mob/living/autohiss.dm
- code/modules/mob/living/say.dm
- code/modules/mob/mob_helpers.dm
Полностью переписал страшный болотный копикод, отвечающий за нарушения речи: заикания (два вида), бубнёж, картавость и шепелявость. Попутно исправил ошибки кодировки.
А, и шипение/рычание ксеносов тоже поправил.
closes #2496 #2389 #1381
> Исправление модификаторов речи

- code/modules/library/lib_machines.dm
Интересный факт: заголовок этого ПР в 143 раза длиннее, чем сами изменения.
close #2587 #2642 #2712
close #2398
> Исправление отображения кириллицы в книгах, полученных из переплётной машины

- code/game/jobs/job/engineering.dm
Стейты для худов генериурются из имени профы, это интересно, конечно, но лезть в иконки при каждом переименовании никому не нужно.
fixes #2702
> Фикс худа на инженерах

- code/_helpers/logging.dm
- code/modules/donations/new/donations.dm
- code/modules/storyteller/metrics/wounds_metrics.dm
- code/modules/storyteller/storyteller_character.dm
- code/modules/storyteller/storyteller_metric.dm
- code/modules/storyteller/storyteller_trigger.dm
Убрал спамящие логи из игрового чатика + совсем удалил некоторые забытые мусорные дебажные логи.
Ну и спамящие логи в файле логов теперь помечаются отдельным тегом
> tweak(donations, storyteller, logging): hide excess logs

- code/modules/mob/living/silicon/robot/examine.dm
- code/modules/mob/living/silicon/robot/inventory.dm
> Модули киборгов видны на экзамине

- code/modules/mob/mob_helpers.dm
Шанс проглатывания гласных уменьшен c 33% до 12%. "Я" больше не заменяется, "е" заменяется на "э".
Шанс замены согласных увеличен с 33% до 40%.
Шанс смены регистра на заглавный уменьшен с 20% до 15%.
close #2741
> Ослабление эффекта пьяного бормотания

- code/game/machinery/recharger.dm
- code/modules/clothing/spacesuits/rig/modules/combat.dm
- code/modules/clothing/spacesuits/rig/suits/ert.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
- code/modules/mining/machine_vending.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/projectile/beams.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
- code/modules/research/designs/protolathe/dp-rig.dm
1.РИГ модуль - плазменный резак, не существует.
Это вообще была странная вещь, теперь ее нету.
2. Добавил перезарядку через твердый форон, убрал зарядку через зарядное устройство.
Работает только для "опасного" режима, на "безопасный" режим не влияет, как и просили в иссуе.
3. Добавил возможность сменить режим на "безопасный", он не будет отрывать конечности, будет наносить меньший урон (7), но не будет тратить заряд и будет так же эффективно добывать руду, как и "опасный".
4. Убрана старая система отрыва конечностей.
Превращаем резак в отличный шахтерский инструмент, путем уменьшения урона и давая бесконечный заряд.
close #2431
> Исправление резака

- code/game/area/areas.dm
- code/game/sound.dm
- maps/shared/exodus_torch/areas.dm
все кто выключает эмбиенс в префах ставьте глаза под этим пром
выпилил наиболее кринжовейшие эмбиенсы что бросались в уши
- в морге ветер вообще пиздец
- звуки кошмара из прея в техах, nuff said
помимо этого общая громкость эмбиенса была срезана в половину, дабы ни у кого в случае чего не подпрыгивало давление от неожиданных звуков
да я в курсе что один из эмбиенсов шахты это вообще тоади оне - антайтлед но я решил оставить ибо где ещё услышишь
> Трогаем эмбиенс.

- code/modules/mob/living/silicon/robot/life.dm
Замена "traitor" на "Traitor"
✅ Я ознакомился c Guide to Contribute.
> fix(life): replace "traitor" to "Traitor"

- code/modules/mob/living/silicon/robot/laws.dm
Замена "traitor" на "Traitor"
✅ Я ознакомился c Guide to Contribute.
> refactoring(laws): replace "traitor" to "Traitor"

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Что раньше не закодили? Один символ заменить.
resolve #2797
> fix(chloralhydrate.affect_blood)

- code/modules/tables/flipping.dm
Никаких ящериц и слаймов, переворачивающие столы.
resolve #2831 
Но код скомпилировался!
> fix(do_flip): add validate before flip

- code/game/objects/buckling.dm
Фиксим фичу, что мыши(дионы) могли баклить людей к стульям.
resolves #1904
> fix(tweak(mousebuckle)): simple_mobs can't longer buckle other mobs

- code/game/gamemodes/changeling/helpcode.dm
хер его знает как этот майнд прыгал во время прока и успевал занулливаться
close #2764
> Твикаем код прока infest и молимся чтобы ничё не сломалось

- code/_global_vars/logging.dm
- code/_helpers/logging.dm
- code/controllers/configuration.dm
- code/game/world.dm
- code/modules/client/asset_cache.dm
- code/modules/client/client_procs.dm
- config/example/config.txt
* Сделал запись общих логов по дням, вынес детализированные логи (debug, href, ...) в отдельные папочки
* Добавил опцию конфига, которая включает/отключает дебажные подробные логи
* Удалил пару логов, которые больше не нужны
> tweak(logging): save common logs by days, add config option for verbose logs

- code/game/antagonist/outsider/raider.dm
До правок воксам надо было выкинуть кого-нибудь за борт для победы, что прямо противоречит декларируемым целям и условиям выигрыша. Изменение приведет это к ожидаемому поведению.
Чтобы протестировать это на локалке надо либо нагонять туда толпу мультиакков, либо изменять условия запуска режима. Проверю позже.
> Leave no vox behind

- code/_onclick/hud/_defines.dm
- code/game/machinery/kitchen/cooking_machines/_cooker.dm
- code/modules/clothing/suits/armor.dm
Четыре дефайна для интерфейса ИИ, кодер действовал наверняка. Дублировался тип сватовского плаща, где происходила попытка обращения к родительскому проку. И в пустом ветвлении парсер на точку с запятой жаловался.
> refac(misc): multiple definitions

- code/modules/paperwork/pen.dm
всем привет с вами хеддев оникса
я запустил локалку до фикса ручки
оказывается просто надо выбрать харм чтобы успешно стабать в ебало
спасибо за внимание
> Revert "Ручки из аплинка теперь не пишут на голове."

- code/modules/food/replicator.dm
Хентай что-то умер, решил допилить фичу.
Добавил обозначения, что у устройства есть микрофон.
Добавил проверку на кодовые слова на русском
Результат:
close #1790
> Репликатор

- code/_helpers/text.dm
порт куска кода с тг о санитайзе имени персонажа
это лютый костыль и вообще надо будет в будущем полностью всё перекопипащивать
> запрещаем лишние (русские) символы в имени персонажа // /proc/sanitizeName refac

- code/modules/mob/living/carbon/human/appearance.dm
- code/modules/mob/living/carbon/human/species/species_getters.dm
- code/modules/nano/modules/human_appearance.dm
- nano/templates/appearance_changer.tmpl
- Добавил кнопку в ченжер для выбора бодибилда.
- Запилил санитайз при смене гендера дабы никто не обузил мужские стейты на трапах.
Хотя бы спрайты одежды дебажить проще станет.
> Мгновенно меняем бодитайп в аппеаранс ченжере без лишних затрат времени и энергии.

- code/game/world.dm
> Мелкобуквенность сосет

- code/_helpers/text.dm
спасибо эпикус отличное ревью
я тоже долбоёб отличное ревью
> хотфикс санитайза

- code/game/objects/items/stacks/matter_synth.dm
- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/core/printer.dm
- code/modules/mob/living/silicon/robot/drone/drone_items.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/mob/living/silicon/robot/robot_upgrades.dm
- code/modules/research/mechfab_designs.dm
Добавил научным киборгам модификацию для производства интегралок.
Состав:
1. Все инструменты, которые есть у людишек для создания интегралок.
2. Специальный принтер для работы как будто человек, все доступные модификации на принтер - активны.
3. Манипулятор для работы с интегралками.
Мелкие исправления логики интегралок для работы с киборгами.
Известный баги, который я не смог пофиксить: киборги не могут переключиться между вкладками в интегралками - решение: менять вкладки и проводить работы со схемой рядом со столом.
Возможно я не так сделал интегралку, но 'ranged sensor' возможно использовать только как 'sensor', при использование в манипуляторе
Иссуев на эту тему мною не было замечено.
> Интегралки киборгам.

- code/_helpers/logging.dm
- code/game/world.dm
- code/modules/admin/admin.dm
- code/modules/client/client_procs.dm
> нормальный хреф_логгинг

- code/game/objects/items.dm
- code/game/objects/structures/crates_lockers/closets.dm
- code/modules/mob/living/carbon/human/human_defense.dm
Был уверен, что вчера залил ПР. Бывает.
- Блокирование мечом/щитом/etc. в основной руке теперь тоже жрёт стамину, но меньше.
> Energy Sword nerf

- code/datums/uplink/devices and tools.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/reagents/reagent_containers/glass.dm
Набор для чистки включает:
(ведро полное, ящик с мешками для трупов хранит в себе 10 штук мешков)
close #2644
> Добавил набор для чистки в аплинк.

- code/game/objects/structures/signs.dm
> Фиксим дюп табличек

- code/_helpers/text.dm
Тапок забайтил, что я ему все сломал. На самом деле сломал он все сам((((
Пытаться складывать коды символов в строку вместо самих символов - было не самой лучшей идеей. Хотфикс, который начал скипать символы - еще веселее.
> fix(sanitize_name): make it works correctly, remove excess comments

- code/game/machinery/cell_charger.dm
- code/game/machinery/recharger.dm
- code/modules/mob/living/silicon/robot/drone/drone_items.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
Дал научному/инженерному/[вставьте название модели киборга, у которого схожий гриппер с предыдущими сюда] возможность вставлять/вынимать батарейки в recharger/cell recharger.
Дал научному киборгу возможность хватать любой синтетический орган, добавил ему мультитул и провода для проведений операций над синтами и не только.
resolve #2192 (PSU слишком legacy для меня)
> Улучшение киборгов

- code/game/machinery/telecomms/broadcaster.dm
- code/game/objects/items/devices/radio/headset.dm
- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/hear_say.dm
_Теперь никто из ваших подчиненных не сможет прослушать ваше сообщение по рации о том, как у Вуди встала шишка._
Командный режим присутствует только у наушников глав, и только. Переключить его можно при помощи альт-клика или же контекстного меню, при этом держа его в руках.
close #1428
> Командный режим для наушников глав

- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/adminjump.dm
Группирует список мобов в админских менюшках аналогично вербу "_Follow_" у гостов.
Затронуты вербы:
1. Get mob;
2. Jump to mob;
3. Man up.
> update(admin_verbs): grouping

- code/game/antagonist/antagonist_helpers.dm
Фиксим критическую проблему спавна любого режима
> fix(antagonist): fix runtime in can_become_antag proc

- code/game/objects/items/weapons/cigs_lighters.dm
Хотфикс курительной трубки.
closes ~~[багрепорт из дискорда](https://discord.com/channels/414832443384659968/686884175822716953/745330949696389240)~~ #3174
> fix(smokable_pipe): lightning

- code/modules/client/preference_setup/global/preferences.dm
- code/modules/mob/living/silicon/robot/login.dm
- code/modules/mob/login.dm
Добавил преф на дефолтный режим хоткеев. По дефолту выключен. Если включен, то при вселении в моба вместо вырубания хоткей режима оный врубается.
> Префы на хоткеи

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Мышь не сможет прокусить скафандры или бронированные предметы - риги, галоши, jackboots, etc. Кусать части тела, не покрытые скафандром или броней, сможет.
close #1830
> nerf(mouse): mice can't bite through armor and thick clothes

- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/typing_indicator.dm
Теперь сначала закрывает, затем, если нужно, спрашивает, что внутри (обычно не нужно). По идее должно уменьшить задержку закрытия на целый пинг.
> Небольшая оптимизация хоткейного сея

- code/modules/client/darkmode.dm
Кодер гений, что тут сказать. Я прошелся регексом, дифф не читал.
> Рефакторинг тем

- code/modules/clothing/head/beanies.dm
> fix(obj/item/clothing/head/beanie/white): change name

- code/modules/power/cell.dm
- code/modules/research/designs/protolathe/dp-engineering.dm
В текущий версии билда фабрикатор просто создается предмет, без обновление его иконки ( к примеру батарея ), данный ПР решает это недоразумение.
Я не нашел иссуи, которые ссылаются на проблему описанную в данном ПРе.
> Исправление беекода в создание батареек в фабрикаторе/протолате

- code/game/machinery/kitchen/gibber.dm
Добавил проверку подобно той, что в коде крюка (хз, почему я тогда туда ее добавил, а сюда нет), чтобы не рантаймило от симплэнималов без реагентов.
closes  #3317
> Фикс гиббера

- code/modules/lighting/lighting_overlay.dm
омега говнокод пролежавший с начала своего создания прожил больше трёх лет чисто из-за костыля с харддделом
те кто не в курсе, при смене турфа оверлеи света не удалялись из контентов
close #2087
close #1964
> fix(light): destroy

- code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/modular_computers/file_system/programs/command/comm.dm
В нескольких местах использования прока Announce на вход подавался санитайзенный вход, который потом опять санитайзился, давая лишний мусор на выходе.
closes #3274
> Фиксы кракозябр в аннонсах

- code/modules/mob/living/silicon/robot/drone/drone_items.dm
Добавил возможность киборгам брать фрукты, овощи.
Теперь киборг может брать яйца из egg box, брать предметы из lunchbox.
close #2849 , close #2630 .
> Исправление сервисного киборга.

- code/modules/clothing/spacesuits/breaches.dm
Кодер гений. Теперь эта штука не должна хватать путь датума вместо дескриптора.
closes #3350
closes #3130
> fix(breaches): fixes breach seal message

- code/modules/mob/living/carbon/human/species/outsider/vox.dm
- code/modules/organs/external/vox.dm
С отсутствующим желудком особо не наешься.
fix #2522
> Позволяем воксам не голодать

- code/game/machinery/telecomms/machine_interactions.dm
Собственно, теперь телекоммы ищут мультитулл не только в руке, но и в составе комбинированных инструментов.
close #1208
> fix(telecomms): Продвинутый мультитулл может в телекоммы

- code/modules/spells/spellbook.dm
Некоторые особо умные игроки умудряются сидеть весь раунд у себя на базе, фармя себе поинты.
- Инвест нельзя прожать находясь не на станции.
- Инвест автоматически прерывается если спеллбук оказывается за пределами станции. С возвращением очков.
Напомню ещё раз, ПР не аффектит никакие другие системы спеллбука за исключением инвеста поинтов.
> Запрещаем инвестить поинты визардам находясь на не станционных Z-уровнях.

- code/controllers/configuration.dm
- code/game/world.dm
- config/example/config.txt
> фикс заголовка

- code/controllers/subsystems/skybox.dm
кто-то успел обесцветить космос, потому пора вернуть ему былую красоту(почти былую)
и ещё вырубил смешной слой звёзд которые вообще тёмные
> tweak(skybox): major improvement

- code/_helpers/text.dm
- code/modules/modular_computers/file_system/programs/command/card.dm
- nano/templates/identification_computer.tmpl
Добавил поля в программу модификации карты, теперь можно нормально регистрировать мирнома... Возвращать утерянные карты экипажу.
Добавил возможность по одной кнопке загрузить из манифеста все необходимые параметры на карточку.
close #2433
> Обновление программы редактирования карты

- code/modules/power/singularity/collector.dm
Выпиливает `return 1`, который оверрайдит все накопленное в . сообщение.
closes #3337
> Фикс экзамайна коллектора

- baystation12.dme
- code/modules/storyteller/storyteller.dm
- code/modules/storyteller/storyteller_admin_secret.dm
- code/modules/storyteller/storyteller_character.dm
- code/modules/storyteller/storyteller_metric.dm
- code/modules/storyteller/storyteller_trigger.dm
- code/modules/storyteller/triggers/spawn_antagonists_triggers.dm
- nano/templates/storyteller_control_panel.tmpl
Добавил в Secrets специальную кнопку, которая открывает панель управления Сторителлером.
В панели можно тыкать все триггеры сторителлера и вызывать их вручную, а также просматривать метрики и их статистику.
> feat(storyteller): Storyteller Control Panel for admins

- code/modules/mob/living/silicon/robot/robot_modules.dm
Заменена человеко-дубинка стандартного борга на СУПЕР ПУПЕРСКУЮ с бесконечным зарядом.
close #2629 
> fix(/obj/item/weapon/robot_module/standard): replace stunbaton

- code/modules/mob/new_player/new_player.dm
Внешность и имя СНАЧАЛА копировалось на моба, а уже потом поменялось. Поменял, теперь сначала меняются преференсы у клиента при проверке банов, а уже затем переносится на нового моба.
close #2095
> Исправление банов на имя и внешность

- code/game/gamemodes/changeling/changeling_powers.dm
- code/modules/mob/living/login.dm
Убрал мешанину с процами и вербами, запихнул все в один верб.
И дифф в гитхабе поломался, печально
И я не понял как addtimer() работает
close #3325 , close #1575 , close #624 .
> refact(changeling_revive) all-in-one proc

- code/__defines/subsystems.dm
- code/_helpers/global_access.dm
- code/datums/communication/ooc.dm
- code/modules/admin/EAMS.dm
- code/modules/admin/admin.dm
- code/modules/admin/topic.dm
- code/modules/client/client_procs.dm
- code/modules/mob/new_player/new_player.dm
Сделал EAMS подсистемой + добавил пару небольших фич.
Выполняет часть #1966.
Много чего поменял здесь. Вроде проверил локально, но остается вероятность что EAMS сломается после этого ПРа. На крайняк можно отключить её через конфиг.
> feat(eams): make eams subsystem and add some features

- code/modules/mob/mob.dm
Исправляет обработку экзамайна фейковой внешности (с #3068 экзамайны пишут в возвращаемую строку, а не в чат).
> Мелкофикс экзамайна

- code/game/jobs/job/assistant.dm
> removes visitors

- code/modules/mob/living/carbon/human/species/station/lizard.dm
Они немного СДВИГАЛИСЬ, а одежда оставалась. Честно говоря, я почти нихуя не знаю как я это сделал, вроде что где ставится и что-то понял в итоге. Пустой шаблончик был немного другого размера и из-за этого трансформировалось всё не очень. Убрал использование особенного шаблона, который ящерам был не нужен.
А, да, я запустил локалку, надел инженерные обтягивающие шмотки и погулял полежал. Всё в порядки вроде, хвосты не отваливается. Но я боюсь как бы это не всплыло где-то в ОСОБОЙ ЯЩЕРСКОЙ ПОЗЕ для которого как раз нужен был тот шаблон. Вроде не всплывает.
close #1922
> Исправил проблему с спрайтами у ящеров.

- code/game/objects/items/weapons/tanks/tanks.dm
Исправил изменение спрайта баллонок при откручивании или прикручивании различных частей.
resolves [#1786](https://github.com/ChaoticOnyx/OnyxBay/issues/1786)
> Мелкофикс баллонок

- code/game/jobs/job/civilian.dm
Выполнил иссуй Родиала
fix #559
> Фикс доступа АВД

- code/modules/mob/living/silicon/robot/drone/drone_items.dm
Добавил исключения в манипулятор киборга для того, что бы он смог брать батарею из бура
Данный ПР дает возможность киборгу забрать из бура батарею.
Затрагивает #2789 .
> Проблема с киборгами и бурами.

- code/modules/client/client_procs.dm
> gunchat mir pobedil

- code/modules/research/designs/protolathe/dp-engineering.dm
- code/modules/research/designs/protolathe/dp-misc.dm
- code/modules/research/designs/protolathe/dp-rig.dm
- code/modules/research/designs/protolathe/dp-robotics.dm
- code/modules/research/designs/protolathe/dp-surgery.dm
По факту починил одну опечатку, но решил порыться и подполировать некоторые вещи, в часности добавил имена СМЕСАМ, и починил в некоторых местах проблемы с большой буквы. Модули РИГа всё ещё называются с большой буквы.
Fixed #3440.
> Починил пару опечаток в рецептах для протолата.

- code/modules/onyxchat/browserOutput.dm
порт
https://github.com/discordia-space/CEV-Eris/commit/ee288fa9fa51ced56ed8a1878ce4267b23255a30
> criticalfix(onyxchat): cookie crash

- code/game/antagonist/outsider/raider.dm
- code/game/gamemodes/objective.dm
Починил все существующие задачи у воксов, а именно:
- Похищение
- Кража 
- Выживание (Ака не потерять никого из своих)
Все задачи требуют того, чтобы вы или цель задания находились или же на базе, или же на припаркованном у базы шаттле, в ином случае провал.
Также поправил опечатку в одной из задач, в которой сказано, что нужно украсть гравитационный генератор. На деле же там нужно украсть генератор сингулярности. 
Задача на выживание не обязывает вас или ваших напарников быть живыми на базе, поскольку по лору Воксов они имеют технологии, способные воскрешать (если я правильно всё помню). 
fix #2570
fix #2571
fix #2570
#2778 (зачем пилить сразу два бага в одном репорте?)
> Починка заданий у воксов

- code/modules/client/preference_setup/global/preferences.dm
- code/modules/donations/donator.dm
Фиксим сохранение цвета никнейма OOC между раундами.
close #2669
close #2736
> fix(donations): fix resetting of ooc_color option

- code/_global_vars/lists/flavor.dm
> Крокет в жукбокс

- code/game/objects/items/weapons/lighters.dm
Теперь спичкой можно прикурить
close #2221
> Мелкофикс спичек

- code/modules/reagents/Chemistry-Machinery.dm
close #1178
Теперь можно засовывать в миксер форон заказанный в карго (стак по 10)
> Мелкофикс блендера

- code/modules/clothing/spacesuits/rig/modules/computer.dm
= not all machines are now checked to be rnd consoles when trying to ninja them
resolves #1930
> Нинжа не пытается скачать уровни исследований со ВСЕХ консолей

- code/modules/admin/admin_attack_log.dm
> fix(log):logs without (JMP) and stuff

- code/game/objects/items/weapons/smokables/smokables.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Ладно, это было смешно.
- Никотин усваивается организмом вдвое быстрее. Не сильно заметно, ибо всё равно **ОЧЕНЬ** медленно.
- Табак теперь выкидывает в организм намного меньше никотина. В частности, в пять раз. Примерно на уровне сигарет до того-самого-обновления. Однако, непрерывное курение всё ещё может уебать.
- Ужасный табак выдаёт втрое больше никотина, а хороший - на 25% меньше.
> Курение убивает, но не так сильно

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
close #2509
У mead нет особенного спрайта коктейля, поэтому он и не отображался в кружке.
> Мелкофикс mead'а

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/helpcode.dm
- code/modules/mob/living/carbon/human/species/species.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/stack.dm
- code/modules/organs/organ.dm
Надеюсь, что исправил баг со структурой, я сделал вызов того же прока "возрождения" биоструктуры, ~~оставил язвительный комментарий по поводу рук того, кто это кодил до меня~~, что было до моего влезания в код.
Еще поменял местами подтверждение ревайва и проверки на регенерацию, что бы не вызывало лишних вопросов у игроков.
У меня тоже растут руки не из того места.
Известные баги:
stack теперь остается, но является органическим.
close #3433 close #3402 close #1971
> tweak(revive) fix changeling organ remove

- code/modules/mob/hear_say.dm
Рефакторинг прока: view, get_dist, isghost, и get_preference_value вызываются один раз
Касается issue #1958
> optimization(hear_say)

- code/datums/outfits/jobs/civilian.dm
Тайтлрелейтед
close #2339
close #3534
> Price scanner и радио торговцу

- code/game/antagonist/outsider/raider.dm
> Воксы не могут менять имена

- code/game/objects/structures/iv_drip.dm
Добавил отдельное условие на то, что ты не помер, при попытке поставить "set transfer amount"
fix #3531 
- [ *] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ *] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [* ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ *] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
> Убрал баг с капельницей

- code/modules/modular_computers/file_system/program.dm
Теперь емагом можно активировать программы
close #3556
> tweak(can_run programm) emag acces fix

- maps/exodus/exodus_jobs.dm
Добавляет ксеносам право играть за торговцев.
> tweak(Exodus_jobs) Xenomerchants

- code/game/objects/structures/barsign.dm
Добавил то, что просили. Теперь когда бармен/кто-то ещё с доступом к бару долбанёт картой по табло будучи культистом, то появится возможность выбора специального табло нарси
close #3589
- [x ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
> Добавил культистам возможность выбора таблички нарси в баре

- code/modules/client/preference_setup/antagonism/02_setup.dm
- code/modules/client/preference_setup/general/05_background.dm
Переместил пункт Exploitable information в префах из ролесов в генерал, ну и небольшие правки в соответствии с вашим CC
Для удобства всех разумных сделал подгрузку информации из(в) файлов в том порядке, в котором она и есть в окне префов
<details>
<summary>Оффтоп</summary>
Пожалуйста, скажите если что-то сделал не так как надо сразу, а то потом будет "ты все время так делал? У нас по-другому"
</details>
Resolves #2429
> Перемещаем Exploitable information

- code/modules/admin/EAMS.dm
- code/modules/admin/multiaccount.dm
- code/modules/onyxchat/browserOutput.dm
> Фиксы-фиксы-фиксы

- code/game/objects/buckling.dm
Теперь хостайлов нельзя привязывать к чему-бы то ни было.
fixes #2067
> Всех хостайлов нельзя пристегивать

- code/datums/outfits/jobs/_defines.dm
> Фикс сумки вирусолога

- code/modules/mob/living/carbon/alien/diona/gestalt/gestalt_verbs.dm
- code/modules/mob/living/carbon/alien/diona/nymph_gestalting.dm
> Перенос вербов дион

- code/modules/reagents/Chemistry-Machinery.dm
> Chemmaster fix

- code/modules/reagents/reagent_containers/food/drinks/bottle.dm
> Викс Фиски

- code/game/machinery/kitchen/microwave.dm
- Исправлены неправильные сообщения при закреплении/откреплении микроволновки монтировкой.
- Исправлен удар по микроволновке после попытки закрепления/открепления монтировкой.
> fix(microwave)

- code/game/machinery/bioprinter.dm
- code/modules/mob/living/silicon/robot/robot_parts.dm
Добавил батарею в принтер органов робототехников.
Вероятно исправил баг с органическими частями тела и органами, теперь части тела роботизируются правильно (вместо 1 - "Unbranded")
close #545 , close #3311
> Батарея в принтере. Исправления бага с полуорганиками-полусинтами.

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/helpcode.dm
- code/modules/mob/living/carbon/human/species/species.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/stack.dm
- code/modules/organs/organ.dm
В результате тестирования багов генокрада, был обнаружен баг в моем смерженом ПРе.
Я удалил нейронить из списка органов, которые не надо удалять, в скором времени, надеюсь, смогу побороть его.
Добавил оповещение о начале ревайва генокрада.
Добавил специальный прок органам для действий _послесоздания_, прописал генкооргане, что бы он правильно обрабатывал свое создание. 
~~Надеюсь багов не будет... Пожалуйста?~~
> Чиним ревайв генокрада, версия N

- code/game/turfs/simulated/floor_attackby.dm
Кажется, выводить сообщение было не лучшей идеей.
> Removes "You don't feel like attacking the floor" spam

- code/modules/clothing/glasses/glasses.dm
> Выключаемые science googles

- code/_helpers/game.dm
- code/game/atoms.dm
- code/modules/mob/mob.dm
- Портирован get_mobs_in_radio_ranges(), должен работать быстрее.
- Чутка подкручен get_mobs_and_objs_in_view_fast(); работает лучше, хотя всё ещё не идеально;
до/после:
/proc/get_mobs_and_objs_in_view_fast 0.068 0.098 0.101 0.007 64 
~~/proc/get_mobs_and_objs_in_view_fast 0.051 0.077 0.077 0.001 62~~
/proc/get_mobs_and_objs_in_view_fast 0.053 0.076 0.076 0.005 74
> Performance tweaks

- code/modules/clothing/masks/miscellaneous.dm
> Еда и шарфы

- code/modules/client/preference_setup/loadout/loadout.dm
Добавил скидки в лоадаут. Сделал скидку на все предметы 50% согласно решению сената.
> feat(loadout): add discounts!

- code/game/objects/items.dm
Фильтры круто, в теории должно работать чуточку дешевле нынешнего анального бленда.
> generate_blood_overlay() update

- code/game/area/area_power.dm
- code/game/objects/items/devices/radio/intercom.dm
Интеркомы зачем-то процессились. Теперь не процессятся, питание проверяется в зоне при power_change().
> Removes intercoms processing

- code/modules/mob/living/simple_animal/parrot.dm
Было ошибкой давать возможность попугам садиться на те вещи, над которыми они могут пролететь.
> Фикс попугов

- code/_helpers/game.dm
я шо знал шоле что радио для гостов это фича
> fix(ghost radio)

- code/modules/mob/living/simple_animal/parrot.dm
close #3804
Добавил еще проверку на инициатора дропа, чтобы когда пиздишь игрока-попуга, ему не срало в чат "You have nothing to drop!"
- [no] Я запускал сервер со своими изменениями локально и все протестировал.
> Фикс сообщений попуга

- code/datums/uplink/devices and tools.dm
- code/datums/uplink/highly_visible_and_dangerous_weapons.dm
Удалил пульс райфл с 36 выстрелами по 45 дамага и 40 ап из аплинка.
Повысил цену на флешдарк для триторов (65) и нюки (129, чтобы хватило на мыло)
> gamedesign goes brrrrr

- code/modules/projectiles/gun.dm
опять
пришлось пожертвовать фарсаундом в пользу симплисити
стерео видео пример https://youtu.be/yXSoajK87p0
рип игорь
> фиксим направление звуков выстрела

- code/game/objects/items/paintkit.dm
ха ха New и Initialize в одном и том же объекте, где второй вообще с куделом
fix #3652
> всем привет с вами тапок и сегодня мы фиксим paint/ripley/random

- code/_helpers/icons.dm
- code/game/objects/items/weapons/cards_ids.dm
- code/modules/mob/new_player/preferences_setup.dm
- code/modules/modular_computers/file_system/crew_record.dm
- code/modules/organs/external/_external_icons.dm
- Порт ТГшного getFlatIcon();
- Исправлен спамящий рантайм с null.update_hair();
Новый getFlatIcon() работает примерно вдвое лучше нынешнего легаси-говна. Попутно, вроде как, пофиксилась проблема с непрогружающимися фотками в Crew Records/на карточках.
> Ports TG's getFlatIcon()

- code/game/objects/buckling.dm
- Отключена возможность пристёгивать мобов с соседних со стулом/кроватью/etc. тайлов, если у цели выбран отличный от HELP интент и цель не лежит/связана.
> tweak(buckling): nerfs combat buckling

- code/game/objects/items.dm
- code/modules/mob/living/carbon/human/human_defense.dm
Больше никаких "The riot shield gets shot out of Vanya Pupkin's hands by a knocked."
> Фикс некорректного сообщения об отстреле предмета из руки

- code/controllers/subsystems/supply.dm
- code/game/gamemodes/events/holidays/Christmas.dm
- code/game/machinery/adv_med.dm
- code/game/machinery/computer/guestpass.dm
- code/game/objects/effects/manifest.dm
- code/game/objects/items/devices/scanners.dm
- code/game/objects/items/devices/taperecorder.dm
- code/modules/economy/Accounts.dm
- code/modules/modular_computers/hardware/nano_printer.dm
- code/modules/paperwork/misc.dm
- code/modules/paperwork/paper.dm
- code/modules/psychotronics/loot.dm
Я ебал нахуй это дерьмо.
Закончил миграцию для paper с New на Initialize
Вроде прошел по коду, рантаймам, новое решение не вызывает проблем
> Ебанная бумага

- code/datums/supplypacks/engineering.dm
- code/datums/supplypacks/medical.dm
- code/datums/supplypacks/science.dm
- code/datums/supplypacks/security.dm
close #1055
ПР добавляет возможность покупки РИГов в карго. Да, запилил почти через год, но не через год же!
Цены тестовые, но вроде нормально накопить можно. Если что, потом удешевим, главное что возможность купить появилась.
- [ x ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ x ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ x ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ x ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
> Add(rigs): Add rigs to cargo

- code/modules/client/client_procs.dm
Это костыль, но работает. По факту передвинул проверку на лимит ниже подгрузки чата. Предположительно из-за этого не работал alert().
close #3392
> Кик из-за превышение лимита игроков не дает сообщения игроку.

- .travis.yml
Бампнул травис до версии на хосте.
> Бамп трависа

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/helpcode.dm
Добавил проверку на стазис в проке перемещения биоструктуры
Так же убрал пожирание химикатов в мимик войсе в стазисе.
close #3947
> changeling update

- code/modules/client/preference_setup/loadout/lists/gloves.dm
- code/modules/client/preference_setup/loadout/lists/headwear.dm
- code/modules/client/preference_setup/loadout/lists/storage.dm
- code/modules/client/preference_setup/loadout/lists/suits.dm
- code/modules/client/preference_setup/loadout/lists/uniforms.dm
Пополняем донатный лодаут 13-ю вещичками.
Вообще его как-то систематизировать надо будет, а то такой огроменный лист ни к чему.
> tweak(loadout): add donate items (8, 22, 23 of SC)

- code/game/objects/structures/railing.dm
Сломал прошлый пул реквест кривым ребейзом. Фикс прохода через стены с помощью перил. 
fix #3573
> Пересоздание сломанного пул реквеста(фикс перил)

- code/modules/projectiles/guns/magnetic/magnetic.dm
- code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
Впилил перегрев при стрельбе из коилгана.
С некоторым шансом, если слишком много стрелять из коилгана, он:
а) Не стреляет с затратой энергии на выстрел.
б) Бьёт током владельца, при этом не стреляет.
в) Взрывается.
Шансы зависят от перегрева, взрыв при перегреве в 30 случается с шансом в ~10%.
closes #3779
> buff(coilgun): removes explosion chance

- code/modules/projectiles/guns/magnetic/magnetic.dm
- code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
ПР был замержен без геймдизайнерского одобрения.
> Revert #3821

- code/game/objects/items/stacks/nanopaste.dm
Исправлю возможность научным киборгам делать on-going ремонт.
Да-да, это работает прямо во время битвы.
> tweak(nanopaste) fix battle cyborg heal

- code/controllers/subsystems/supply.dm
Тостер сломал бумагу, я починил
fixes #4016
> Опять бумажное, опять карго

- code/modules/client/preference_setup/loadout/lists/eyegear.dm
Ну да, чутка перегнул, бывает. 
- В лодаут добавлена мезонная повязка, 3 очка, рестрикт на технические роли.
- В лодаут добавлен медицинский визор, 3 очка, рестрикт на медицинские роли.
> Возвращаем лодаут

- code/modules/detectivework/tools/evidencebag.dm
- code/modules/mob/living/silicon/robot/robot_items.dm
- code/modules/mob/living/silicon/robot/robot_upgrades.dm
Починил контейнер для улик, так же добавил еще один способ добавления в пакет - нажать предметом по пакету, так же поменял текущий метод, с перемещение пакета на предмет, на предмет на пакет, так же провел небольшой рефакторинг кода, теперь вроде все работает заебись. 
Добавил в модуль модификации охранного киборга, а именно детективный модуль модификации, а именно в "контейнер детектива" возможность брать контейнер для улик, так же добавил возможность их создавать.
Увеличил количество хранимого в "контейнере детектива" с 8 до 12.
> Evidencebag fix

- code/modules/client/preference_setup/loadout/lists/food_drinks.dm
- code/modules/reagents/reagent_containers/food/lunch.dm
- Во фляжках из лодаута снова можно выбирать напитки;
- Из выбора напитков убраны сигбрау и грыбное пыво;
> Лодаутно-фляжечное

- code/modules/projectiles/guns/magnetic/magnetic.dm
- code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
This reverts commit 2f0e280bc236f95064a6330b21d8dacb7ca0df36.
#3821, но заново.
>Впилил перегрев при стрельбе из коилгана.
>С некоторым шансом, если слишком много стрелять из коилгана, он:
а) Не стреляет с затратой энергии на выстрел.
б) Бьёт током владельца, при этом не стреляет.
в) Взрывается.
Шансы зависят от перегрева, взрыв при перегреве в 30 случается с шансом в ~10%.
> tweak(coilgun): removes explosion chance, add overheat mechanics.

- code/modules/power/pedal_gen.dm
2 миллиона строк изменений, хотфикс который мы заслужили.
close #4105
> fix(pedal_gen) chair from pedal_gen fix

- code/modules/projectiles/guns/energy/mining.dm
Пообещал педальке багфикс за антага, выполняю обещание.
Аффтар кода перепутал инициализацию, в итоге launcher у него был null
fix #4075
> Шахтёрско фикс

- code/modules/power/fusion/core/core_control.dm
- code/modules/power/fusion/fuel_assembly/fuel_control.dm
- code/modules/power/fusion/fuel_assembly/fuel_injector.dm
- code/modules/power/fusion/gyrotron/gyrotron_control.dm
Совсем мелкий фикс доступа гостов к РАСТу.
> Госты больше не могут взаимодействовать с консолями РАСТа

- code/modules/modular_computers/file_system/programs/generic/records.dm
Добавил санитайза.
close #4227
> tweak(crew records) security updates

- code/game/objects/structures/girders.dm
Пофиксил название культогирдера, раньше он назывался просто "cult"
> fix(cult_girder)

- code/game/objects/items/weapons/material/ashtray.dm
Теперь пепельница занимает столько же места, сколько и патч на plate carrier.
close #4193
> Исправление размера пепельницы в инвентаре

- code/modules/virus2/effect.dm
occasionally sleep in full processed procs are gonna fuck your ass
✓  Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✓  Я внимательно прочитал все свои изменения и багов в них не нашел.
✓  Я запускал сервер со своими изменениями локально и ~~все протестировал.~~
✓  Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
upd: ah eys
pickrelated
before
after
> sopli ne zamedlâût mobkontroller do skorosti ebanoj čerepahi blâtʹ

- code/datums/movement/robot.dm
Пофиксил проблему описанное в иссуе.
close #4305
> tweak(robot movement) robot lockdown movement fix

- code/modules/reagents/Chemistry-Recipes.dm
- Теперь химическая вспышка нормально проверяет защиту глаз, а не дебильно проверяет на наличие солнцезащитных очков. Уебите дебила, который это изначально кодил.
- Химическая вспышка вблизи не только укладывает космонавтиков, но и станит.
> fix(flash powder): correct protection check

- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Починка переработки стульев складных в автолате. 1000 металла -> 2000 металла.
close #4194
> Теперь правильные стулья

- code/modules/clothing/glasses/hud.dm
- Фикс нерабочей матрицы ночного видения;
> fix(night vision matrix)

- code/game/gamemodes/changeling/helpcode.dm
- Генкомобы теперь могут ходить в космосе/невесомости, если есть за что цепляться. Как и абсолютно все другие мобы.
Я не знаю, нахуя Филя захардкодил им невозможность это делать. Гений, видимо.
> Опять генокрады

- code/game/mecha/equipment/tools/tools.dm
- Теперь сервоускоритель по умолчанию выключен;
> tweak(servo accelerator): off by default

- code/modules/surgery/implant.dm
Во время тестирования возможностей интегралок заметил, что самый большой "кейс" можно положить в человека, хотя это никаким образом не должно было получиться.
Теперь данная проблема исправлена.
> tweak(implant surgery) add forgotten check

- code/game/machinery/doors/windowdoor.dm
- code/game/objects/structures/inflatable.dm
- code/modules/clothing/clothing.dm
- code/modules/shield_generators/shield.dm
- Исправлен баг, позволявший поднимать одежду с помощью Pick up через окошки/створки;
- Надувные двери и стены теперь блокируют атмос;
- Щиты в режиме Atmospheric Containment теперь блокируют атмос;
> fix(windows+atmos): clothing pick-up, atmos block

- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/mob/living/carbon/brain/brain.dm
- code/modules/mob/living/silicon/pai/pai.dm
- Исправлена невозможность передвижения за pAI;
Я вообще не ебу, почему там хендлеры были переназначены. Заебался, пока пилил, видимо.
> fix(pAI): movement

- code/modules/mob/living/silicon/ai/malf.dm
Добавляет строку с отображением координат глазу ИИ
> add location to status for AI Eye

- code/modules/mob/living/silicon/robot/robot_modules.dm
Увеличивает количество ресурсов в дроне, а конкретно:
- 2 дерева на 20
- 1 пластик на 10
> update material synthesizer

- code/game/antagonist/outsider/raider.dm
Возвращен спавн карт воксам, только теперь кошелек в кармане.
close #4514
> fix vox outfit

- html/changelog.html
кто там чейнжлог просил
если кто не доволен будет чем-то правьте сами, не тупые
> changelog 25/02/21

- code/modules/surgery/surgery.dm
У нас обрезания перчаток никак не влияет на хирургию, что я считаю нелогично.
Но обрубать на совсем как по мне - слишком, поэтому я с шансом 25 процентов пропускаю выставление germs с перчаток.
~~Тут происходит унижение котов~~
close #4481
> feat(surgery) gloves didn't protect from germs if they were cut

- code/modules/research/designs/protolathe/dp-surgery.dm
Изменил цену создания улучшенного орган фиксера, убрал оттуда золото и серебро, взамен добавил пару нулей к стали и стеклу.
> tweak(organ fixer) cost tweak

- maps/exodus/frontier/frontier_define.dm
Теперь генерация должна работать, желательно залить поскорее
> fix(map) fixed exodus asteroid generation

- html/changelog.html
edit by yourself if someone merges more commitz
> change log

- code/modules/virus2/disease2.dm
> fix(virus): antigenes with adaptations

- code/modules/virus2/disease2.dm
- code/modules/virus2/effects/mild.dm
Исправлена ошибка с получением имени моба для Voice Changer Syndrome;
Исправлено лечение  Voice Changer Syndrome.
Исправлена передача Voice Changer Syndrome и других одноразовых симптомов.
close  #4554
> fix(virus): Voice changer and oneshot effects

- code/game/objects/effects/decals/Cleanable/fuel.dm
- code/modules/ZAS/Fire.dm
> fix(fire): enables fire spreading

- code/controllers/subsystems/air.dm
> мелкофиксы атмоса

- code/modules/hydroponics/seed.dm
- code/modules/hydroponics/trays/tray.dm
фингерпринтласт, не всегда доступен, вкидывание сикей человека, что посадил данное растение - идеальное решение
> feat(datum/seed) add ckey for admins' purpose.

- code/modules/virus2/diseasesplicer.dm
> fix(diseasesplicer): copy spliced effect correctly and change stage

- SpacemanDMM.toml
- baystation12.dme
- code/__defines/spaceman_dmm.dm
- code/_helpers/unsorted.dm
Добавляет поддержку [SpacemanDMM](https://github.com/SpaceManiac/SpacemanDMM) в репозиторий, а точнее специальный файл-конфигурацию для пользователей с данным расширением и несколько полезных макросов для его работы.
SpacemanDMM - инструментарий для работы с DM-языком, в котором существует проверка стандарта кода (напрмер детектинг не-полных путей) и возможность ловить ошибки в коде ещё до компиляции.
Само приложение доступно для редактора как дополнение к Visual Studio Code. После установки вы сможете компилировать билд прямо из VSC и проводить перезагрузку дримчекера, получая такое вот окошко с проблемами:
В текущем состоянии билда после одного моего фикса он выявил ... 
**301** проблем! И это без учёта не полных путей (в общей сумме где-то 1к варнингов если включать этот кодстайл). …
> experimental(dreamchecker): adds dreamchecker support to repository

- code/modules/onyxchat/browserOutput.dm
Ориентируюсь на http://www.byond.com/docs/ref/#/proc/set/background. Локальные тесты весьма производительны, один из них: https://discord.com/channels/414832443384659968/606429790316134410/817330235770929162.
close #3680
> чиним гунчат

- code/modules/mining/mine_items.dm
Портировал пару ПРов с Авроры.
https://github.com/Aurorastation/Aurora.3/pull/11042
https://github.com/Aurorastation/Aurora.3/pull/10387
https://github.com/Aurorastation/Aurora.3/pull/9419
> tweak(mine_items): port some PRs from Aurora

- code/modules/virus2/disease2.dm
> fix(update_disease): return antigen when adaptation is gone

- code/modules/modular_computers/file_system/crew_record.dm
> Fix colors

- code/game/objects/items/devices/scanners.dm
эйтиихн дейз эгоу 
close #3753
> чёрный по зелёному

- code/modules/spells/general/mark_recall.dm
> mark_recall.dm#L50 (a.k.a. non existent path fix)

- code/modules/modular_computers/computers/subtypes/preset_console.dm
Хех привет я однострочный пр да
Добавил в охранный пресет консолей охранные рекордсы, так как это забыл сделать тот, кто эти рекордсы запилил. 
close #4654
> feat(console): added security records to security preset console

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
ФИОЛЕТОВЫЙ ЖИДКИЙ ФОРОН
close #4469
> ФИОЛЕТОВЫЙ ЖИДКИЙ ФОРОН

- code/modules/mob/living/silicon/robot/robot.dm
Убрал возможность рестить за боргов, потому что эта хуйня кидает их в вечный стан, который решается только педально
fix #4544
> Убрал рест у киборгов

- code/modules/mob/living/bot/secbot.dm
вставляем костыли чтобы бипски не игнорировал когда его пиздят
выглядит как говно но работает. евейтинг фулл бот реврайт
алсо бипски теперь орёт *препейр фор джастис!* когда видит свою цель
> Обучаем бипски защищаться

- code/modules/client/preference_setup/global/05_settings.dm
Срать должно стать меньше, причину не исправляет (возможно проблема в бйонде?), но может дать наводку на источник проблемы.
close #3455
> Preferences logging

- code/modules/assembly/proximity.dm
Proximity sensor больше не срабатывает от гостов, от глаза ИИ и от мага в джаунте.
close ChaoticOnyx/OnyxBay#4618
> fix(proximity): исправил работу proximity sensor

- code/game/machinery/floorlayer.dm
- code/game/machinery/oxygen_pump.dm
- code/game/objects/structures/gas_stand.dm
- code/modules/mob/new_player/new_player.dm
> Артикльное

- code/modules/events/event_container.dm
> добавляем красивые пробелы в евент контейнер (и выпиливаем блоба из ивентов нахуй) ((опять))

- code/modules/mob/hear_say.dm
<details>
<summary>До</summary>
</details>
<details>
<summary>После</summary>
</details>
> hear_say optimization

- code/modules/onyxchat/browserassets/js/browserOutput.js
66 лайнов с регексом конечно звучит круто, но не теперь, когда билд на 513.
Вероятно, что игрокам станет попроще с этим.
Пруф того, что всё ок и без него:
> Спилил rustoutf() у ониксчатика

- code/datums/browser.dm
Исправляет рантаймы связанные с пропажей клиента
> Browser runtime fix

- code/controllers/subsystems/mapping.dm
- code/game/mecha/mecha.dm
- code/game/objects/items/weapons/smokables/pipes.dm
- code/game/objects/structures/under_wardrobe.dm
- code/modules/emotes/emote_define.dm
- code/modules/mob/living/carbon/human/species/species.dm
- code/modules/mob/living/simple_animal/bees.dm
- code/modules/paperwork/carbonpaper.dm
> Bad arg name 'nodestroy'

- code/game/machinery/status_display.dm
> Status display font fix

- code/modules/admin/banjob.dm
Исправляет рантайм, когда игрок тыкает "Ready", а контроллер джобок не загрузился.
> fix(runtime) job_master fails on server start up

- code/_onclick/item_attack.dm
ну это пиздец особенно для медицинских когда ты не можешь нормально отменить действие инструментов потому что пошёл нахуй получи по ебалу
зато теперь можно спокойно тыкать ломом космонавтов
> борги перестают пиздить людей на хелпе и начинают их тыкать

- baystation12.dme
- code/modules/mob/living/silicon/subsystems.dm
- code/modules/modular_computers/file_system/crew_record.dm
- code/modules/modular_computers/file_system/programs/ai/ai_records.dm
- code/modules/modular_computers/file_system/programs/medical/records.dm
- nano/templates/ai_records.tmpl
- nano/templates/sec_records.tmpl
Добавляет программу, где ИИ и киборги могут редактировать все "станционные" поля у рекордов.
Раньше ИИ пришлось бы открывать 3 программы для того, что бы редактировать рекорды у членов персонала, теперь одна.
Так же теперь киборги не кастрированы в возможности изменения рекордов членов персонала, медицинские киборги могут редактировать медицинские записи персонала, охранные киборги - охранные, и наоборот, считаю, что это удобно (так теперь может делать любая модель киборгов).
> feat(ai_records) add ultimate records program for AI and cyborgs

- code/modules/projectiles/guns/projectile/revolver.dm
https://www.youtube.com/watch?v=rtizjDbvIRU
> fix(tobygun)

- code/modules/modular_computers/file_system/crew_record.dm
- code/modules/modular_computers/file_system/manifest.dm
Смотри закрываемый иссуй, все сделано по нему.
Демонстрация работы:
close #2989
> feat(manifest) add departament flag manipulation things

- code/game/verbs/ooc.dm
**It just works.**
Добавил костыльный вариант для починки сломавшихся хоткеев из-за злоебучей русской раскладки. Своей активацией закрывает открытые окошка в игре. Ну и ещё что-то визуальное поломать может, наверное. Но, думаю, можно попробовать?
> Верб для починки хоткеев

- baystation12.dme
- code/controllers/subsystems/circuit_component.dm
- code/modules/admin/secrets/admin_secrets/toggle_circuits.dm
- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/core/debugger.dm
- code/modules/integrated_electronics/core/integrated_circuit.dm
- code/modules/integrated_electronics/core/pins.dm
- code/modules/integrated_electronics/core/printer.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/manipulation.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
- code/procs/announce.dm
- config/example/config.txt
Я очень сильно расстроен.
Добавил кнопку для отключения возможности для работы интегралок и включения их обратно, так же была задействована нормальная подсистема обработки activate pinов, что вероятное всего решает проблему с тем, что не все сигналы успевают активироваться в тике (+ убивает дронов-уничтожителей)
Пофиксил возможность положить интегралку в интегралку (я надеюсь)
Исправил гостскан.
Исправил возможность пулить интегралкой интегралкой.
Починил сенсоры
Пофиксил возможный баг с ИИ.
> Окончательное решение интегрального вопроса.

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/machinery/telecomms/telecomunications.dm
- code/game/objects/items/weapons/grenades/anti_photon_grenade.dm
- code/game/turfs/simulated/wall_attacks.dm
- code/modules/admin/verbs/mapping.dm
- code/modules/atmospherics/mainspipe.dm
- code/modules/detectivework/microscope/microscope.dm
- code/modules/economy/EFTPOS.dm
- code/modules/mob/living/bot/mulebot.dm
- code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
- code/modules/overmap/ships/computers/helm.dm
- code/modules/power/cable.dm
Убираем вызовы к родителю у проков, у которых нет родителей.
> Dreamchecker: proc has no parent

- code/game/machinery/embedded_controller/airlock_controllers.dm
- code/game/machinery/embedded_controller/airlock_docking_controller.dm
- code/game/machinery/embedded_controller/airlock_docking_controller_multi.dm
- code/game/machinery/embedded_controller/simple_docking_controller.dm
- code/game/machinery/machinery.dm
- code/modules/atmospherics/atmospherics.dm
- code/modules/atmospherics/components/tvalve.dm
- code/modules/atmospherics/components/valve.dm
- code/modules/client/preference_setup/laws/laws_pref.dm
- code/modules/hydroponics/spreading/spreading.dm
- code/modules/hydroponics/spreading/spreading_growth.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/nano/nanoexternal.dm
- code/modules/power/gravitygenerator.dm
- code/modules/surgery/organs_internal.dm
- code/modules/wireless/interfaces.dm
- code/modules/xgm/xgm_gas_mixture.dm
- code/procs/AStar.dm
> Dreamchecker: undefined types

- code/controllers/subsystems/event.dm
- code/datums/category.dm
- code/modules/admin/verbs/diagnostics.dm
- code/modules/music_player/_music_tape.dm
- code/modules/paperwork/photography.dm
> Dreamchecker: undefined field

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/machinery/computer/atmos_alert.dm
- code/game/machinery/computer/station_alert.dm
- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/game/machinery/doors/windowdoor.dm
- code/modules/paperwork/faxmachine.dm
- code/modules/security levels/keycard authentication.dm
> Dreamchecker: failed to resolve path

- code/game/verbs/ooc.dm
1)Звук теперь выключается.
Просто знайте я это заметил и починил, спасибо @HonkyDonky
> Stop all sounds fix

- code/modules/virus2/effects/mild.dm
ало [я это же уже фиксил](https://github.com/ChaoticOnyx/OnyxBay/pull/4313/files) вы как умудрились это проебать
> убираем eternal ожидание мобконтроллера от соплей а.к.а. удоляем лаги

- code/modules/mob/grab/normal/grab_normal.dm
Ой щас бы грабы ещё сильнее не забаговывать
> Removes code unreachablenessity in grab_normal.dm

- code/game/machinery/machinery.dm
Хз фиксит ли сам кокретный краш, но вот ЭТО в коде - непорядок.
Некоторые `beepsounds` используют листы, а если скормить плейсаунду лист без пика - произойдёт прикол.
> pick(beepsounds)

- code/__defines/items_clothing.dm
- code/_helpers/global_lists.dm
- code/modules/mob/living/carbon/human/update_icons.dm
> Removes hidden unfix

- code/controllers/subsystems/event.dm
- code/game/objects/items/devices/suit_sensor_jammer.dm
- code/modules/multiz/structures.dm
> Dreamchecker: misc

- code/_helpers/text.dm
> Фикс текста флавора при экзамайне

- code/game/machinery/newscaster.dm
1)Поле для ввода новости нормального размера.
2)ББ коды впилены
(на скрине показано что sign не работает ибо и не должен)
close #4819
> Newscaster remove absence of BB code

- .editorconfig
Теперь ньюлайны будут добавляться сами...
> Editorconfig update

- code/game/machinery/status_display.dm
> Small Fonts

- code/datums/outfits/jobs/science.dm
Что добавлено:
- Робототехник появляется в одежде своей профессии. 
close #4577
> Roboticist outfit pack fix

- code/datums/outfits/spec_op.dm
- code/game/mecha/equipment/weapons/weapons.dm
- code/game/objects/structures/railing.dm
- code/modules/mob/living/carbon/alien/diona/diona_attacks.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/simple_animal/hostile/voxslug.dm
- code/modules/organs/external/head.dm
- code/modules/organs/external/standard.dm
- code/modules/overmap/exoplanets/grass.dm
- code/modules/paperwork/complaint.dm
- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/animate.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/spells/aoe_turf/drain_blood.dm
- code/modules/spells/spell_projectile.dm
> Dreamchecker: missing keyword args

- code/datums/outfits/jobs/civilian.dm
- Бармен снова спавнится с бронежилетом, как раньше;
> Removes bartender's lack of armor

- code/modules/organs/external/head.dm
_На жопе у себя ඞ накарябай, блять._
> Removes absence of forehead-writing logging

- code/datums/outfits/jobs/science.dm
- code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Что сделано:
- В шкафчике директора исследований теперь появляется полный комплект био-скафандра, удалена экипировка ученого, которая появлялась в шкафу из-за копирования кода.
> Rd outfit pack fix

- code/modules/mob/living/silicon/silicon.dm
Заебало
Лаги вызывались из-за ахуевшего количества вызовов to_chat() у клиента, так что я всё свёл в один вызов
fix #4657
> Фикс лагов чатика от тревог у синтетиков

- code/__defines/lighting.dm
- code/game/area/areas.dm
- code/modules/events/radiation_storm.dm
- code/modules/power/lighting.dm
Ивент с радиационным штормом теперь окрашивает главные коридоры станции в зелёный цвет.
**Зачем?**
Чтобы проще было заметить сам ивент.  Чтобы в медбее было меньше трупов. 
<details>
<summary>Картинка</summary>
</details>
> Освещение во время радшторма

- code/game/gamemodes/game_mode.dm
- code/modules/client/preference_setup/antagonism/01_candidacy.dm
- code/modules/mob/living/silicon/pai/recruit.dm
- Преференсы на антагов теперь по умолчанию выставляются на "Never", а не на "Low". 
Сокращаем количество "adminhelp админ убири рольку плез!!".
Скорее всего, после накатывания всем придётся обновлять преференсы вручную.
> Removes default "low" antag prefs

- code/modules/organs/external/_external.dm
- code/modules/recycling/disposal.dm
- Гиббающиеся от атмоса люди больше не должны замораживать мобконтроллер. Наверное;
- Автоматическое смывание мусорок больше не замораживает машинериконтроллер;
> Removes possible sleep() from humans' processing

- SpacemanDMM.toml
- code/modules/admin/admin_memo.dm
- code/modules/admin/topic.dm
- code/modules/donations/donator.dm
- code/modules/mob/living/silicon/custom_sprites.dm
- code/modules/mob/living/simple_animal/parrot.dm
- code/modules/nano/interaction/default.dm
- code/modules/storyteller/storyteller_metric.dm
- code/modules/storyteller/storyteller_trigger.dm
> Dreamcheker options

- code/_helpers/areas.dm
- code/_helpers/game.dm
- code/modules/mob/living/bot/bot.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/living/simple_animal/friendly/corgi.dm
- code/modules/organs/external/_external_damage.dm
- code/modules/organs/external/_external_icons.dm
- Чистим всякое говно во славу перформанса;
-10% от нагрузки на /human/Life()
> Removes lack of performance

- code/game/objects/explosion.dm
- code/modules/admin/admin.dm
- code/modules/admin/verbs/pray.dm
- code/modules/maps/ruins.dm
- code/modules/modular_computers/file_system/programs/command/comm.dm
> Dreamchecker: undefined var: "src"

- code/modules/onyxchat/browserassets/css/browserOutput.css
- code/modules/onyxchat/browserassets/css/browserOutput_marines.css
- code/modules/onyxchat/browserassets/css/browserOutput_white.css
Отформатировал файлы, убрал переопределение шрифтов. Теперь ВЕСЬ текст в чате будет одного шрифта.
> Chat fonts

- code/modules/client/preference_setup/antagonism/02_setup.dm
- code/modules/client/preferences.dm
> Preferences html fix

- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/subtypes/access.dm
- code/modules/integrated_electronics/subtypes/lists.dm
- code/modules/integrated_electronics/subtypes/text.dm
Позволяет игроку скопировать интегралку, наконец-то.
> tweak(assembly) fix ghost scan

- code/controllers/subsystems/processing/mobs.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/mob/observer/virtual/base.dm
- Убрана двойная логика проверки среды у симпл энималов.
- Мобы на Z уровнях где нет игроков - не обрабатываются
> Mobs optimization

- code/modules/admin/topic.dm
- code/modules/admin/verbs/individual_logging.dm
Пофиксил отображение индивидуальных логов.
Из-за моей ошибки они отправлялись игроку, а не админу.
> Фикс индивидуальных логов

- code/modules/modular_computers/file_system/crew_record.dm
- code/modules/modular_computers/file_system/manifest.dm
- code/modules/modular_computers/file_system/programs/generic/records.dm
Починил отображение в манифесте в случае, если department_flag имеет более двух флагов в описание.
В программу рекордов добавлен список флагов.
<details>
```yml
🆑
tweak: Исправлена ошибка отображения в манифесте в случае, если department_flag имеет более двух флагов в описание.
/🆑
```
</details>
> Manifest fix

- html/changelog.html
Насильное обновление ченжлога, часть 2.
> Removes absence of changelog.html

- code/modules/spells/racial_wizard.dm
- code/modules/spells/targeted/equip/dyrnwyn.dm
- code/modules/spells/targeted/equip/holy_relic.dm
- code/modules/spells/targeted/equip/seed.dm
- code/modules/spells/targeted/equip/shield.dm
- code/modules/spells/targeted/ethereal_jaunt.dm
- code/modules/spells/targeted/shapeshift.dm
- code/modules/spells/targeted/shift.dm
<details>
```yml
🆑
BugFix: Пофикшены сломанные заклинания мага.
/🆑
```
</details>
> fix spells

- code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
Фикс пофикшенного фикса.
<details>
```yml
🆑
tweak: Исправлена возможность положить сервер word'ом.
/🆑
```
</details>
> tweak(word) fix fields bug

- code/_onclick/ai.dm
- code/_onclick/click.dm
- code/_onclick/cyborg.dm
- code/_onclick/rig.dm
- code/modules/client/preference_setup/global/preferences.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/robot/robot.dm
Новый хоткей: Shift-MiddleMouseClick указывать на что-то.
Также добавлена возможность указывать боргам и голограмме ИИ.
<details>
```yml
🆑
rscadd: Новый хоткей: Shift-MiddleMouseClick указывать на что-то.
rscadd: Также добавлена возможность указывать боргам и голограмме ИИ.
/🆑
```
</details>
> Point to hotkey

- code/game/objects/items.dm
```yml
🆑
tweak: Отключена возможность блокировать выстрелы лёжа и/или находясь в стане.
/🆑
```
> 絶対的な防御を取り除く

- code/__defines/_planes+layers.dm
- code/_helpers/game.dm
- code/_helpers/icons.dm
- code/_helpers/json.dm
- code/datums/helper_datums/construction_datum.dm
- code/datums/helper_datums/events.dm
- code/datums/helper_datums/global_iterator.dm
- code/datums/helper_datums/topic_input.dm
> Рефакторинг Part II

- code/modules/economy/ATM.dm
- code/modules/economy/cash.dm
- code/modules/merchant/merchant_programs.dm
- code/modules/projectiles/guns/launcher/money_cannon.dm
Ситуация такая же как и с лутом ховерхеада.
<details>
```yml
🆑
bugfix: Возможность создавать огромное количество денег теперь утрачена.
/🆑
```
</details>
> fix(money) money can be used after "deletion"

- .github/workflows/check_changelog.yml
Добавляет авто-плашкователя ПРов (для чейнджлогов). Ждём Эпикуса.
> 🤖 changelogical

- .vscode/launch.json
- nano/To BYOND Cache.bat
- nano/Watch.ps1
Скрипт для обновления nano ресурсов в кэш (аналог tgui watch)
Для людей на других ОС нужно уточнить путь до кэша БЙОНДА
> Nano Watch

- code/controllers/subsystems/supply.dm
- code/datums/supplypacks/miscellaneous.dm
По геймдизайн запросу.
x2 цена к заказу ТК.
Добавлена функция уведомления экипажа о покупке нелегальных предметов (30% к срабатыванию за каждый пункт контрабанды в заказе), также 5% шанс на ложное срабатывание.
```yml
🆑
rscadd: Добавлено уведомление о покупке нелегальных предметов в карго - каждый нелегальный пункт в заказе увеличивает шанс на срабатывания на 30%.
tweak: Увеличены цены на покупку телекристаллов в карго.
/🆑
```
> feat(cargo) announce when buy illegal stuff

- code/game/antagonist/station/rogue_ai.dm
- code/game/gamemodes/changeling/changeling_powers.dm
- code/modules/flufftext/Dreaming.dm
- code/modules/mob/living/carbon/human/species/station/station.dm
- code/modules/organs/external/diona.dm
- code/modules/shuttles/shuttle.dm
- code/unit_tests/equipment_tests.dm
> Dreamchecker: returning a value has no effect

- code/modules/admin/banjob_iaa.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
- code/modules/integrated_electronics/subtypes/text.dm
> tweak(something) runtimes fix

- code/game/gamemodes/traitor/fixer.dm
Забыл про базовый тип у контрактов.
> Фикс контрактов

- .github/workflows/check_changelog.yml
Должно быть намного меньше лишних проверок
> Action Tweak

- code/modules/projectiles/projectile/special.dm
- Исправлено отсутствие спрайта у тяжёлого лазерного болта;
> Removes absence of heavy laser bolt icon

- code/__defines/inventory_sizes.dm
> Removes storage-breaking absence of brackets

- code/modules/admin/admin_ranks.dm
- code/modules/admin/permissionverbs/permissionedit.dm
- code/modules/donations/donations.dm
rank и change - зарезервированные слова в MySQL, поэтому их нужно экранировать косыми кавычками
> fix(sql): quote reserved words

- code/modules/events/event_container.dm
Слегка откручиваем шанс на ивент со спавном грудоломов.
> Removes one third of xenomorph infestation event weight

- code/datums/uplink/devices and tools.dm
- code/game/gamemodes/traitor/contracts.dm
Решил попробовать оставить авторизацию через аплинк.
Пофиксил рантайм.
> fix(contracts) fix runtime

- code/modules/spells/targeted/mind_control.dm
```
Runtime in mind_control.dm, line 103: Cannot execute null.has reagent().
Skipped 1131 runtimes in mind_control.dm,103.
```
> Фикс рантайма 

- code/modules/spells/general/area_teleport.dm
- code/modules/spells/spell_code.dm
Маги <del>заново</del> открыли магию телепортации
<details>
```yml
🆑 Lovla aka Zert0X
bugfix: Исправлено нерабочее заклинание телепортации у мага.
/🆑
```
</details>
> fix(wizard) Teleportation spell

- code/game/gamemodes/traitor/contracts.dm
> fix(contracts) check params fix

- code/game/machinery/doors/brigdoors.dm
<details>
```yml
🆑
tweak: Более читаемые шрифты у таймеров в бриге.
/🆑
```
</details>
> fix brig fonts

- tools/CI/CodeStyleRules.json
- Добавил больше исключении в проверку на var/
- Улучшил регулярку на спаны.
> CodeStyle Tweak

- html/browser/assembly_ui.css
> Фикс отступов в интерфейсе интегралок

- code/modules/onyxchat/browserassets/js/browserOutput.js
> Чатлоговское

- code/game/machinery/autolathe.dm
<details>
```yml
🆑
BugFix: Добавлено окно хакинга автолата. Открывается в отдельном окне при открытии автолата с открытой панелью.
/🆑
```
</details>
> Autolathe Hacking Fix

- code/modules/spells/general/area_teleport.dm
- code/modules/spells/general/mark_recall.dm
- code/modules/spells/spell_code.dm
- code/modules/spells/targeted/ethereal_jaunt.dm
- code/modules/spells/targeted/projectile/fireball.dm
- code/modules/spells/targeted/projectile/projectile.dm
Убрал проверку на таргет спелам которым она не нужна. Из-за этой проверки эти спелы работали раз в тысячу лет и то на рандом.
<details>
```yml
🆑
bugfix: Починил каст у некоторых спеллов мага
/🆑
```
</details>
> Fix some magic bugs

- code/modules/mob/mob.dm
- html/changelog.css
Чуток потрогал чейнджлог, размеры шрифтов теперь везде должны быть нормальными.
> Чейнджлог твикс

- html/changelog.css
> Changelog Missing Fonts

- code/modules/client/preferences.dm
- code/modules/mob/new_player/login.dm
- Перенёс открытие панели в соответствующие место.
Продолжаем танцевать с бубном.
> Uncurse Prefs

- code/modules/client/client_procs.dm
- code/modules/mob/new_player/login.dm
Перенёс сверку и открытие чейнджлога в соответствующее место
> Чейнджлогийное

- nano/templates/hire_tool.tmpl
close #5423 
<details>
```yml
🆑 Pl3aseJust3ndMyPain
bugfix: Исправлена грамматическая ошибка в программе вакансий.
/🆑
```
</details>
> Okey > Okay

- code/controllers/subsystems/initialization/character_setup.dm
- code/modules/admin/admin_verbs.dm
- code/modules/client/client_procs.dm
- code/modules/client/preference_setup/global/05_settings.dm
- code/modules/client/preferences.dm
Переместил загрузку префов в запуск из клиентского прока, что в теории должно убрать частые рантаймы в префах из-за ливнувшего клиента.
> Preferences Hell

- code/controllers/subsystems/initialization/character_setup.dm
> Проклятье преференсов

- code/_macros.dm
Делает макрос SPAN константным
> Константные спаны

- code/modules/tgui_panel/external.dm
- code/modules/tgui_panel/tgui_panel.dm
Поменял бессмысленное сообщение с нерабочей ссылкой.
Добавил проверку на инициализированность чата - просто избавляет от лишних рантаймов.
> Небольшие фиксы чата.

- baystation12.dme
- code/game/antagonist/station/thrall.dm
- code/game/antagonist/station/vampire.dm
- code/game/gamemodes/cult/ritual.dm
- code/game/gamemodes/objective.dm
- code/game/gamemodes/vampire/vampire_objectives.dm
1. Вампиру теперь выпадают задания;
2. Добавлены два новых задания:
2.1 Вампиризировать человека;
2.2 Создать N-e число гулей на станции;
3. Вампиру и было больно от святой воды;
<details>
```yml
🆑 Lovla aka Zert0X
rscadd: Вампиру теперь выпадают задания;
rscadd: Добавлено пару заданий специально для вампиров;
/🆑
```
</details>
close #5460
> Add objectives to vampire

- code/game/gamemodes/vampire/modular_vampire.dm
- code/game/gamemodes/vampire/vampire_powers.dm
1. Блад хил теперь лечит вирусы
<details>
```yml
🆑
tweak: Blood Heal вампиров теперь лечит вирусы.
/🆑
```
</details>
close #5463
> Medical improvments for vampires

- code/modules/client/preference_setup/global/03_pai.dm
<details>
```yml
🆑
bugfix: Исправлено сохранение и загрузка настроек ПИИ.
/🆑
```
</details>
fixes #5578
> Преференсное ПИИ

- code/game/verbs/ooc.dm
- code/modules/client/client_procs.dm
- code/modules/client/preference_setup/global/preferences.dm
<details>
```yml
🆑
bugfix: Fix Hotkeys теперь работает.
/🆑
```
</details>
> Fix Fix Hotkeys

- code/datums/uplink/categories/devices and tools.dm
```yml
🆑
bugfix: Исправлена невозможность покупки паверсинка и флешдарка в аплинке.
/🆑
```
> Removes inability to buy flashdarks

- code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
```yml
🆑
bugfix: Ксеноморфы больше не могут использовать плевки и кислоту из труб.
/🆑
```
> Removes xenospits going through vents

- code/controllers/subsystems/virus.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/viruses.dm
- code/modules/virus2/centrifuge.dm
- code/modules/virus2/disease2.dm
- code/modules/virus2/effect.dm
- code/modules/virus2/effects/common.dm
- code/modules/virus2/effects/mutation.dm
- code/modules/virus2/helpers.dm
Исправлена ошибка, из-за которой вирус не передавался дыхательным путем между людьми.
Two Percent Syndrome больше не гибает людей. Впрочем, мартышек все равно гибает, так что берегите своего Пун-Пуна и опасайтесь повторного заражения после становления обезьянкой.
При мутациях у новых эффектов теперь корректная стадия.
Исправлена ошибка, из-за которой мутировавший внутри человека вирус был неизлечим.
close #4637
close #5714
close #4641
<details>
```yml
🆑
bugfix: Исправлена ошибка, из-за которой вирус не передавался дыхательным путем между людьми.
bugfix: Two Percent Syndrome больше не гибает людей.
bugfix: При мутациях у новых эффектов теперь корректная стадия.
bugfix: Исправлена ошибка, из-за которой мутировавший внутри человека вирус был неизлечим.
/🆑
``` …
> Пачка вирусных пофиксов

- code/modules/mob/living/carbon/xenobiological/powers.dm
- code/modules/organs/blood.dm
- code/modules/projectiles/projectile/beams.dm
fixes #5800 
fixes #5799 
fixes #5797
> Сом Фиксес

- code/modules/organs/external/head.dm
```yml
🆑
bugfix: Исправлена опечатка в названии сонной артерии: "cartoid artery" -> "carotid artery".
/🆑
```
> Removes the most malicious medical bug

- code/modules/virus2/helpers.dm
close #5796
Добавлена проверка на null
> fix Runtime in helpers.dm,92: Cannot read null.name

- code/game/machinery/vending.dm
```
Runtime in vending.dm,188: Cannot execute null.GetIdCard().
```
> Фикс рантайма вендомата

- code/modules/modular_computers/computers/subtypes/preset_console.dm
close #5817 
```yml
🆑 Artemonim
tweak: В консолях инженерного отдела установлен NanoWord
/🆑
```
> NanoWord предустановлен в консоли инженерки

- code/game/atoms_movable.dm
- code/modules/admin/IsBanned.dm
- code/modules/mob/living/carbon/carbon.dm
Баны не тестировал, остальное тестировал.
<details>
```yml
🆑
tweak: Из вентов нельзя больше бросать предметы.
tweak: Теперь при заходе с баном, помимо причины, выдается ссылка на то, куда писать, чтобы подать апелляцию.
/🆑
```
</details>
close #5403 , close #3613
> Немного указов

- code/modules/client/preference_setup/loadout/lists/xenowear.dm
- maps/exodus/Loadout/loadout_xeno.dm
Удалил одежду IPC, которую невозможно надеть
Удалил одежду, которую мог одеть только IPC, расы которого нет на сервере, следовательно, эту одежду невозможно взять. Удалил и сам файл, и из Loadout меню
<details>
```yml
🆑
rscdel: Удалена одежда IPC
/🆑
```
</details>
close #5218
> Удаление одежды, которую невозможно надеть

- tgui/packages/tgui/interfaces/RDConsole.tsx
fixes #5968 
<details>
```yml
🆑
bugfix: Добавлена кнопка сохранения рецептов в консоли РнД.
/🆑
```
</details>
> Add save design button

- code/controllers/configuration.dm
- code/game/antagonist/alien/borer.dm
- code/game/antagonist/alien/xenomorph.dm
- code/game/antagonist/antagonist.dm
- code/game/antagonist/blob/blob.dm
- code/game/antagonist/outsider/actors.dm
- code/game/antagonist/outsider/commando.dm
- code/game/antagonist/outsider/deathsquad.dm
- code/game/antagonist/outsider/deity.dm
- code/game/antagonist/outsider/ert.dm
- code/game/antagonist/outsider/ninja.dm
- code/game/antagonist/outsider/raider.dm
- code/game/antagonist/outsider/syndicate.dm
- code/game/antagonist/outsider/wizard.dm
- code/game/antagonist/station/changeling.dm
- code/game/antagonist/station/cult_god.dm
- code/game/antagonist/station/cultist.dm
- code/game/antagonist/station/loyalist.dm
- code/game/antagonist/station/meme.dm
- code/game/antagonist/station/renegade.dm
- code/game/antagonist/station/revolutionary.dm
- code/game/antagonist/station/rogue_ai.dm
- code/game/antagonist/station/thrall.dm
- code/game/antagonist/station/traitor.dm
- code/game/antagonist/station/vampire.dm
- config/example/config.txt
close #5884
в следующей серии: мин эйдж реквайремент из конфига для джобок
алсо потёр лишний хардкодед вар для эйдж реквайремента
повесьте кл не нужен у меня нет прав
> add(antags): min_age_req from cfg

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/modular_computers/file_system/programs/command/comm.dm
Теперь поля для ввода анонсов и сообщений в ЦК стали большими
<details>
```yml
🆑
tweak: Теперь поля для ввода анонсов и сообщений в ЦК стали большими.
/🆑
```
</details>
close #5925
> tweak(announce): Biggest input window

- code/game/gamemodes/changeling/helpcode.dm
- code/game/gamemodes/changeling/powers/division.dm
Ебанный рот этого вашего дедфиле
<details>
```yml
🆑
bugfix: Теперь не накладываются задания генок при выпивание генореагента.
bugfix: Теперь генокрады, которые выданы через генореагент и дивизион отображаются в итоговом списке антагонистов.
/🆑
```
</details>
close #5378
> Исправление генокрадовое

- code/datums/outfits/jobs/civilian.dm
- code/game/objects/items/weapons/storage/belt.dm
- code/game/objects/structures/crates_lockers/closets/job_closets.dm
```
/obj/item/weapon/reagent_containers/spray/cleaner //Добавление возможности держать в поясе уборщика space cleaner
/obj/item/weapon/storage/belt/janitor //Появление в шкафчике уборщика пояса
```
<details>
```yml
🆑
rscadd: Добавлен пояс для уборщика, находится в шкафчике уборщика.
/🆑
```
</details>
close #5874
> Пояс для уборщика и space cleaner

- maps/exodus/exodus_areas.dm
Исправлен рантайм `Runtime in unsorted.dm,1084: Unknown sound: science`
> Fix ambient name

- code/game/objects/structures/inflatable.dm
Одна ошибка и ты ошибся.
<details>
```yml
🆑
bugfix: Киборги больше не могут удаленно взаимодействовать с надувными дверями.
/🆑
```
</details>
> Киборги больше не могут удаленно взаимодействовать с надувными дверями

- code/_helpers/global_access.dm
- code/controllers/subsystems/virus.dm
- code/modules/admin/secrets/admin_secrets/toggle_viruses.dm
- code/modules/mob/living/carbon/viruses.dm
- code/modules/virus2/disease2.dm
- [x ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
> Ренейм системы вирусов

- code/game/gamemodes/changeling/powers/transform.dm
- code/modules/mob/living/carbon/human/human.dm
При трансформе в существо другого размера теперь все вещи сбрасываются на пол, так же сбрасывается нижнее белье.
fix #6066
fix #6203
<details>
```yml
🆑Oubi
bugfix: Пофикшен сброс нижнего белья при превращении в обезьяну за генокрада. Viva la monkey!
/🆑
```
</details>
> fix(changeling): transform wear drop fix

- code/game/gamemodes/traitor/fixer.dm
Ай, больно в ноге.
<details>
```yml
🆑
tweak: Теперь в контрактах не будет пустых контрактов.
/🆑
```
</details>
> tweak(contracts) contract now can't be empty

- code/controllers/subsystems/tgui.dm
- code/game/machinery/adv_med.dm
- code/game/machinery/autolathe.dm
- code/game/machinery/computer/arcade.dm
- code/game/machinery/doors/airlock_electronics.dm
- code/game/machinery/doors/brigdoors.dm
- code/game/machinery/resleever.dm
- code/game/machinery/vending.dm
- code/game/mecha/mech_fabricator.dm
- code/game/objects/items/devices/floor_painter.dm
- code/game/objects/items/devices/suit_sensor_jammer.dm
- code/modules/research/rdconsole.dm
- code/modules/tgui/external.dm
- code/modules/tgui/tgui.dm
Порт с beeстанции. Теперь уи изначально не автообновляются каждый тик.  Для необходимости обновить уи или включения автообновления используется отдельный прок.
> Порт оптимизации тгуи

- code/modules/shuttles/shuttle.dm
Как рантайм не нужен, игра из-за отсутствия шаттла не ломается, особенно учитывая что на картах не может быть ВСЕХ шаттлов.
> Убираем рантайм с шаттлом

- code/_helpers/time.dm
Теперь отсчёт начинается после первого срабатывания. ¯\\\_(ツ)_/¯
> Фикс поведения THROTTLE

- code/game/machinery/cell_charger.dm
Добавлена проверка питания при зарядке батареи.
close #3724
<details>
```yml
🆑
bugfix: Больше зарядник батарей не будет их заряжать при отключившемся питании.
/🆑
```
</details>
> fix(cell_charger): added power check during cell charging

- code/_helpers/time.dm
Теперь точно всё работает как надо
> Тротл опять

- code/game/gamemodes/traitor/fixer.dm
Я дурачек.
close #6330
<details>
```yml
🆑
bugfix: Контракты теперь генерируется. Снова.
/🆑
```
</details>
> fix(contracts) contracts now can be spawn, hooray!

- maps/example/example-1.dmm
- maps/example/example-2.dmm
- maps/example/example-3.dmm
Со старта теперь включен свет.
На первом уровне появилась гравитация.
На втором уровне добавил админскую id карту.
На третьем уровне добавлена маленькая комната без гравитации.
Стены теперь укрепленные и двойные.
> fix(map): Example fixes

- code/modules/spells/aoe_turf/blink.dm
- code/modules/spells/aoe_turf/conjure/druidic_spells.dm
- code/modules/spells/aoe_turf/conjure/faithful_hound.dm
- code/modules/spells/aoe_turf/conjure/forcewall.dm
- code/modules/spells/aoe_turf/knock.dm
- code/modules/spells/aoe_turf/summons.dm
- code/modules/spells/general/area_teleport.dm
- code/modules/spells/general/mark_recall.dm
- code/modules/spells/general/radiant_aura.dm
- code/modules/spells/no_clothes.dm
- code/modules/spells/targeted/ethereal_jaunt.dm
- code/modules/spells/targeted/mind_control.dm
- code/modules/spells/targeted/projectile/magic_missile.dm
- code/modules/spells/targeted/shapeshift.dm
Поменял множество мелких багов мага, которые лежали в билде лет так 6. По одиночке они больших проблем не несут, но вместе, они знатно ломают баланс. Много скиллов при улучшении жрали лишние очки и не давали ничего, подрезал пустые уровни и добавил кулдауны в некоторые скиллы для предотвращения имбы с кулдауном в 0.
<details>
```yml
🆑
bugfix: Починил различные баги мага связанные с кулдауном скиллов. Раньше очки можно было потратить впустую.
/🆑
```
</details>
> fix(cooldowns): fixes wizard cooldowns

- code/modules/mob/living/silicon/robot/drone/drone_items.dm
- code/modules/projectiles/gun.dm
Ай мля.
<details>
```yml
🆑
tweak: Теперь игрушечным пистолетом нельзя убить.
tweak: Если киборг попытается вставить компонент в интегралку, и у него не получится, то компонент упадет на пол.
/🆑
```
</details>
> tweak(bugs) delete bugs

- code/game/machinery/spaceheater.dm
- code/modules/atmospherics/components/binary_devices/passive_gate.dm
- code/modules/atmospherics/components/unary/cold_sink.dm
- code/modules/atmospherics/components/unary/heat_source.dm
- code/modules/modular_computers/file_system/programs/engineering/rcon_console.dm
да, газ кулер теперь плавный.
как вариант ещё есть добавить обновление интерфейса всегда когда приходит топик, но это может слегка сказаться на производительности -> нужны рецензии.
а пока наслаждаемся интерактивностью 
close #4109
<details>
```yml
🆑kcalbCube
bugfix: теперь некоторые наноуи интерфейсы стали отзывчивыми
/🆑
```
</details>
> добавляем обновление в топики нескольких наноинтерфейсов

- code/game/machinery/kitchen/gibber.dm
close #6378 
<details>
```yml
🆑
bugfix: исправляет зависание гиббера на кухне при засовывании синта, теперь синт выбрасывает от 33 до 55 листов стали при мясорубывании
/🆑
```
</details>
> gibber fix

- code/modules/mob/living/silicon/custom_sprites.dm
Я забыл проверку на существования файла, теперь она есть.
> fix(custom sprite) fix runtime in 9 line

- code/modules/spells/spellbook.dm
После покупки артефакта можно было ресетнуть книгу и купить артефакты из разных книг. Побыстрее это вмерджить нужно.
> fix(wizard): artifact reset

- code/datums/movement/mob.dm
- code/modules/vehicles/cargo_train.dm
- code/modules/vehicles/train.dm
- code/modules/vehicles/vehicle.dm
Если вдруг вырезать не будем - небольшой фикс карговозика:
- Используются мув хандлеры.
- По лестницам спускается/поднимается (правда при подъёме персонаж якобы остаётся на лестнице но при следующем передвижении появляется на карговозике)
> Карговозика фикс

- .github/workflows/additional_checks.yml
Завез проверку на вар в аргументах в экшен, возможны подводные эджкейсы.
> Чек на вар в аргументах 

- code/modules/mob/mob.dm
Добавляет кнопочку фоллоу по эмоутам для призраков.
close #6319
<details>
```yml
🆑
tweak: Добавлен гостам фоллоу по эмоутам.
/🆑
```
</details>
> Возможность гостам делать фоллоу к людям по эмоуту.

- code/modules/tgui_panel/external.dm
> tweak(fix_chat): replace tgui alert with byond alert

- code/game/gamemodes/nuclear/nuclear.dm
- code/game/machinery/nuclear_bomb.dm
close #3214
<details>
```yml
🆑
bugfix: Теперь пинпойнтер может искать нюкодиск даже если его смыли в мусорку.
/🆑
```
</details>
> fix nukedisk spawn

- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- code/modules/tables/flipping.dm
close #3474
<details>
```yml
🆑
bugfix: Дионы и им подобные не могут теперь крутить стулья и переворачивать столы из труб вентиляции.
/🆑
```
</details>
> you can't interract with sturctures

- code/modules/ventcrawl/ventcrawl.dm
close #2164
<details>
```yml
🆑
bugfix: Спайдерботы снова могут лазить по вентиляции (без вещей).
/🆑
```
</details>
> spiderbot vent fix

- code/modules/research/rdconsole.dm
close: #5541
<details>
```yml
🆑
bugfix: Теперь не нужно пересобирать всё РнД если открутил консоль.
/🆑
```
</details>
> rndconsole sync fix

- code/modules/mob/holder.dm
close: #5051
<details>
```yml
🆑
bugfix: Теперь птицы не воскрешаются после взятия их на руки.
/🆑
```
</details>
> теперь дохлый

- code/modules/nano/nanoui.dm
Передаю привет всем аппрувающим нетестированный ПР #6464.
<details>
```yml
🆑
bugfix: Добавлена карта Фронтира в интерфейс консолей (в этот раз на самом деле)
/🆑
```
</details>
> Фикс карты Фронтира в уях

- code/modules/modular_computers/computers/subtypes/preset_console.dm
Хех привет я однострочный пр да
Добавил в медицинский пресет консолей медицинские рекордсы, так как это забыл сделать тот, кто эти рекордсы запилил.
см также #4690
<details>
```yml
🆑
tweak: Программа для работы с медицинскими записями предустановлена на медицинские консоли
/🆑
```
</details>
>  tweak(console): pre-install medical records on medical consoles

- code/modules/projectiles/guns/energy/temperature.dm
- code/modules/projectiles/projectile/special.dm
close: #1479
<details>
```yml
🆑
bugfix: Температурная пушка снова работает.
/🆑
```
</details>
> temp gun fix

- code/game/mecha/mecha.dm
> Mech runtime fix

- code/modules/surgery/limb_reattach.dm
> fix(runtime): add missing type guard

- code/modules/research/rdconsole.dm
> fix(runtime): fix rnd console unlink runtime

- code/modules/surgery/organs_internal.dm
> fix(runtime): fix runtime in internal organs surgery

- code/modules/spells/hand/blood_shards.dm
- code/modules/spells/hand/hand.dm
> Фикс блудшардов

- code/_onclick/hud/skybox.dm
Скайбокс теперь правильно перемещается на любых картах
fix #4894
<details>
```yml
🆑
bugfix: Исправлены проблемы со смещением скайбокса
/🆑
```
</details>
> Адаптивный скайбокс

- tools/ChangelogGenerator/ClCheck.csx
- tools/ChangelogGenerator/Models.csx
Теперь если нет чейнджлога в пре - будет автоматически вешаться плашка "CL не требуется".
> tweak(ci): some ci tweaks

- code/game/gamemodes/changeling/powers/absorb.dm
~~Джва~~ Год был баг, а фиксится за 5 минут, и так весь билд.
close #2206
<details>
```yml
🆑
bugfix: Теперь генокрады не смогут получать очки поедая свое старое тело.
/🆑
```
</details>
> tweak(changeling) fix absorbing same dna (monkey abuse)

- code/datums/movement/multiz.dm
- code/modules/vehicles/vehicle.dm
<details>
```yml
🆑
tweak: Карговозики и весь транспорт в целом теперь не может передвигаться по лестницам.
/🆑
```
</details>
> tweak(vehicle): restrict stairs riding

- code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
<details>
```yml
🆑
tweak: Инвалидные коляски больше не могут передвигаться по лестницам.
/🆑
```
</details>
> tweak(wheelchair): restrict stairs riding

- code/game/gamemodes/cult/narsie.dm
- code/game/objects/structures/flora.dm
- code/modules/power/singularity/act.dm
- code/modules/power/singularity/singularity.dm
Стало довольно грустно наблюдать за тем, как сначала сингулярность пожирает бедного космонавтика, а затем отпускает его, убегая на гетто-уровень. Мне показалось, что стоит решить эту проблему. 
Добавлять плашку 'геймдизайн' я не решился, ибо, как по мне, это недочёт который давно стоило бы поправить. 
Исходя из названия можно понять, что теперь сингулярность не будет прыгать туда-сюда как зайчик, а просто-напросто занимать всевозможные Z-уровни к которым она подсоединена. 
<h2>Реализация</h2>
Ну тут всё относительно легко. Мы просто создаем фиктивную сингулярность, которая ходит по стопам родителей и точно так же процессится от неё. 
<h2>Проблемы</h2>
- По неизвестным мне причинам некоторые объекты не желают удаляться попадая в горизонт событий сингулярности. Эти предметы начинают …
> Сингулярность: многоуровневость 

- code/modules/mob/grab/grab_object.dm
Блять, бейцы опять насрали в кашу.
close #6588
<details>
```yml
🆑
bugfix: Теперь нельзя сразу несколько людям грабать одного и тоже человека.
/🆑
```
</details>
> fix(grabs) fix server crush grabs

- code/modules/paperwork/folders.dm
close #2657 
<details>
```yml
🆑
bugfix: Теперь в папках корректно отображается русский.
/🆑
```
</details>
> fix(paperwork): now folders correctly show russian language

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
порт убив процессинга дверей, работает и хорошо, слава таймерам
> port(doors): doors works on timers, without processing
