- code/game/objects/effects/effect_system.dm
- code/game/objects/items/weapons/cigs_lighters.dm
- code/modules/detectivework/tools/rag.dm
- code/modules/reagents/Chemistry-Logging.dm
- code/modules/reagents/Chemistry-Recipes.dm
Перезалив ПРа с предыдущей репы с дополнительными фиксами для сигарет и тряпок. 
Оказалось, что сигареты тоже были сломаны и не взрывались. Сейчас их можно наполнить топливом и взорвать, правда там не будет никакого урона от самого взрыва - слишком мало реагентов, но должен быть отдельный урон по голове/руке. Это надо будет доделать в будущем.
Из предыдущего ПРа:
> Переписал логику взрывных реакций, починил логирование для реакций.
> 
> Теперь реакции вызывают реальные взрывы и могут гибнуть человека, если реакция будет внутри него. Никаких искр и странных вспышек. Также избавился от копипасты в коде взрыва: теперь потассиумный и нитроглицериновые взрывы имеют общего наследника.
> 
> Все реакции логируются в текстовые логи и логи в отдельной менюшке в педальном интерфейсе. Важные реакции …
> Explosion reactions tweak, fix for reactions logging

- code/game/supplyshuttle.dm
1. Добавлена возможность отправлять в карго-шаттле деньги на ЦК, и получать за них баллы, с коэффициентом 0.5. То есть за 1 таллер - 0.5 балла.
Обоснование:
Поломанные зоны на астероиде не дают добывать достаточно ресурсов для РнД (то есть автоматические буровые установки невозможно использовать - в земле нет ресурсов).
Баллы карго копятся очень, ОЧЕНЬ медленно.
Можно отправлять некоторые ресурсы на ЦК конечно, но только вот это просто смешно:
points_per_phoron = 5
Т.е. с полного стака форона ты получаешь 250 баллов карго.
В итоге мы имеем очень слабо юзабельный отдел.
Это может помочь несколько реанимировать финансовую систему добавлением еще одного пути сбыта денег.
> Баллы карго за талеры.

- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/stripping.dm
- code/modules/mob/living/living_defines.dm
Починил раздевание:
1. Теперь если попытаться снять несколько предметов сразу - пишется варнинг.
2. После снятия предмет больше не будет телепортироваться из рук в руки среди тех, кто снимал его.
3. Если сделать двойной граб персонажа, то можно снимать предметы сразу по несколько штук (причем держать и снимать могут разные люди, там два условия: 1. на том, с кого снимают есть двойной захват, 2. тот кто снимает не использует намерение Help).
~~Бонус: пробная локализация всех сообщений касательно одевания-раздевания. Буква Я в коде мне совсем не нравится, зато в игре зашибись выглядит.~~
Локализацию решили выпилить пока.
> Stripping fix, agressive stripping with grab

- code/game/machinery/rechargestation.dm
- code/modules/mob/living/silicon/ai/death.dm
Можно запихивать синтов и и боргов в станции зарядки перетаскиванием
При смерти ИИ привязаным боргам приходит сообщение о потери сигнала с ИИ (в чейнджлоге ошибка, там идет оповещение ИИ о смерти борга а не наоборот)
> drag n drop feature for recharge station and AI death notification for borgs

- code/modules/mob/living/simple_animal/hostile/asteroid/basilisk.dm
- code/modules/mob/living/simple_animal/hostile/asteroid/goliath.dm
- code/modules/mob/living/simple_animal/hostile/asteroid/sand_lurker.dm
- code/modules/random_map/automata/caves.dm
- html/changelog.html
Уменьшено общее количество с 250 до 200.
Процентовка видов мобов перераспределена и теперь выглядит более разумно. Более слабых мобов стало относительно больше, а более опасных относительно меньше.
Некоторые мобы так или иначе понерфлены.
Самый опасный моб, который теперь встречается гораздо реже, стал непредсказуемее, но потерял часть здоровья.
> Ребаланс фауны

- code/datums/supplypacks/hydroponics.dm
#334 
Стоимость горшков с цветами поднята до 6, чтобы убрать дюп. Даже если проставлять печать, выходит возврат в 6 очков и итоговая прибыль 0.
> Фикс экономики карго

- code/controllers/configuration.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- config/example/config.txt
_This is blind port of topic limiter from /tg/_
It appiles to all non-admins. Rate limit is configurable, it defaults to 10 in any second and 100 in any minute.
Hitting the minute limit causes a notification to go to admins (once per minute) so that they are aware of the things going on.
The user will be notified if a topic is ignored so they know whats going on. If they trigger a notification to admins they are told about this as well.
> T15: Blindly ported topic limiter

- code/game/objects/items/paintkit.dm
- code/modules/mining/mine_turfs.dm
- code/modules/power/smes_construction.dm
Профайлер говорит, что есть BadInitializeCalls в количестве 7 штук. Поправил инициализацию везде, кроме первого пункта.
1. /mob/new_player
2. /obj/item/device/kit/paint/ripley/random
3. /obj/machinery/power/smes/buildable/outpost_substation
4. /turf/simulated/mineral
5. /turf/simulated/floor/asteroid
6. /turf/simulated/mineral/random/high_chance
7. /turf/simulated/mineral/random
> Fixed bad initialization calls

- code/game/objects/items/toys.dm
Исправляет #577 
Вернул игрушечному арбалету спрайт. Заодно и сигнальной палочке.
> I577: Fixed toy crossbow and marshalling wand icons

- code/game/machinery/atmoalter/canister.dm
- code/modules/mob/living/silicon/robot/drone/drone_items.dm
По реквесту Легата и многочисленным просьбам игроков, забрал у ИИшника возможность взаимодействия с газовыми канистрами на станции. Борги и дроны могут подключиться к интерфейсу канистры с помощью встроенного манипулятора.
> Забираем удаленное взаимодействие с канистрами у ИИшника.

- code/controllers/subsystems/atoms.dm
- code/game/atoms.dm
- code/modules/maps/map_template.dm
Фикс для #700
Судя по всему, единственное место где дверка создаётся - функция `LateInitialize()`, но её вызов никогда не происходит при создании объекта `/obj/structure/closet/wizard`. Добавил строчку при вызове `New()` и всё работает. По-хорошему, нужно перегрузить конструктор у `/obj/structure/closet` дабы он вызывался на всех шкафах, а не только на шкафах мага.
> Фикс шкафчиков мага

- code/game/objects/objs.dm
- code/modules/recycling/sortingmachinery.dm
#742. qdel на предмете который мы выносим не работал, видимо, из-за ссылки на этот самый объект в обёрточной бумаге, из-за чего предмет с голодека не удалялся. Также, изменил проверку при открытии обёрточной бумаги - она теперь удаляется если пустая.
Ещё почему-то когда выходил с голодека - я буквально вошёл в бесконечный цикл, но это уже другая история.
> Фикс выноса вещей с голодека

- code/game/machinery/newscaster.dm
- code/modules/modular_computers/file_system/data.dm
- code/modules/modular_computers/file_system/programs/generic/file_browser.dm
- code/modules/modular_computers/file_system/programs/generic/ntnrc_client.dm
- code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
- nano/js/nano_state_manager.js
- Немного улучшил этот NanoUI, теперь он все входные данные обрабатывает регулярками (быстрее на JS вроде и не сделать) и заменяет поломанную кириллицу на UTF-8.  Для этого взял функцию rustoutf из russian.dm да вставил в самое подходящее место - nano/js/nano_state_manager.js. Так что теперь кириллица работает в любом NanoUI.
- Заметил, что NanoWord сохраняет файлы с расширением DAT, но когда пытаешься их загрузить - он ищет файлы формата TXT и соответственно ничего не находит. Пытался поменять формат сохраняемых файлов на TXT - но он упорно делал их DAT, поэтому просто поменял проверяемый формат.
-  Я пока так и не допёр как фиксить букву "я" в функциях input, самый безболезненный способ который смог придумать - использовать input_utf8, но там буква отображается как "\Я".
> Фикс кириллицы в NanoUI - теперь как родная.

- code/game/machinery/cell_charger.dm
Починил дюп батарейки зарядником.
На самом деле дюп не настоящий, а тупо одна батарейка была сразу в двух местах. Ничего особенного.
Сделал forceMove, как делается в аналогичных местах.
close #986
> fix(cell_charger): fix cell dubling on insert

- code/modules/modular_computers/file_system/crew_record.dm
Добавил автоматические оповещения в канал СБ, когда кто-то меняет статус розыска. Также создается оповещение при изменении security record. 
Сам текст Security Record выводить в голосовой канал не стал, ибо там может быть довольно объемный текст, а офицеры все равно могут его посмотреть с помощью очков.
Скрин:
close #994
> feat(crew manifest): radio announcements for security statuses changes

- code/modules/events/event_container.dm
* Понизил шанс брич-ивентов вирусологии и ксенобиологии в пять раз. Эта хуйня не является веселой, интересной, не "испытывает навыки" экипажа, не добавляет ничего в раунд, это просто раздражающий пердеж, который фиксится исключительно синтами, поскольку инженерам всегда лень тратить пять-десять минут жизни на ковыряние в проводах десятка шлюзов.
* Немного поменял вес у других ивентов, например слегка понизил шанс радшторма и электрошторма, слегка повысил шанс вспышки вирусов, лозы, т.д.
> Нерф убогих брич-ивентов, мелкая настройка веса других

- code/__defines/mobs.dm
- code/game/antagonist/station/changeling.dm
- code/game/antagonist/station/cultist.dm
- code/game/antagonist/station/traitor.dm
- code/game/jobs/job/captain.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/engineering.dm
- code/game/jobs/job/job.dm
- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
- code/game/jobs/job/security.dm
- code/modules/client/preference_setup/occupation/occupation.dm
- code/modules/mob/new_player/new_player.dm
**ПР выполнен по согласованному реквесту:
close #199** 
Коротко: 
- Глав могут брать только те персонажи, у которых выставлена фракция НТ.
- Главы требуют теперь как минимум нейтральную лояльность к НТ.
- Главы больше не становятся антагонистами на станции раунд-стартом. Исключение: РД, СМО и СЕ могут быть предателями.
**Я не веду обсуждения в этом ПР'е. 
На дальнейшие изменения в этом ПР'е влияет только тот человек, что согласовал его.**
> Лояльные главы

- maps/exodus/exodus_define.dm
Скорее всего из-за того, что был выставлен плохой maxx и maxy - необходимое число руды не генерировалось даже после нескольких попыток, что послужило отсутствием руды в песке на астероиде.
Фикс не проверялся.
> Возможный фикс генерации руды на астероиде.

- code/modules/clothing/spacesuits/rig/suits/station.dm
* Убрал ограничение зрения в активном состоянии, убрал слепоту в неактивном, теперь там обычный рестрикт, как у сварочного щитка.
* Повысил скорость на единицу. Сначала повысил на две единицы, как советовали в иссуе, но чет слишком быстро. Этот РИГ и должен быть медленным, просто не настолько ебануто медленным как сейчас. В выключенном состоянии тоже передвигаться всё так же невозможно, ибо нашлись любители.
* Повысил резист к бруту на 15 единиц, большую часть фауны можно хоть руками бить. Понизил резист к пулям и лазерам на 15 единиц, ибо не боевой РИГ. Повысил резист к взрывам, и дал полную защиту от радиации. Шахтеров частенько облучают артефакты, так что в РИГе можно будет копать без риска получить дозу. К тому же, защита от радиации на нем имеет смысл, он же для строительства в …
> Бафф индустриального РИГа

- code/datums/communication/aooc.dm
- code/datums/communication/dsay.dm
- code/datums/communication/looc.dm
- code/datums/communication/ooc.dm
- code/game/world.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/adminpm.dm
- code/modules/admin/verbs/adminsay.dm
- code/modules/lobby_music/_lobby_music.dm
Привет! Здесь небольшие изменения для чата. 
Первая половина исправляет отсутствие возможности открывать ссылки. По умолчанию гунчат фильтрует сообщения и если у него не выставлен параметр для текста, он не даёт делать из текста ссылку. Как вариант исправления добавил в некоторых местах `linkify` где это необходимо (чаты коммуникации, общение с администрацией)
Вторая половина добавляет в чат уведомление когда сервер перезапускается. После успешного переподключения уведомление становится в зелёным. Немного поможет невнимательным отличить перезапуск от падения
> Исправление ссылок гунчата

- code/modules/mob/say.dm
typing_indicator удалялся дважды, что роняло мастер контроллер.
```
[17:20:37] Runtime in garbage.dm,355: /atom/movable/overlay/typing_indicator destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic<br />
usr: Petro Lanis (/mob/living/carbon/human) ([0x30001fb]) (the floor) (131,128,2) (/turf/simulated/floor/tiled) (petrov1tch)<br />
usr.loc: The floor (/turf/simulated/floor/tiled) ([0x1017d04]) (131,128,2) (/area/hallway/primary/central_two)<br />
[17:20:40] Runtime in garbage.dm,355: /atom/movable/overlay/typing_indicator destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic<br />
usr: Avel Kirshtein (/mob/living/carbon/human) ([0x30001fd]) (the floor) (115,140,2) (/turf/simulated/floor/tiled) (novan13)<br />
usr.loc: The …
```
> fix(typing_indicator): don't delete typing_indicator twice

- code/game/machinery/autolathe.dm
- code/game/machinery/autolathe_datums.dm
- code/game/machinery/vending.dm
Здравия!
В соответствии с иссуем про анализаторы голоса добавил оные в автолат и также в вендоматы: в обычном вендомате их два и появляются только если взломано; в вендомате антагов их четыре и в вендомате токсинщиков шесть.
Ну и ещё я конечно не дождался ответа на #1550 , но таки не верю, что это не баг. Сделал так, что меню автолата заново открывается только если человек рядом с ним.
closes #1189
closes #1550
> Voice Analyzer + меню автолата не лезет в глаза

- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Двери открывать не могут, а стулья складывают. Даже тот стул, к которому привязаны. Что позволяет заменить двухминутное сидение в резисте не слишком ужасным уроном по гроину и относительно коротким станом, а к тому же уронить зазевавшегося рядом сидящего швардена или офицерика. Или вообще кого угодно.
В общем, поправил, добавил проверку на наручники - теперь если человек связан, то ничего не сложит.
> Связанные люди не могут складывать стулья

- code/modules/materials/materials.dm
- code/modules/mining/ore_datum.dm
Исправляет ошибку, связанную с неправильным названием материала и руды:
`[02:50:28][ERROR] Unable to acquire material by name 'hydrogen'`
> Исправление водорода

- code/__defines/client.dm
- code/datums/communication/ooc.dm
- code/modules/client/preference_setup/global/05_settings.dm
- code/modules/client/preference_setup/global/preferences.dm
- code/modules/donations/new/donations.dm
- code/modules/donations/new/donator.dm
- code/modules/onyxchat/browserassets/css/browserOutput.css
- code/modules/onyxchat/browserassets/css/browserOutput_marines.css
- code/modules/onyxchat/browserassets/css/browserOutput_white.css
- code/modules/onyxchat/browserassets/css/styles_template.css
- code/stylesheet.dm
Добавил патронам уникальные цвета для никнейма в OOC. Выглядит это так:
Патроны могут выбрать цвет любого тира более низкого уровня или вовсе отключить эту фичу в префенсах.
На сервере пока не заработает с реальными патронами, потому что бот не заполняет эту инфу в базе. Но это я тоже скоро сделаю.
close #1007
> feat(donator): decorate ckey in ooc with patreon tier color

- code/game/objects/structures/crates_lockers/closets.dm
- code/modules/modular_computers/computers/modular_computer/damage.dm
- code/modules/power/smes.dm
- code/modules/supermatter/supermatter.dm
СМ является важным объектом на Исходе, её проёб должен караться намного сильнее, чем сейчас.
- СМ теперь притягивает объекты с нижних/верхних уровней.
- Взрыв от СМ теперь полностью зависит от значения EER. Чем он больше - тем сильнее взрыв. При экстремально мощном заряде выдается дополнительное сообщение по общей частоте, с предупреждением о том, что ожидается очень мощный взрыв.
- Взрыв от СМ может вызвать замыкание у СМЕСов неподалеку.
- Взрыв от СМ может вызвать галлюцинации у людей, находящиеся в зоне без радиационной защиты. Чем ближе к эпицентру - тем сильнее галлюцинации.
- СМ больше нельзя спрятать в шкафчике.
Также поправил реагирование некоторых объектов на взрывы, чтобы после него не было такого, что ты приходишь к месту происшествия, а там космос и... невредимая модульная …
> Усиливаем последствия от взрыва суперматерии.

- code/modules/client/preferences_savefile.dm
`Runtime in character_setup.dm, line 32: undefined proc or verb /savefile/save preferences()`
> Фикс рантайма у SScharacter setup

- code/modules/client/preference_setup/global/05_settings.dm
Фиксим пачку рантаймов:
```
[17:50:37] Runtime in 05_settings.dm,54: Cannot read null.client<br />
proc name: sanitize preferences (/datum/category_item/player_setup_item/player_global/settings/sanitize_preferences)<br />
src: Settings (/datum/category_item/player_setup_item/player_global/settings)<br />
call stack:<br />
Settings (/datum/category_item/player_setup_item/player_global/settings): sanitize preferences()<br />
Global (/datum/category_group/player_setup_category/global_preferences): sanitize setup()<br />
/datum/category_collection/pla... (/datum/category_collection/player_setup_collection): sanitize setup()<br />
/datum/preferences (/datum/preferences): sanitize preferences()<br />
/datum/preferences (/datum/preferences): New(Florrie (/client))<br />
Florrie (/client): …
```
> fix(preferences): runtime in 05_settings.dm,54: Cannot read null.client

- code/game/gamemodes/changeling/changeling_powers.dm
- code/game/gamemodes/changeling/modularchangling.dm
- code/modules/mob/living/carbon/human/human.dm
- Генокрад теперь высасывает реагенты вместе с кровью из своей жертвы.
- Способность "Rapid Regeneration" теперь не может стаковаться, также она занерфана в два раза в целях баланса(?).
- Способность "Finger Lockpick" приобретает задержку в десять секунд после каждого использования.
- Ревайв генокрада больше не будет возвращать протезированные конечности. 
close #1585
close #1064 (Спрайты не предоставили, но я всё равно закрою)
close #1065
> "Дергаем" генокрада за щупальца.

- code/controllers/configuration.dm
- code/modules/client/client_procs.dm
**Перед принятием ПРа необходимо выставить опцию `hard_player_limit` в конфиге на нужный.**
Позволяет игрокам с живым мобом на сервере обходить лёгкий лимит, но и если при этом при всём не заполнен тяжелый лимит.
close #1445
> Игроки с живым мобом могут обходить лёгкий лимит. 

- code/game/objects/noose.dm
Убраны анимации петли в связи с некоторыми проблемами
Отсутствие головы в активном состоянии теперь должно выкидывать из петли
fixes #1677
close #1649 (не думаю что стоит что-то добавлять, машинам не наносится оксиурон т.к. они не могут дышать)
> Hangout Party End

- code/game/objects/items/weapons/teleportation.dm
Rebalance.
Also fixes issue with O(N) intended malfunctions for 'battle function' becoming O(N^unknown) due to malfunction calling itself on each iteration.
Therefore, chance for each type of malfunction was raised a bit.
Charge costs multiplied, as there was no 'bluespace cell' with 10k total capacity when previous values were implemented.
Reworked 'vortex cap' for non-timelord VMs.
Plus, EMP now won't strike single vortex manipulator multiple times in small time intervals.
> More server-friendly vortex behavior.

- code/game/objects/items/stacks/rods.dm
Суть что было раньше: 
1 лист стали = 2000 ед. в автолате
1 прут = 1875 ед, в автолате
1 лист стали = 2 прутам в крафте руками
2000 != 3750
Итог дюп стали.
Мои изменения: 
matter = list(MATERIAL_STEEL = 1875) ----> matter = list(MATERIAL_STEEL = 1000)
1 лист стали= 2000
2 прута = 2000
fix #1778
> Исправление дюпа стали.

- code/game/machinery/alarm.dm
Суть проблемы:
При выставлении на термостате крайних температур 0С и 40С, тот никак на это не реагировал.
Крайние температуры считались недопустимыми из за проверки >= и <=.
Решение: Замена проверок на > и < соответственно.
fix #1780
P.S Решение разжевано и положено в рот автору by TermService
> Исправление работы термостата в настенном AirAlarm

- code/modules/mining/mine_turfs.dm
Суть: когда происходит разрушение астероид-турфа в котором находится артефакт - на расстоянии двести тайлов все мобы получают рандомный не смешной эффект, а также турфы на этом расстоянии получают неплохую дозу радиации. И ладно бы это происходило раз в полгода, но это происходит слишком часто, чтобы игнорировать.
fix #464
> Убираем радиацию с астероида.

- code/modules/mob/living/living_powers.dm
- code/modules/mob/living/simple_animal/friendly/mouse.dm
- code/modules/mob/observer/ghost/ghost.dm
- Запрещаем атаковать в то время, когда они прячутся.
- Добавляем дополнительный кулдаун после атаки.
- Добавляем кулдаун после использования кнопки `hide`.
- Уменьшаем здоровье до одной единички.
- Уменьшаем урон до 1 - 2.
- Убираем кнопку `Become Mouse`.
> Нерфаем мышей после обновы

- baystation12.dme
- code/__defines/flags.dm
- code/_helpers/game.dm
- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/machinery/camera/motion.dm
- code/game/machinery/flasher.dm
- code/game/objects/effects/proximity.dm
- code/game/objects/items/devices/transfer_valve.dm
- code/game/turfs/turf.dm
- code/modules/assembly/holder.dm
- code/modules/assembly/proximity.dm
- code/modules/hydroponics/spreading/spreading.dm
- code/modules/mob/mob_defines.dm
- code/modules/power/singularity/containment_field.dm
- code/modules/projectiles/guns/launcher/slugsling.dm
Вместо того, чтобы проверять каждый атом на HasProximity вокруг другого атома при заходе на турф - мы создаём поле из слушателей, которые при триггере (Crossed) передают сигнал владельцу.
Должно снизить лаги, поскольку конкретно сейчас у нас вызывается куча пустых проверок, которые ничего не делают.
```
Proc			Self CPU Time 	Total CPU Time	Real Time 	Overtime	Calls	
/atom/proc/HasProximity	8,125		15,974		24,069		0,595		2882942	
```
Одолжено с ТГ.
> Proximity System

- code/modules/mob/living/silicon/robot/robot_items.dm
Нек-ые из них пожирают ящики, да вот только ящики они эти не опустошают, из-за чего всё содержимое попадало в нулспейс. В том числе и игроки.
> Фикс диспенсеров у киборгов

- code/modules/power/apc.dm
Т.е. не нужно проводить каждый раз карточкой, чтобы его перезапустить.
> Инженерный доступ позволяет перезапускать заблокированный АПЦ

- code/game/objects/items/weapons/material/shards.dm
Поскольку у нас используется `Crossed` - при прохождении на `turf` с огромным кол-вом шрапнели у нас он процессится каждый отдельно друг от друга. В этом ПРе мы используя `locate` сверяемся с тем, что шрапнель первый в списке `Contents` у `loc`, тем самым заставляя процессить первый шрапнель за всех.
Также выставлен максимальный урон. Согласовано геймдизайнером -  @MemoryDreams. 
fix #1810
> Ограничиваем стак-урон у стекляшек/шрапнели на полу

- code/modules/client/asset_cache.dm
- code/modules/client/client_procs.dm
Когда клиент дисконнектится, сервер продолжает слать ему ассеты. Из-за того что клиент занулился, сервер еще и рантаймил, ругаясь на отправку ассетов в null.
Заменил пару ассертов на проверки. Теперь когда клиент дисконнектится отправка ассетов прерывается.
> fix(assets): stop sending assets for disconnected clients

- code/datums/sun.dm
опечатка вызывала обновление солнечных панелей каждый тик вместо 60 секунд положенного
> fix(sun.dm): misprint

- code/game/machinery/nuclear_bomb.dm
Fixes:
1) Nuclear disk could've been transported from station in mixed gamemodes (e.g. siege, crossfire); obviously this resulted in nuclear operatives being unable to blow nuclear bomb, as disk cannot be tracked properly outside of the station.
2) For gamemodes without mercenaries, it was still a big problem that nuclear disk could be thrown into space. As is is unique, there were no in-game ways of returning it back from various space z-levels (first - you can't track it, second - you can't transport it with handtele or teleporter hub).
Related issues:
fix #1933, fix #1932
> Improper nuclear disk behavior

- code/game/machinery/nuclear_bomb.dm
ИИ больше не может взаимодействовать с ядерной боеголовкой.
Роботы же могут, но только если она находятся рядом с ней.
> Взаимодействие синтетиков с ядерной боеголовкой.

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/external/_external_damage.dm
- code/modules/organs/external/_external_icons.dm
- code/modules/organs/pain.dm
Немного переписал логику боли так, чтобы она меньше грузила сервер. Теперь боль считается один раз за тик в Process. Метод get_pain() возвращает посчитанное ранее значение.
Также явно разделил методы get_pain и get_full_pain. Первый метод - только накопившаяся боль из разных источников, а второй добавляет также боль от урона и увечий.
Методы add_pain и remove_pain схлопнулись в adjust_pain.
fix #1951 
Не запускал, т.к. локально хрен протестишь боль. По коду все нормально, вроде, но на крайняк ничего кроме боли сломаться не должно. Если сломается боль - узнаем по репортам, больше не вижу вариантов.
> refact(pain): update pain on Process

- code/game/machinery/kitchen/cooking_machines/_cooker.dm
Пофикшены кухонные приборы
Обнаружил, что вот тут https://github.com/ChaoticOnyx/OnyxBay/commit/a6eb7437e74e85076303cddec36d1b88bd2e3992#diff-cff537c745ca48ebb082adb773278ec3 была сломана функция проверки того, что в кухонной машине есть объект и что у этого объекта положение - прибор. Пофиксил. Далее нашел, что, если жарить животных, то они дюпаются, потому что при удалении объекта в печи удаляется "рука" типа /obj/item/weapon/holder, а не само животное, которое эта "рука" удерживает, поэтому проверяем и удаляем животное.
Closes #1861.
> fix(cookers)

- code/game/objects/items/stacks/telecrystal.dm
Запрещаем телепортироваться при помощи телекристалла на админ-уровнях.
> Фикс использования ТК на админ уровнях

- code/game/machinery/washing_machine.dm
Пофикшено то, что стиралка выкидывала вещи только после двойного открытия.
closes #283
> fix(washing machine)

- code/modules/mob/living/silicon/robot/robot.dm
Поправил нулевой закон емагнутого киборга, чтобы он не конфликтовал с остальными. "\he" заменил на нейтральный "they", потому что не работало и местоимение тупо исчезало.
fixes #2285
> Исправление конфликта законов емагнутого борга

- code/game/objects/structures/lattice.dm
Починил проверку на включённость и топливо сварки, из-за сломанности которой решётчатый пол можно было спилить выключенной сваркой или сваркой без топлива.
fix #2299
> Фикс: выключенная сварка пилит решётчатый пол

- code/modules/clothing/head/misc_special.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Исправление минорного бага с исчезновением спрайта сварочной маски при её поднятии:
Раньше, если не щёлкать по маске в руке, а сразу кликнуть Adjust Mask в контекстном меню, то маска исчезала.
Теперь нет.
closes #1501
> fix(welding helmet)

- code/game/mecha/equipment/tools/tools.dm
Reverts ChaoticOnyx/OnyxBay#2033
Из-за этого ПРа Рипли стал неиграбельным мехом вместо просто плохого меха. Из-за желания автора пофиксить отступ проверка кода стала очень сложной и были внесены изменения, не описанные в ПР(например, то, что обычная дрель теперь может ломать укрепленные стены). Из-за проебанного отступа логика была похерена, и блок кода `101-120` с рудами попал в логическую зону стены, из-за чего становится недоступным вовсе, то есть руда не копается как руда и не помещается в сумку.
Откатите это и напишите нормально вместе с нормальным ребалансом Рипли.
P.S. И отступы фиксить нужно в отдельном коммите, а не все в один.
> Revert "Алмазный бур для Рипли стал хуже обычного, а обычный стал хуйней"

- code/modules/clothing/spacesuits/rig/rig_pieces.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/mob/living/carbon/human/species/station/station.dm
- code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
- code/modules/organs/external/_external.dm
Короче у органов не обновлялся full_pain из-за того, что они не попадали в список "плохих органов", т.е. раненых, которые нужно обновлять. А не попадали они туда, потому что там не было проверки на боль.
Что забавно, "плохие органы" - это типо оптимизация, чтобы все органы не обновлять, но чтобы составить этот список мы все равно итерируемся по всем органам. А потом еще и проверяем дополнительно на need_process. Короче какая-то странная двойная оптимизация. need_process итак должен нормально справляться, так что спилил нафиг "плохие органы", чтобы не плодить одни и те же проверки.
fix #2045
> Чиним стан, вызываемый болью

- code/modules/integrated_electronics/subtypes/output.dm
В самом описание платы написано что доступ можно получить через научную сеть.
> Takes a string as a name and a boolean to determine whether it is on, and uses  this to be a camera linked to **the research network**.
Но доступ получается в свою очередь через вкладку тандера.
Было:
Стало:
> Исправил доступ к интегральной камере.

- code/modules/research/stock_parts.dm
Исправил уровни исследований, получаемые при разборке подпространственного анализатора (aka subspace analyzer), на корректные.
Неисправленный вариант:
Исправленный:
Связанных иссуев не нашёл.
> fix(Subspace-Analyzer)

- code/__defines/damage_organs.dm
- code/modules/mob/living/carbon/human/death.dm
- code/modules/organs/external/_external.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
это история про флаг по имени ORGAN_DISFIGURED. ORGAN_DISFIGURED был обычным флагом который как обычно занимался своей жизню искривлением лица, всё было прекрасно
но однажды кто-то присвоил этот флаг всем органам, таким образом нарушив баланс сил во вселенной, ведь этот флаг можно было вылечить только для лица. такова была его задумка
затем тоби написал с его примением целую логику! и теперь, после облитого кислотой человека, тот становился инвалидом до конца своих дней, ибо вылечить у чего-то кроме головы ORGAN_DISFIGURED было невозможно
если серьёзно
- пофиксил хуйню при которой после кислоты челик вечно падал вследствие чего шок стейдж ронял сердце
- пофиксил эту хуйню у хасков(?) и скелетов. теперь если потрогать санса то после превращения вы не будете падать замертво
- кислота теперь …
> Фикс постоянных падений от кислоты и не только.

- code/modules/mob/living/carbon/human/species/station/station.dm
А ещё понизил с 19 до 18 для скреллов и таяр, но судьба ксеносов никого не волнует.
Зачем? У нас ведь ЕРП разрешили, негоже будет, если несовершеннолетних совращать будут. На самом деле мне просто нечётные числа не нравятся.
> Повысил минимальный возраст с 17 до 18

- code/modules/mob/living/say.dm
Теперь если рот заклеен скотчем или заткнут кляпом, все невербальные языки, в том числе язык жестов всё равно работают.
resolves #1141
> fix(muzzle): sign-language

- code/modules/storyteller/characters/support.dm
- code/modules/storyteller/triggers/spawn_antagonists_triggers.dm
Пофиксил спавн антагонистов сторителлером.
Из-за двух багов он спавнил только одного трейтора и одного чейнжа, не пересчитывая баланс. Сейчас поправил, теперь он будет спавнить чейнжей и трейторов до тех пор пока баланс не исправится.
Локально не тестировал, ибо сложно и неудобно. На сервере посмотрим, если тут будут баги опять - ничего плохого не случится.
> fix(storyteller): fix balancing and spawn_antagonist trigger

- code/modules/xenoarcheaology/finds/find_spawning.dm
Устранил рантайм из-за ошибки в синтаксисе.
Если кому интересно, Dream Maker распознавал такую строчку не как list association, а как named argument: `I.origin_tech.Add(TECH_MATERIAL = pick(1, 2, 3, 4, 5, 6))`.
close #2503
> fix_runtime(archeology)

- maps/exodus/exodus_shuttles.dm
Отключил инициализацию на старте игры у отсутствующего шаттла. Война рантаймам! Даёшь чистые логи!
```
[11:05:41] Runtime in shuttle.dm,47: Shuttle "Transport" could not find its starting location.
proc name: New (/datum/shuttle/New)
src: Transport (/datum/shuttle/autodock/ferry/transport)
call stack:
Transport (/datum/shuttle/autodock/ferry/transport): New(null, null)
Transport (/datum/shuttle/autodock/ferry/transport): New(null, null)
Transport (/datum/shuttle/autodock/ferry/transport): New(null)
Shuttle (/datum/controller/subsystem/shuttle): initialise shuttle(/datum/shuttle/autodock/ferry/... (/datum/shuttle/autodock/ferry/transport), 1)
Shuttle (/datum/controller/subsystem/shuttle): initialize shuttles()
Shuttle (/datum/controller/subsystem/shuttle): Initialize(291418)
Master …
```
> fix_runtime(shuttle)

- code/modules/mob/new_player/new_player.dm
Портировал с поляриса и немного подправил. Запрещает заходить за персонажа с таким же именем. Удобно.
> Убрал возможность заходить за того же персонажа в одном раунде

- code/_helpers/logging.dm
- code/modules/library/manuals/engineering.dm
- code/modules/library/manuals/medical.dm
- code/modules/library/manuals/nanotrasen.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Пофиксил логирование рантаймов на этапе загрузки карты и кучу веселых рантаймов:
```
[00:43:52][ERROR] Runtime is caught before log initialization!
[00:43:52][ERROR] Runtime is caught before log initialization!
[00:43:52][ERROR] Runtime is caught before log initialization!
[00:43:52][ERROR] Runtime is caught before log initialization!
[00:43:52][ERROR] Runtime is caught before log initialization!
[00:43:52][ERROR] Runtime is caught before log initialization!
```
На самом деле это оказались рантаймы типо такого:
```
[04:23:14][ERROR] [EARLY RUNTIME] [04:23:14] Runtime in medical.dm,138: Cannot read null.wikiurl
[04:23:14][ERROR] [EARLY RUNTIME]   proc name: New (/obj/item/weapon/book/manual/medical_diagnostics_manual/New)
[04:23:14][ERROR] [EARLY RUNTIME]   src: Medical Diagnostics Manual …
```
> fix(logging, manuals, animals): fix map loading runtimes and logging of them

- code/_helpers/logging.dm
- code/modules/projectiles/projectile.dm
Прожектайлы имеют классное свойство зависать и вешать сервер:
```
Infinite loop suspected--switching proc to background.
If it is not an infinite loop, either do 'set background=1' or set world.loop_checks=0.
proc name: Process (/obj/item/projectile/test/Process)
source file: projectile.dm,481
usr: null
src: the projectile (/obj/item/projectile/test)
src.loc: the floor (184,118,2) (/turf/simulated/floor/tiled/white)
call stack:
the projectile (/obj/item/projectile/test): Process(the floor (184,118,2) (/turf/simulated/floor/tiled/white))
the projectile (/obj/item/projectile/test): launch(Andrzej Dresden (/mob/living/carbon/human))
check trajectory(Andrzej Dresden (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret), 7, null, null)
the turret (/obj/machinery/porta_turret): …
```
> fix(projectile): throw exception when projectile stuck

- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/subtypes/output.dm
Починил работу интегральных лампочек в следующих аспектах:
-Лампочки теперь в принципе могут светить.
-При вытаскивании платы лампочки из ассембли, собственно ассембли не продолжает светиться без лампочки.
Новые значения дальности света взял из фонарика (или лампы накаливания) для обычной лампы, а для улучшенной - люминисцентной лампы.
Мощность (сила, яркость) света в соответствии с фонариком/лампой накаливания у всех интегральных ламп.
close #1037
> fix(Integrated lighting)

- code/modules/client/asset_cache.dm
- code/modules/client/client_procs.dm
- code/modules/onyxchat/browserOutput.dm
эпикус сказал пора обрубать поддержку старого чата
я хз зачем но сделал пару твиков
- чат грузится первым из ассетов кроме фонтов
- страшное сообщение о загрузке ассетов запихнутов в старый чат и немного отредачено
- ту чаты больше не выводят в старый чат
(вайтспейс)
> tweak(chat): trivials 'n outputs

- code/datums/browser.dm
Теперь главное окно игры остаётся активным после открытия/закрытия всплывающего интерфейса. Другими словами, игрок теперь не теряет возможность ходить с помощью стрелочек клавиатуры после щелчка по АТМ или открытия панели бота.
Подобное поведение уже было у консолей (можно было открыть интерфейс консоли и отойти), я скопипастил его на другие случаи.
> Всплывающие окна не перехватывают фокус

- code/modules/mob/living/living.dm
can_move_mob иногда вызывал сам себя и сваливался в бесконечную рекурсию, что вызывало лаги
Профайл:
[50a2afc46ff1abcd.docx](https://github.com/ChaoticOnyx/OnyxBay/files/4925557/50a2afc46ff1abcd.docx)
> fix(mob): fix can_move_mob proc's endless recursion

- code/modules/admin/topic.dm
- code/modules/client/preference_setup/loadout/lists/utility.dm
- code/modules/client/preference_setup/loadout/loadout.dm
- code/modules/donations/new/donator.dm
- code/modules/music_player/_music_player.dm
- code/modules/music_player/subtypes_player.dm
- code/modules/music_player/subtypes_tape.dm
* Добавил бумбокс и пустую кассету (на которую можно записать свою музыку) в лоадаут для патронов. Бумбокс требует ранга патрона Ассистент, а кассета - ХоСа.
* Убрал ID у бумбокса, т.к. он неоч полезный и спамит педалей когда бумбокс тыкают в лоадауте.
* Починил педальный вайп музыки с кастомной кассеты.
ПР согласован с сенатом
> feat(donations): add boombox and custom tape to loadout for patrons

- code/game/machinery/autolathe.dm
Интерфейс автолата обновлялся слишком медленно, из-за чего имелась возможность при быстром закликивании после распечатывания предмета и до обновления окна отправить в печать то, на что не хватает ресурсов, что приводило к вечному зависанию машины и невозможности дальнейшей с ней работы до вмешательства педальными кнопками. Теперь окно обновляется без задержки, что исправит проблему.
fix #3000 fix #1893
> Менее занятые автолаты

- code/modules/onyxchat/browserOutput.dm
`code/modules/onyxchat/browserOutput.dm:179:warning: original_message: variable defined but not used`
> вырезаем анюзд вар

- code/modules/hydroponics/seed.dm
- code/modules/hydroponics/seed_machines.dm
Проблема связана со стартовыми 10 ксенорастениями в автомате ксенофлоры. Им присваиваются uid #186-196. После мутаций или изменений в ксено, uid новых растений начинается с #86 и увеличивается на 1 за каждое из этих действий. В итоге когда uid пересекаются с растениями из автомата, случаются чудеса, описанные в иссуе. 
Теперь uid новых растений будет генерироваться через sequential_id.
fix #2755 
Довольно полезная фича не работала из-за одного условия. 
Теперь диск с генами можно вставлять в экстрактор, что позволяет записывать несколько генов и прививать их семенам одновременно.
> Фикс id растений/Фикс флора диска

- code/game/world.dm
Перед отправкой сообщения в ООС через дискорд проверяем, не забанен ли, часом, у отправителя ООС.
resolve #2258 ? Не уверен, правда, что тот иссуй про баны, а не именно муты, но даже если и нет, то проблемы в этом я не вижу - за обход мута можно и бан на оос навесить.
> fix(discord ooc): prevents ooc ban evasion over discord

- code/game/objects/items.dm
Исправил ситуацию при удалении предмета, лежащего в рюкзаке (ящике/другом хранилище), когда иконка этого предмета навсегда прилипала к экрану.
close #2193
> Фикс предметов, "зависающих" на экране при удалении из рюкзака.

- code/game/machinery/Sleeper.dm
- code/game/machinery/cryo.dm
Пофикшена смешнявка, когда при перетаскивании мышью игрока на слипер/крио человек мог уйти на обед, лечь на операцию, улететь на астероид, а потом форсмувнуться в машинку. Плюс, поклажа в крио человека в грабе была мгновенной, что еще круче, добавил задержку.
resolves #1639
> fix(sleeper and cryo teleport)

- code/game/antagonist/antagonist.dm
- code/game/antagonist/antagonist_helpers.dm
- code/game/antagonist/station/changeling.dm
- code/game/antagonist/station/cult_god.dm
- code/game/antagonist/station/cultist.dm
- code/game/antagonist/station/revolutionary.dm
- code/game/antagonist/station/traitor.dm
Добавил логов, чтобы поймать баг #3024. По коду пока не понял как так получается, что сторителлер спавнит чейнжей несмотря на ограничения ролей.
Переименовал protected_jobs, чтобы понятнее была суть этой переменной.
Плюс починил рантайм:
[17:25:17] Runtime in antagonist.dm,112: Cannot read null.player_age
proc name: build candidate list (/datum/antagonist/proc/build_candidate_list)
[17:25:17] Runtime in antagonist.dm,112: Cannot read null.player_age
proc name: build candidate list (/datum/antagonist/proc/build_candidate_list)
> fix(antagonist): fix runtime, add more logs

- code/modules/onyxchat/browserassets/js/browserOutput.js
Количество хранящихся в чате сообщений увеличено в два с половиной раза. Теперь при достижении лимита вайпается половина истории за раз. Это позволит избежать восхитительного экспириенса, когда текст постоянно уплывал относительно окна, делая попытки его чтения или копирования отдельным, достаточно неприятным, испытанием.
> Постоянное укатывание чата при достижении лимита сообщений едет нахуй

- code/game/objects/structures/crates_lockers/closets.dm
Добавил проверку, чтобы нельзя было использовать мультитул на хранилищах без замка (мусорках, гробах, пакетах для трупов...)
close #2077
> fix(closet): forbid hacking non-existent locks

- code/game/machinery/kitchen/gibber.dm
- code/game/objects/structures/kitchen_spike.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/mob.dm
- code/modules/mob/mob_defines.dm
- code/modules/modifier/helpers.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/external/standard.dm
Меняет функционал крюка, теперь на него можно вешать чуть ли не любых мобов, которых держишь вторым грабом.
Вешание и снимание моба с крюка требует некоторое время и наносит брут урон, моб может попытаться сам вырваться с крюка, на это потребуется больше времени (чем если бы его кто-то другой снимал), и в процессе нанесется дополнительный урон.
Если висящий моб не человек (и не человекоподобный), то использованием острого предмета на крюке (не на мобе) можно этого моба гибнуть подобно тому, как это делает гиббер. Если висящий моб человек (или человекоподобный) (включая мартых), то его конечности тем же образом можно рубать на мясо, но от самого тела таким образом не избавиться (хотя его тоже можно рубать на мясо).
Гриндер теперь выдает столько же мяса, сколько выдало бы нарезание на крюке …
> Расчлененка для кухонного крюка

- code/modules/client/client_defines.dm
- code/modules/mob/living/bot/secbot.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/say.dm
- code/modules/mob/typing_indicator.dm
- interface/skin.dmf
В скин добавлено окно saywindow, которое имитирует окно input, которым say_wrapper принимает ввод. say_wrapper теперь использует это окно вместо input. forcesay теперь сохраняет радио ключи и все введенное (на момент удара) сообщение (кобольд в дискорде сказал, что норм) и корректно работает с хоткейным сеем.
closes #2231
>  Прерывание речи от ударов

- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/say.dm
Делает так, чтобы при запуске сея без аргументов (прожатие энтера в хоткейном меню или запуск Say из командной строки без доп. символов) не всплывало окно бйондовского инпута.
Попутно изменен forcesay, чтоб корректно обрабатывал вариант без кавычек( Say something вместо Say "something), который теперь возможен, и чтоб убирал индикатор набора сообщения.
> Мелкофикс сея

- code/modules/mob/typing_indicator.dm
- interface/skin.dmf
Название кнопки использовалось два раза и из-за конфликта отвалилась кнопка Chat в нижнем-левом углу экрана.
fix #3177
> fix(say): fix "Chat" button

- code/modules/mob/grab/normal/norm_neck.dm
- code/modules/multiz/structures.dm
В красном грабе теперь можно таскать людей по вертикальным лестницам. Такой перенос длится 15 секунд вместо двух.
close #1027
> tweak(ladder): В третьем грабе можно таскать людей по лестницам

- code/__defines/mobs.dm
- code/modules/mob/living/simple_animal/friendly/mouse.dm
В ходе реализации #1830 оказалось, что мыши вообще могут кусать не только стопы, но и ноги с гроином.
Это конечно смешно, но хотелось бы чтобы мыши не могли кусать людей в жестких ботинках. Да и чтобы мыши прыгали я еще ни разу не слышал.
Мыши все еще могут кусать лежащих людей куда угодно.
> nerf(mouse): forbid them to bite organs above feet

- code/modules/mob/blob.dm
- code/modules/mob/living/bot/secbot.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/say.dm
- code/modules/mob/typing_indicator.dm
- interface/skin.dmf
Предположительно исправляет проблемы с фокусировкой на окно хоткейного сея и обратно.
Добавляет возможность изменять размер окна хоткейного сея и выпиливает центрирование оного окна при первом вызове (теперь будет запоминать размер и расположение).
Меняет подстановку в режиме чата с say на Say (чтоб соотносилось с вербами).
Меняет работу typing indicator, теперь его наличие напрямую зависит от наличия фокуса на строке чата (будь то командная строка в режиме чата или строка в окне хоткейного сея), в частности, теперь оно работает с командной строкой в режиме чата и частично вне режима чата (если при фокусировке в строке прописан Say ", то облачко появится).
Незначительно меняет работу forcesay, теперь вместо затирания всего инпута он будет затирать только часть после Say " (чтобы можно …
> Прерывание речи от ударов 3

- code/modules/mob/login.dm
- code/modules/mob/new_player/new_player.dm
Добавление трейтов выносим в самый конец создания персонажа, т.к, когда трейт на дальтонизм тригерит update_client_color(), у хуманов доходит до 109 строки (helpers.dm) и какого-то хуя if(!client) возвращает true и в итоге не происходит обновления цветов, а у железяк наоборот, if(!client) возвращает false и цвета обновляются.
Также добавил в начало создания персонажа animate(client, color = null, time = 10), чтобы при перерождении не накладывались старые цвета.
Fix #593 
P.S Вроде все работает нормально, но это не точно.
> Fix(new_player.dm) ЖИЗНЬ ДАЛЬТОНИКАМ

- code/modules/mob/blob.dm
close #3186 фикс рантайма суть которого, что про инициализации худа оно не присваивалось худу из рантайма.
> fix(blob.update_hud): RUNTIME: Cannot read null.blob_powerbar

- code/__defines/gamemode.dm
- code/modules/client/preference_setup/antagonism/01_candidacy.dm
- code/modules/ghosttrap/trap.dm
Исправил ошибку, из-за которой возможность получать оповещения о доступном вселении из призрака в культиста работала как возможность получить роль обычного культиста (и наоборот).
Более явно выделил настройки оповещений для гостов.
Убрал настройку оповещений о возможности вселения в культиста (как и раньше, их будут получать только те, кто выставил в настройках роль культиста на **Low** или **High**).
Возможность вселения в камень душ отвязана от роли культиста.
Оповещения для фамильяра отвязаны от роли визарда.
От награды отказываюсь в пользу @MorJams (ПР #3219)
closes #2170
> fix(antagonist preferences): double Cultist

- code/game/gamemodes/objective.dm
- code/modules/mob/living/life.dm
Зафикшен баг, при котором не выполнялся обжектив на десятиминутный арест. Проблема заключалась в криворукости программистов, что сделали сие творение таковым, что is_brigged "запускался" и вычислялся только в конце игры. Исправлено введением нового прока для обжективов, что выполняется каждый игровой тик для каждого моба что имеет обжектив. Практически не затратно и затрагивает на данный момент только арест ревы и триторов. В идеале создает новую платформу для обжективов, что могут в потиковое вычисление.
close #3303 
~ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to …
> rework & fix datum/objective

- code/game/gamemodes/cult/runes.dm
- code/game/machinery/nuclear_bomb.dm
- code/modules/paperwork/paper.dm
Фиксит руну культа, которая привязывается к бумаге. Конкретно исправляет механизм проверки "чистоты" бумаги.
Делает parse_named_fields проком (как-то оно стало вербом, и этого никто не заметил).
Исправляет html_encode в set_contents бумаги (оно там было и предполагалось, что оно применяется к входу, но там был беекод и оно не применялось, и чет я проглядел, когда ранее копался в этом). Попутно правит формат инструкции к нюке (который бумаге кормит хтмл теги, хотя не должен).
Мелочи: меняет табы на пробелы в выравнивании комментов, добавляет дефолтное значение содержимому бумаги, убирает лишний аргумент из update_space.
closes #3410
> Мелкофиксы бумаги

- code/_helpers/roundend.dm
Фиксит сломанные иконки в окне с ролями в конце раунда. Для этого из to_chat скопипащен кусок кода, который для каждого макроса \icon вызывает icon2html (ибо \icon не работает в браузере).
closes #3396
> Фикс иконок в окне с ролями в конце раунда

- code/datums/browser.dm
Добавляет обработку контента браузера тем самым регексом из to_chat, который меняет макрос \icon (который не работает в браузере) на картинки, генерирующиеся icon2html (который попутно отсылает нужное клиенту).
#3397 с мержем этого изменения вроде бы как не нужен, но там суть в том, что из-за того, что браузер свой на каждого клиента, этот регекс будет прогоняться по одному и тому же содержимому много раз, что не то что бы хорошо. Так что можно оба мержить (если этот вообще будет вмержен).
> Форс icon2html в содержимом браузера

- code/game/antagonist/antagonist.dm
Фиксы для antagonist_spawn (мидраундового спавна антагонистов):
1. Добавил проверку на тип моба. close #3376
2. Исправил сброс mind.special_role после спавна. Из-за этого такие роли не показывались в Who и в АнтагХУДе. close #2566
> fix(antagonist): some fixes for antagonist_spawn

- code/modules/admin/admin.dm
- code/modules/paperwork/adminpaper.dm
Я пытался разобраться с тем, почему админ факс дублирует вводимый текст, ответом оказалось то, что он каким-то образом вызывает generateinfolinks таким видом, что текст и endtag прилетает два раза. Вот быстрофикс
fix #3583
- [* ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ *] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ *] Я запускал сервер со своими изменениями локально и все протестировал.
- [*] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
> Починил дупликацию текста админ факса

- code/game/objects/items/crayons.dm
- code/modules/mob/holder.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Оказалось, что содержимое желудков космонавтов находится на нулевом Z-уровне, а симплмобы не умирают и вообще не обрабатываются, пока на их Z-уровне нет игрока, оттого и вечное существование без переваривания. Кроме того, пробить желудок изнутри можно было только с предметом в руках. Это починено.
Мобов через маску кушать теперь нельзя, мелки тоже. Вилку я съесть не смог.
В процессе тестирования обнаружилось, что съедение не мешает мышам кусать обжору за ноги, но я без понятия, как это фиксить. Впрочем, мыши-ИИ не кусаются, а игрок успеет немногое до переваривания, так что, думаю, не страшно.
close #2176
> Починка пожирания

- code/_global_vars/lists/flavor.dm
- code/modules/mob/living/silicon/robot/robot.dm
- Теперь борг может выбрать стандартный модуль вне зависимости от того, есть ли на станции другие стандартные борги.
Если лимит на выбор специализированного модуля ещё оправдан, то почему нельзя стать стандартным - непонятно. К тому же, это приводит к смешным проблемам вроде #3668
> Unlocking Standard module 

- code/modules/projectiles/guns/projectile.dm
4 сом ризон раньше даже селф аттак пистолета перекладывал магазин в свободную руку, заставляя переключатся на неё и выкидывать магаз на drop, дабы подать обратно уже новый
теперь можно эпично выкидывать пустой магазин после рэмбовской перестрелки единственным нажатием клавиши 
бонус поинты тому кто найдёт крутой sfx как магазин слайдит из пистолета
> фаст рэмбо анлоад магазина пистолета

- code/game/gamemodes/vampire/vampire_powers.dm
- code/modules/reagents/reagent_containers/blood_pack.dm
Перезарядка абилки сосания крови. Лимит в 115 крови с процесса выкачки, а также момент в 85, после которого время перезарядки вырастает вдвое, поэтому появляется еще выбор пососать меньше для более быстрой перезарядки, а не сосать до упора. В итоге имеем такой расклад: лимит в 115 единиц крови, 3 минуты стандартной перезарядки, 6 увеличенной в случае пресыщения, момент начала пресыщения в 85 единиц крови. Можно сосать кровь из пакетов, измененный текст сообщений, а также уменьшенный уровень "безумия" у новообращенных.
close #3490
close #3489
> Фиксы вампиров, измененный текст сообщений.

- code/modules/modular_computers/file_system/program.dm
Микрофикс рантайма
```
[17:13:26] Runtime in program.dm,134: Cannot read null.computer_emagged
proc name: can run (/datum/computer_file/program/proc/can_run)
usr: Milo Belikov (/mob/living/carbon/human) ([0x300018b]) (the floor) (172,121,2) (/turf/simulated/floor/tiled/white) (azeroender)
usr.loc: The floor (/turf/simulated/floor/tiled/white) ([0x1017634]) (172,121,2) (/area/assembly/robotics)
```
fix #3827
> fix(modular_computer): fix runtime on program's check if computer emagged

- code/modules/integrated_electronics/subtypes/manipulation.dm
С посаженных растений в трее(tray) можно собирать образцы кусачками. С небольшим шансом при сборе, трей может получить флаг sampled = 1, который не позволит более собирать образцы с этого же растения. Этот флаг обычно сбрасывается, если растение по разным причинам уже не в трее(сбор, рубка топором). Проблема заключается в том, что при выкапывании растения с помощью Plant manipulation module интегрального принтера, флаг sampled не сбрасывается. Из-за этого, если посадить следующее растение, с него невозможно будет брать образцы.
Теперь флаг сбрасывается к 0, при использовании модуля в режиме выкапывания.
> Фикс модуля интегралки Plant manipulation module

- code/modules/power/fusion/core/core_control.dm
- code/modules/power/fusion/fusion_reactions.dm
Убрал проверку на поломку RUS-T (Его нельзя сломать), поменял несуществующие реагенты в реакциях на существующие(Откуда у нас в газах бор и бз, верно?). Это необходимый хотфикс, чтобы на данный момент получить хоть-какой то движок, чтобы в последствии его переписать(Полностью чужой код). 
Извиняюсь за три коммита, была проблема с логином.
> RUS-T engine reactions and controls fix

- code/modules/integrated_electronics/subtypes/input.dm
Починил невозможность передать (или есть слишком переусложненный способ передачи текста до которого я не дошел) юникод символы отличные от английских символов, именуемыми буквами и спец. символов.
_По запросу от ревьюверов готов предоставить интегралки для проверки, но вроде ничего не сломал._
> tweak(advanced_signaller) unicode letters fix

- code/modules/organs/external/_external.dm
- code/modules/organs/external/head.dm
- code/modules/organs/external/standard.dm
- code/modules/projectiles/projectile/beams.dm
- Опять переработан шанс на вызов артериального кровотечения. Раньше артерия могла прокнуть на всех органах после равного порога в 30 урона, теперь же порог зависит от органа. 20 у кистей, 25 у пяток, 30 у локтей, 40 у коленей, гроинов и голов, 45 у груди; порог теперь высчитывается не из имеющегося урона + нанесённого, а только из имеющегося. 
- Порог для перелома головы увеличен с 35 до 40 урона;
- Снижен модификатор артериального кровотечения для локтей (0.75 -> 0.65), пяток (0.5 -> 0.45), кистей (0.5 -> 0.35);
- Исправлено нанесения урона по органам станлучами и шоковыми лучами;
> ТобиБоёвочка - Артериальное

- code/game/antagonist/antagonist.dm
- code/modules/storyteller/storyteller_metric.dm
когда педалишь гораздо приятнее видеть периодически появляющиеся рантаймы чате которые хотя бы как-то можно анализировать, а не спавн трёхсотысячь строк драфтов и метрик за инстанс которые насмерть убивают тебе дримсикер (из-за гунчата i guess)
- метрики сторителлера убраны из дебаг логов чата и теперь сейвятся онли в лог файл
- драфты антага убраны из дебаг логов чата и теперь сейвятся онли в лог файл
брух
> Перестаём срать в чат дебаг лога по пять страниц драфтов и странице метрики

- code/game/gamemodes/cult/runes.dm
а раньше не видели
- экзамайн за госта показывает чё за культяпская руна
- принт описания руны в чат перенесён ниже (а не выше как было) самого экзамайна
скринов не будет
> госты видят чё за руны

- code/procs/announce.dm
Проблема: я сидел в шкафу, не услышал анонса о радиационной угрозе и помер от радиации. Другие анонсы из шкафов тоже не слышно.
Почему так: сейчас анонс рассылается всем мобам, у которых z-уровень соответствует станции. У мобов в шкафах z-уровень выставляется в 0 и я не вижу легкого способа это поправить и не поломать всё. Для мобов в контейнерах текущий контейнер записывается в `loc`, поэтому перед анонсом можем проверить `get_turf(loc).z` у моба.
> Мобы в шкафах не слышат глобальных анонсов

- code/game/objects/buckling.dm
Затрагивает структуры, на которые можно садить людей (карго-паровоз, кровати...). Для них задан `pixel_shift` - координаты, на которые нужно сдвинуть иконку прицепленного моба. До этого PR `pixel_shift` модифицировал только текущий сдвиг (`pixel_x`,`pixel_y`) моба и не трогал дефолтный сдвиг `default_pixel_x`, `default_pixel_y`. Из-за этого некоторые анимации, завязанные на дефолтные сдвиг могли просирать текущий сдвиг.
Еще заметил, что сейчас анимация buckle/unbuckle для таких структур долгая, сделал быстрее.
close #4024
> Починил анимацию атаки для водителя карго-паровоза

- code/modules/modular_computers/file_system/programs/engineering/atmos_control.dm
- nano/templates/atmos_control.tmpl
- Программа Atmospherics Control теперь показывает панельки только с соединённых З-левелов (основной этаж и гетто);
- Список в Atmospherics Control сортируется в алфавитном порядке;
- В Atmospherics Control тревоги выводятся выше всего остального;
> fix(atmospherics control)

- code/modules/mob/new_player/new_player.dm
- code/procs/announce.dm
Теперь если есть ИИ, то он будет называть пребывающих существ на станцию.
Если их несколько, то тут, кому прокнуло, тот и сказал.
Если ИИ нет, отвечает "старый" ИИ (тот же самый).
> feat(announcment) auto arrivals announcement by AI

- code/game/objects/items.dm
- code/game/objects/items/stacks/medical.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/items/weapons/storage/storage.dm
- code/game/objects/items/weapons/storage/storage_ui/default.dm
- Исправлены остающиеся в УИ инвентарей (рюкзаки, коробки, etc.) фантомные бэкграунды после удаления предмета (складывание стаков, взрыв гранат, etc.);
- Инвентари теперь можно открывать с помощью alt+click;
- Киборги теперь могут открывать инвентари. Класть внутрь модули и вытаскивать вещи, конечно же, нельзя;
- Инструменты детектива теперь могут взаимодействовать с рюкзаками, коробками, etc. если интент - не help;
> tweak(storage): alt+clicks, usage by robots, background tile fixes

- code/game/objects/items/weapons/storage/secure.dm
- code/game/objects/items/weapons/storage/storage.dm
- Исправлена возможность открывать закрытые сторейджи с помощью alt+click;
> fix(storage): alt+click interaction w/ locked storages

- code/modules/mob/hear_say.dm
- Сообщения в сей с двумя или более восклицательными знаками в конце будут показываться полужирным текстом в обычной речи и по рации;
- Две замены <span> на SPAN() (хотел остальное поменять, но там страшное по три спана за строчку, и в итоге не компилилось, так что к чёрту)
ПР сделан по иссую:
close #2617
> Кричим полужирным текстом

- code/game/antagonist/antagonist.dm
- code/game/antagonist/antagonist_update.dm
- code/game/antagonist/outsider/commando.dm
- code/game/antagonist/outsider/deathsquad.dm
- code/game/antagonist/outsider/ert.dm
- code/game/antagonist/outsider/ninja.dm
- code/game/antagonist/outsider/raider.dm
Разработчик забыл явно определить вайтлист рас, из-за этого можно было выбрать Алиумов при спавне ЕРТшником, так же исправил возможность выбрать воксов, алиумов, скреллочки и таярочки для ниндзи, и некоторые другие минорные фиксы.
~~А если бы не мех на Фловуи, я бы не заметил и не пофиксил этот баг, спасибо тебе, котик, люблю, целую~~
> tweak(antag appearance) fix ability to select xenos

- code/game/area/Space Station 13 areas.dm
- code/game/gamemodes/cult/narsie.dm
- code/game/gamemodes/cult/runes.dm
- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- code/game/turfs/simulated.dm
- code/game/turfs/turf.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
Ну что тут сказать? Вперед гостчане!
Стулья нельзя крутить в священной зоне.
Зона становится священной после того, как кто-нибудь в ней осветит любой турф при помощи святой воды.
Зона перестает быть священной после осквернения (defile) культистами или же Нар-Си.
close #2969
> Позволяем призракам крутить стулья

- code/__defines/items_clothing.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/suits/miscellaneous.dm
- code/modules/clothing/suits/storage.dm
- code/modules/clothing/suits/toggles.dm
- code/modules/mob/living/carbon/human/examine.dm
Изменил прок получения строки одежды для экзамайна, теперь можно отключить отображение аксессуаров.
Добавил флаг для отключения возможности просмотра аксессуаров на костюме к "большим костюмом".
close #1197
> Кобура с пушкой. Исправляем

- baystation12.dme
- code/_onclick/other_mobs.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/gloves/boxing.dm
- code/modules/clothing/gloves/stun.dm
- code/modules/mob/living/carbon/human/species/species.dm
- Добавлены стан-перчатки. Они делаются из любых перчаток (кроме боксёрских) добавлением 15 проводов и закреплением их изолентой. Получившиеся стан-перчатки наследуют некоторые свойства у оригинала.
- Для работы стан-перчаткам нужна девайс-батарейка - одна атака стоит 50 заряда. Установленную в перчатки батарейку можно снять кусачками.
- Для атаки стан-перчатками нужно нажать на человека дизармом, имея надетые стан-перчатки с достаточным зарядом батарейки. Болевая сила атаки немного слабее станпрода, а атака сопровождается видимыми искрами. Стан-атаки нельзя направлять в ноги и пятки, чтобы нельзя было уложить здорового человека одной атакой.
- Успешное рукопожатие, инициированное носителем стан-перчаток, исполняет стан-атаку над вторым человеком.
- Стан-атака имеет небольшой шанс (5% для …
> Стан-перчаточное

- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- code/modules/mob/typing_indicator.dm
- interface/skin.dmf
Комбинация клавиш `Shift + F3` или `Shift + T` теперь инвертирует текущее состояние префа `Show Typing Indicator`. То есть, проще говоря, зажатый шифт при сэе скрывает, либо показывает индикатор набора текста, в зависимости от значения настройки. 
<h3>Зачем и нахуя?</h3>
К примеру вам захочется что-то передать в канал генокрадов, при этом не показывая окружающим, что вы что-то пишите. Или же если вы другой какой антагонист. Или же если вы хотите сказать что-то по рации, при этом не останавливая мимоидущего крокодила. Или же наоборот, хотите привлечь его внимание. С этой фичей вам не нужно будет постоянно залезать в настройки, чтобы скрыть/показать свой индикатор набора текста.
<h3>Что-то ещё?</h3>
Сделано с небольшим *костылем* с проверкой по времени в которое кнопка Shift перестала …
> Активное переключение индикатора набора текста

- code/game/antagonist/blob/blobs/factory.dm
- code/game/antagonist/blob/theblob.dm
Исправляет ошибку `Runtime in ,: bad arg name 'plane'` которая сыпется сотнями. От неё как минимум раньше крашились ДД, и само появление краша зависит от железа.
> Runtime fix

- code/game/objects/items/weapons/smokables/cigarettes.dm
- code/game/objects/items/weapons/smokables/smokables.dm
- code/game/objects/items/weapons/storage/fancy.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
1. Создан новый вид сигарет syndi_cigs с увеличенным chem_amount с 5 до 15 для хороших реакций(возможно изменение для баланса)
2. Создана ./syndi_cigs/flash. Сигарета флешка при закуривании(задержка до первой затяжки)и поджигании станит ~5 секунд(возможен ребаланс)
3. Создана ./syndi_cigs/smoke. Сигарета дымовуха при закуривании и поджигании создаёт пук дыма вокруг игрока(не очень полезна, но подойдёт при побеге в техах, закурил и в шкаф залез)
4. Создана ./syndi_cigs/mind_breaker. Сигарета наркоманов при закуривании и недлительном курении(хватает пару затяжек) начинаются глюки.
5. Создана ./syndi_cigs/tricordrazine. Сигарета лечилка, действует как tricordrazine...
6. В связи с моей кривозадостью созданы пачки для данных сигарет они абсолютно одинаковы кроме содержимого и …
> Syndicate Cigarettes rework

- code/_helpers/roundend.dm
- code/datums/browser.dm
Фиксит это говно в конце раундов
```
[13:08:50] Runtime in browser.dm,32: undefined variable /client/var/client
[13:08:50] Runtime in browser.dm,32: undefined variable /client/var/client
[13:08:50] Runtime in browser.dm,32: undefined variable /client/var/client
[13:08:50] Runtime in browser.dm,32: undefined variable /client/var/client
[13:08:50] Runtime in browser.dm,32: undefined variable /client/var/client
```
> Roundend runtime fix

- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Добавил новый прок для human'ов, который позволяет нанести дамаг рандомной органической конечности (не протезу). Также добавил этот прок в метаболизм аритразина, чтобы он не наносил дамаг протезам. Фолбэк к mob/living/carbon на всякий случай оставил.
fix #4731
> fix(arithrazine): prothesis damage from arithrazine

- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- SpacemanDMM.toml
- baystation12.dme
- code/__defines/_compile_options.dm
- code/_helpers/auxtools.dm
nuff said
Имплементирует поддержку [auxtools](https://github.com/willox/auxtools) которая будет полезна для отладки в VSC с помощью SpaceDMM.
Работает при запуске F5 при скомпилированном билде. На живом сервере использоваться, собственно, не будет.
Он уже ловит ошибки которые "приостанавливают" игру, так что не удивляйтесь если ваша игра зависнет. Вам просто надо нажать на кнопочку продолжить в вискоде.
Список текущих ошибок которые выявились с начала локального раунда.
```
Debug Server: "Pausing execution (reason: Runtime(\"code/modules/admin/banjob_iaa.dm:178:Assertion Failed: establish_db_connection()\"))"
Debug Server: "Pausing execution (reason: Runtime(\"Shuttle \\\"Creaker\\\" could not find its starting location.\"))"
Debug Server: "Pausing execution (reason: Runtime(\"bad …
```
> experimental(auxtools): adds auxtools support

- code/modules/mob/mob.dm
Теперь `point-to` копирует `pixel_x` и `pixel_y` у атома, на который был указан.
"Зачем" показано на картинках ниже.
> Точный point-to

- code/modules/modular_computers/file_system/programs/generic/file_browser.dm
- code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
1)Документы теперь печатаются не хтмл кодом, а как было задумано.
(Объяснить почему так было в дискорде/коментариях)
2)Размер окошка ввода документа теперь нормальный
close #4877
Затрагивает #3547 (Пункт о размере окошка)
> Nanoword fix + tweak

- code/_helpers/roundend.dm
Было(2 игрока на серве):
Стало(2 игрока на серве):
Вынес команду для логирования так что-бы она срабатывала ОДИН раз, а не столько же сколько игроков
close #4907
> roundend logs fix

- code/__defines/lighting.dm
- code/controllers/evacuation/evacuation.dm
- code/game/area/Space Station 13 areas.dm
- code/game/area/areas.dm
- code/modules/power/apc.dm
- code/modules/power/lighting.dm
- Пофиксил ломающийся свет у лампочек в то время, когда у них выставлен особый режим освещения, вроде эвакуационного.
- Также теперь сохраняются режимы освещения при выставлении другого, так что быстрое включение/выключение пожарной сигнализации не уберёт эвакуационный режим освещения. 
- Также моргание лампочек при особом режиме перестает ломать их вовсе. Могло быть вызвано культо-магией или же синтетиками. 
fix #1807
Возможно были ещё репорты, но я не нашёл.
> Фикс режимов освещения

- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
Теперь ресурсы грузятся во время подключения к серверу, а не подгружаются во время игры. Больше никаких фризов от стандартных песен из джукбокса, крашей от эмбиентов и пропадающих иконок. 
В теории, может решить проблему и с белыми окошками наноУИ.
После обновления игрокам рекомендуется почистить кэш бульонда. А желательно - чистить после каждого обновления.
> Fixes everything

- code/game/jobs/job/civilian.dm
- code/game/jobs/job/job.dm
- code/modules/economy/Accounts.dm
- code/modules/events/money_hacker.dm
Всем абсолютно похуй на этот ивент (ровно как и на деньги), потому я решил сделать его жестче. 
Теперь же хакер нацеливается на абсолютно **все** финансовые аккаунты станции, а не на какой-то один. 
Предотвратить кражу денег можно следующими способами:
1. Временная блокировка аккаунта через специальную консоль у главы персонала.
2. Повышение уровня безопасности аккаунта хотя бы до среднего.
3. Обналичивание всех денег со счета.
4. Временное отключение НТсервера - самый глобальный и, по идеи, наилучший вариант.
С этими изменениями, как мне кажется, люди будут создавать кое-какое, но всё же, движение в раунде. А при четвертом варианте решения проблемы многие программы будут недоступны, вроде сенсоров, что позволит антагам сделать свой ход.
> Делаем ивент с кражей денег жёстче

- code/game/machinery/autolathe.dm
Собственно говоря как у нас работает АВТОЛАТ, он проверяет может ли user, дропнуть/положить куда-то то, что у него в руке, т.к. в руке у борга не листы метала а sheet loader то соответственно ничего не происходит ибо дропнуть и сложить он его не может АВТОЛАТ ругается, что Вы такое положить не можете
Так что была сделана проверка на то что моб является карбоном
fix #5009
> Borg sheet loader to autolathe fix

- code/game/mecha/combat/combat.dm
- code/game/mecha/mecha.dm
Убрал и заменил потому, что дримчекер жалуется на неё.
Проверил локально, ничего не сломалось, мехи ходют.
> Убрал переопределение do_after() у мехов

- code/modules/organs/external/machine.dm
Теперь синтовскую батарейку при ставке в органическое туловище ничего не делает, раньше таким образом можно было возродить человека.
Я пока не нашел иссуя, который удовлетворяет условиям найденного мною бага
<details>
🆑
bugfix: Теперь нельзя возрождать не-синтетиков с помощью установки батарейки.
/🆑
</details>
> fix(microbattery) organic human can't revive by using microbattery.

- code/modules/admin/verbs/individual_logging.dm
- code/modules/emotes/emote_mob.dm
- code/modules/mob/mob_helpers.dm
Ну а также перевёл само окошко в фэйковые нанохуи
<details>
<summary>Окошко</summary>
</details>
close #4800 
🆑
tweak: Добавлено логирование эмоутов в Individual Round Logs.
/🆑
> Прикрутил эмоуты к сейлогам в Individual Round Logs

- code/modules/mob/living/simple_animal/hostile/alien.dm
```yml
🆑
bugfix: Ксеноморфы-мобы больше не бессмертные.
bugfix: Ксеноморфы-мобы теперь принадлежат фракции "xenomorph" и не будут нападать на лицехватов.
/🆑
```
> Removes simplemorphs' immortality

- code/datums/movement/movement.dm
- code/game/objects/effects/chem/foam.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/weapons/soap.dm
- code/game/turfs/simulated.dm
- code/modules/ZAS/Airflow.dm
- code/modules/hydroponics/grown_inedible.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/life.dm
- Исправлена длительность опрокидывания (и добавлен стан) при поскальзывании (и от ветерка). Оно пострадало во время череды фиксов и сейчас то же мыло роняет буквально на 0 секунд.
- Исправлены столкновения с предметами во время утягивания атмосферой (во время разгерметизации, например). Больше никаких "You are pinned against the bullet casing by airflow! x15", а разгерметизации выглядят чутка зрелищнее.
- handle_npc() убран под spawn(), ибо там есть step(), замораживающий процесс на время перемещения.
```yml
🆑
tweak: Поскальзывание и сквозняк теперь роняют на большее время.
tweak: Предметы больше не блокируют друг друга и мобов при утягивании атмосферой.
/🆑
```
> Removes lack of proper movement thingies

- code/modules/client/preference_setup/loadout/loadout.dm
Не очень то и круто пролистывать каждый раз всю страницу только из-за того, что она вся в донатных шмотках, *пикус.
```yml
🆑
rscadd: В лодаут добавлена кнопка сокрытия донатных предметов.
/🆑
```
> Кнопка для скрытия донатных предметов в лоадауте

- baystation12.dme
- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/airlock_control.dm
- code/game/machinery/doors/airlock_presets.dm
- Рефактор дверок. Убраны всякие ненужные "src." и "as".
- Попутно исправлен пропадающий на долю секунды спрайт открытия шлюзов с открытыми панельками. Оно было впилено специально давным-давно из-за бага с flick() в буонде, а он уже давно исправлен.
- Попутно исправлено свечение при открытии шлюзов. Лампочки на спрайтах загораются сразу во время начала анимации открытия, а свечение включалось только после полного открытия. 
- Пресеты дверок вынесены из airlock.dm в отдельный файл, ибо он дико разросся.
```yml
🆑
bugfix: Шлюзы начинают светиться при начале анимации открытия, а не в конце, в соответствии со спрайтами.
bugfix: Спрайты шлюзов с открытой панелькой больше не исчезают на долю секунды при открытии.
bugfix: Шлюзы с открытой панелькой больше не излучают свет при открытии, в …
```
> Removes lack of airlocks refactoring

- code/game/objects/items/weapons/backwear/rpd.dm
```yml
🆑
bugfix: Исправлена невозможность печатать мусорные трубы с помощью РПД.
tweak: Стандартная батарейка с 250 заряда заменена на батарейку с 1000 заряда. Теперь заряда хватит не на 5 стандартных труб, а на 20.
/🆑
```
> Removes lack of RPD disposal pipes

- code/game/objects/items/weapons/grenades/explosive.dm
- code/game/objects/items/weapons/grenades/grenade.dm
Нынешние гранаты чуть ли не телепортируются при метании - сложно даже отследить, откуда и куда они летят. А так - и красиво, и баланснее.
И у гранатомётов появляется хоть какая-то ценность.
```yml
🆑
tweak: Уменьшена скорость полёта гранат.
/🆑
```
> Removes 飛雷神-grenades

- code/modules/projectiles/guns/energy/energy.dm
- code/modules/projectiles/projectile/special.dm
```yml
🆑
tweak: Энерговинтовкам добавлен режим стрельбы лазерными болтами. У обычных винтовок (у ЕРТ) болт такой же, как у лазерных карабинов, у дешёвой версии (у ХоСа) - слегка занижены характеристики.
tweak: Уменьшена скорость перегрева nuclear energy gun. Теперь его можно использовать относительно безопасно, если сильно не спамить.
/🆑
```
> Removes lack of energy rifles viability

- code/modules/mob/mob.dm
- code/modules/mob/mob_defines.dm
ИтКупс добавил хоткей для поинт-ту, но не добавил ей задержку, из-за чего некоторые недобросовестные игроки пользуясь этим засирают всем чатик. 
<details>
```yml
🆑
tweak: Добавлена задержка для повторного использования Point-To.
/🆑
```
</details>
> Задержка для Point-to

- code/game/gamemodes/cult/runes.dm
Для лолконверта теперь надо 2 культиста минимум. Если провести ритуал в одиночку у человека в чате всплывает предложение вступить.
<details>
```yml
🆑 Lovla aka Zert0X
tweak: Для лолконверта теперь надо 2 культиста минимум.
tweak: При конверте в одиночку, у цели будут спрашивать хочет ли она?
/🆑
```
> tweak(cult): lol convert 

- code/game/objects/structures/inflatable.dm
- Исправлена вместительность кейсов с надувными барьерами. Теперь они вмещают шесть штук.
- Добавил ещё одну стенку в кейсы. Три штуки - это как-то ни в пизду, ни в Красную Армию.
- Переименовал кейсы из "inflatable barrier box" в "inflatable barriers kit". Как-то лучше оно смотрится, хз.
- Чутка подчистил код в inflatable.dm.
- Итем_стейт наборов с надувашками заменён с коробки шприцев на кейс.
```yml
🆑 
bugfix: Исправлена вместительность наборов с надувными барьерами.
tweak: Наборы с надувными барьерами теперь содержат две двери и четыре (вместо трёх) стенки.
/🆑
```
> Removes brokenness from inflatable barriers cases

- code/_helpers/russian.dm
- code/modules/emotes/emote_mob.dm
Эмотить можно используя русскую раскладку ("*тщв" == "*nod")
<details>
```yml
🆑
rscadd: Теперь использовать эмоуты можно и с русской раскладкой ("*тщв" == "*nod").
/🆑
```
</details>
> Emote cyrillic workaround

- code/_onclick/ai.dm
- code/_onclick/cyborg.dm
- code/game/turfs/turf.dm
Двери можно открыть кликая на турф а не на иконку двери
<details>
```yml
🆑
rscadd: Двери теперь можно открывать кликая на тайл где находится дверь.
/🆑
```
</details>
> Doors can be interacted with by clicking on turf

- code/modules/virus2/effects/common.dm
- code/modules/virus2/effects/mutation.dm
`Runtime in viruses.dm, line 46: Cannot read 0.len`
Из-за занулления листа `antigen` проверка в файле viruses.dm ломалась к чертям, не давая вирусу умереть, если тот должен был.
Возможно, но не обещаю, это пофиксит спавн миллиард вирусов. 
Но вот это `Skipped 6053 runtimes in viruses.dm,46.` точно никуда не годится.
> Фикс рантайма у вируса

- code/modules/admin/admin.dm
- code/modules/admin/topic.dm
Совместно с Фрогой было замечено, что игнорирование игроками сообщений педалей успешно лечится отключением игрового окна. Незаменимая фича при общении с новичками, которые нарушают правила и при этом не замечают стучащегося к нему админа. 
<details>
<summary>Пример того, как это выглядит</summary>
</details>
<details>
```yml
🆑
admin: В Player Panel добавлена кнопка, позволяющая закрыть игровое окно для игрока.
/🆑
```
</details>
> Кнопка для закрытия игрового окна

- code/modules/power/lighting.dm
После обновы с софтдарком в дормы фронтира подселились негры и стали активно воровать уголь, из-за чего не было видно литтерали ничего дальше тайла. Повысил какие-то два параметра наскальным лампам, вроде стало лучше. Попутно понизил им шанс заспавниться сломанными (надеюсь) и слегка повысил радиус красным лампочкам в техах. Красные лампочки всё еще совершенно ничего не освещают, так что "дух техов" остается, но выглядит хоть немного приятнее.
Дормы до:
Домы после:
<details>
```yml
🆑
maptweak: Изменил освещение дорм фронтира на более яркое и приятное глазу. Слегка поднял радиус освещения мелких красных лампочек.
/🆑
```
</details>
> tweak(lights): tweaked frontier lights a bit

- code/__defines/subsystems.dm
- code/controllers/subsystems/initialization/character_setup.dm
- code/modules/client/preference_setup/global/05_settings.dm
Преференсы отказывались загружаться из-за того - что в `get_preference_value` у нас, в отличии от бэя, осталась проверка на инициализированность подсистемы. Перенёс установку флага и приоритет системы на чуть раньше и добавил краш в проверку.
возможно fixes #5510 
```yml
🆑
bugfix: Исправлена проблема с загрузкой преференсов.
/🆑
```
> Преференсное

- code/modules/storyteller/storyteller.dm
Убрал сторителлеру срабатывания во время эвакуации
fix #2810
<details>
```yml
🆑
tweak: Сторителлер больше не будет срабатывать во время эвакуации.
/🆑
```
</details>
> tweak(storyteller): don't fire storyteller on evacuation

- code/game/gamemodes/traitor/contracts.dm
close #5492
close #5550 
<details>
```yml
🆑 Pl3aseJust3ndMyPain
bugfix: Ядра метроидов и чертежи станций в контрактах теперь называются правильно.
/🆑
```
</details>
> Правильное название экстрактов и чертежей в контрактах

- code/modules/mob/living/carbon/human/species/species.dm
Исправил удаление имплантов при ревайве - теперь они будут оставаться на месте. Внезапно, Борер - тоже имплант и при ревайве он ломался.
fix #5337
<details>
```yml
🆑
tweak: Теперь чудесные воскрешения и вылечивания не будут удалять импланты.
bugfix: Исправлен баг из-за которого после лечения ядром Ховерхеда пропадала возможность извлечь Борера хирургически.
/🆑
```
</details>
> fix(human): preserve implants on revive

- code/modules/clothing/chameleon.dm
- code/modules/clothing/clothing.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
Опечатка в коде привела к смешному. Раз уж всё равно надо было фиксить - чутка рефакторнул код анармед-комбата. Бонусом - больше нет хардкодной проверки на наличие робастных хамелеон-перчаток, а у любых перчаток теперь есть переменная unarmed_damage_override. Если она не нулл (дефолтное значение) - при надевании этих перчаток урон с руки будет заменяться на это значение (с учётом стандартного разброса +-40%). 
Циферки урона, в общем-то, никак не затрагивает, они остаются прежними (до поломки). 
```yml
🆑
bugfix: Исправлен неадекватно-высокий урон при ударах руками по себе, по людям в грабе и по лежачим.
/🆑
```
> Removes over-robust unarmed attacks

- code/modules/power/lighting.dm
- Добавлена возможность выковыривать разбитые лампочки из светильников. Если светильник под током (есть питание и в зоне включен свет) - с шансом в 75% горе-инженер получит разряд.
```yml
🆑
tweak: Теперь разбитые лампочки можно вытаскивать из светильников с помощью монтировки. Следовательно, борги теперь могут разбирать светильники.
/🆑
```
> Removes cyborgs' inability to disassemble lgiht fixtures

- code/modules/mob/living/carbon/alien/alien.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/simple_animal/hostile/facehugger.dm
- code/modules/mob/mob.dm
```yml
🆑
tweak: Ксеноморфы теперь могут раздевать людей, но с ограничениями.
tweak: Лицехваты теперь скидывают не только шлемы и маски, но и предметы на ушах.
/🆑
```
> Removes xenomorph's inability to strip people

- code/modules/mob/living/carbon/human/species/station/station.dm
Добавляет перегрев при ношении скафандров Таярам(но не до урона, как с синтами). Температура в рамках 47-49C, что им лишь неприятно. Нужно, чтобы хоть как-то оправдять их шерстистость.
close #5370
<details>
```yml
🆑
tweak: Таяры теперь перегреваются (без получения урона) при ношении скафандров.
/🆑
```
</details>
> Allow Tajar to overheat in the spacesuit with no damage.

- code/modules/mob/living/carbon/human/species/station/station.dm
Температура Таяр будет в пределах, которые не вызовут урон, но будет отображатся иконка о перегреве.
fix #5776 
<details>
```yml
🆑
bugfix: Теперь таяры не получают урон от перегрева.
/🆑
```
</details>
> Allow Tajar to overheating with no damage

- code/game/objects/items/toys.dm
close #5679
ура фикс размеров шариков
алсо теперь можно наполнять не только из ватертанков
<details>
<summary>cheenglox</summary>
```yml
🆑
bugfix: Водяные шарики теперь приобрели ожидаемый малый размер и научились менять его при наполнении.
bugfix: Водяные шарики теперь можно наполнять не только из водяных баков.
/🆑
```
</details>
да я знаю что из раковины хрен наполнишь но мне влом пихать костыли
> fix(water_ballon): w_size approximation & fulfillment from dispensers

- code/modules/spells/general/area_teleport.dm
- code/modules/spells/general/mark_recall.dm
- code/modules/spells/spell_code.dm
- code/modules/spells/targeted/ethereal_jaunt.dm
- code/modules/spells/targeted/projectile/passage.dm
Добавил проверку на нахождении в криокапсуле, если маг кастует из нее, то его сначала оттуда выкинет и моментально произойдет блинк/телепорт
fixes #707
<details>
```yml
🆑
bugfix: Исправил баг с телепортацией мага из криокапсулы. Теперь никакого раздвоения.
/🆑
```
</details>
> fix(teleport): fixes all mages teleports

- code/modules/mob/living/simple_animal/hostile/mimic.dm
При педальном спавне или спавне из экстракта мимик был бессмертен из-за того, что он обязан быть копией чего-то. Теперь в случаях таких спавнов при смерте он станет обычным контейнером.
fixes #5626
<details>
```yml
🆑
bugfix: Мимики больше не бессмертные
/🆑
```
</details>
> Убираем бессмертных мимиков

- code/_macros.dm
- code/modules/spells/aoe_turf/knock.dm
- code/modules/spells/contracts.dm
- code/modules/spells/general/contract_spells.dm
- code/modules/spells/general/return_master.dm
Одной строчкой поправил действие Knock указав что шлюз открывается насильно, как монтировкой.
Парой строк поправил действия скиллов которые влияют на ученика мага. Теперь ученик телепортируется К МАГУ, а не наоборот. Область действия скиллов больше не ограниченна областью видимости. 
close #5693
close #5656
<details>
```yml
🆑
bugfix: Заклинание "Knock" открывает обесточенные шлюзы.
bugfix: Исправлены заклинания взаимодействия мага с учениками.
tweak: Заклинание "Return to Master" телепортирует ученика к магу, а не наоборот.
/🆑
```
</details>
> Чиним нерабочие заклинания мага.

- code/modules/clothing/chameleon.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/gloves/stun.dm
- Стан-перчатки инициализировались через жопу.
- Заспавненные/намаппленные стан-перчатки теперь по умолчанию выбирают базой рабочие перчатки. До этого - получалось поломанное нечто.
- Попытка обрезать/обмотать проводами перчатки-хамелеоны теперь выдаёт очевидное сообщение, как у боксёрских перчаток.
> Removes broken stungloves initialize()

- code/game/objects/structures/crates_lockers/closets.dm
- code/game/objects/structures/crates_lockers/crates.dm
- code/modules/materials/material_recipes.dm
Добавил контейнерам переменную материала, теперь можно настроить во что разбирается каждый тип контейнера. Немного рефакторинга.
Поправил описание самодельного контейнера
close #5624
сlose #5625
<details>
```yml
🆑
bugfix: Пластиковый ящик при разборе больше не дает стальной лист
bugfix: Поправил описание самодельного контейнера из пластали
/🆑
```
</details>
> fix(crates): add specific material to crates and some refactoring

- code/game/objects/items/weapons/material/twohanded.dm
Исправил отображение копья и биты на спине. Раньше они отображались лишь тогда, когда во время перемещения на спину вторая рука была занята.
fix #5756
<details>
```yml
🆑Oubi
bugfix: Исправлено отображение копья и биты на спине
/🆑
```
</details>
> fix(twohanded): fix display of two-handed weapons on the back

- code/__defines/inventory_sizes.dm
- code/game/objects/items/weapons/storage/toolbox.dm
Исправил вместимость тулбокса синдиката
Добавил значение для вместимости тулбокса синдиката и добавил его самому тулбоксу, теперь он вмещает идеальное количество предметов
<details>
```yml
🆑
bugfix: Исправлена вместимость тулбокса Синдиката
/🆑
```
</details>
close #5950
> Syndicate toolbox fix

- code/modules/mob/grab/grab_datum.dm
- code/modules/mob/grab/grab_object.dm
Исправления багоюза с колясками связанный с грабами.
Возможно исправляет возможность грабать в состояние [REDACTED]
<details>
```yml
🆑
tweak: Теперь нельзя грабать человека и держать его в грабе за километр.
/🆑
```
</details>
> Remove lack of fix grab

- code/game/antagonist/antagonist_update.dm
Исправил логику update_antag_mob из-за которой антагонисты спавнились с битым майндом (current = null), из-за чего возникали другие баги, в том числе их не телепортировало на спавн.
<details>
```yml
🆑
bugfix: Исправил спавн воксов-рейдеров на станции вместо их собственной локации.
/🆑
```
</details>
fix #5965
> fix(antagonist): fix update_antag_mob

- code/game/gamemodes/vampire/modular_vampire.dm
- code/game/gamemodes/vampire/vampire_powers.dm
- "Blood Heal" - **ничего не трогал** в связи с ребалансом боёвки и огнестрела, властелин ночи теперь сосёт бибу если увеличить задержку даже на пол секунды
- "Hypnotise" - не работает на генках и вампирах.**Так и надо было**
- "Presence" - Снизил расход крови с **_10_** до **_5_**
- "Touch of Life" - Снизил цену с **_50_** до **_30_**
- "Summon Bats" - Ничего не делал, **по хорошему вырезать говнину требую геймдизайн**
- "Chiropteran Screech" - Снизил цену с **_90_** до **_70_**
- "Veil Walking" - **Ничего не делал.**
- "Enthrall" - Снизил цену с **_150_** до **_120_**
- "Toggle Darkvision" - Добавил вампирчику скилл для возможности просмотра порнушки без фонарика
- **Текст о том что тебя укусили и о том что ты ничего не помнишь/что-то помнишь теперь выводится большими буквами** …
> Vamp skill rebalance and some tweaks

- code/game/objects/effects/portals.dm
Данный ПР исправляет возможность "абузить" порталы, позволяю получить полное бессмертие от пуль.
<details>
```yml
🆑
tweak: При активации портала, все объекты на турфе, где находится портал, перемещаются в соседние турфы.
/🆑
```
</details>
> tweak(portal) move all objects from portal loc

- code/_helpers/icons.dm
- code/_helpers/roundend.dm
- code/game/objects/effects/proximity.dm
- code/game/verbs/ignore.dm
- code/game/verbs/who.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/client/preference_setup/global/05_settings.dm
- code/modules/client/preference_setup/loadout/loadout.dm
- code/modules/mob/mob_helpers.dm
- code/modules/modular_computers/file_system/programs/command/comm.dm
- code/modules/virus2/disease2.dm
- Добавлена try-get обёртка для безопасного получения значения префа (возвращается дефолтное значение если они не загружены), пока добавил только к вербу вху.
- Добавил проверку на префы в проке `is_key_ignored`, если префы не прогружены - по дефолту возвращается фолз.
- Убрал кринж из конструктора вируса, рантайма который он фиксит не заметил. Так или иначе таких фиксов не надо.
- Добавил ещё одну проверку на клиент у моба в проке шатания камеры, ибо после коварного слипа клиент может (что и происходит) дать съебалды.
- Добавил проверку на тип моба перед выдачей кнопочки показать раунд энд репорт.
- Пофиксил легендарный рантайм с бэд икон оперейшн. Кое-кто забыл что цвет может быть не только в виде "#eeeeee" но и в виде матрицы.
- Пофиксил respawn_character.
fixes #6014 
fixes #5850 …
> Рантаймовое

- code/game/objects/items/weapons/smokables/smokables.dm
Сила света, излучаемого горящей сигаретой была уменьшена вдвое.
close #6112 #6096
<details>
```yml
🆑Nod404
tweak: Зажжённые сигареты теперь светят не так ярко.
/🆑Nod404
```
</details>
> свет от сигарет

- code/game/gamemodes/changeling/helpcode.dm
- code/game/gamemodes/changeling/modularchangling.dm
- code/game/gamemodes/changeling/powers/fake_armblade.dm
- code/modules/augmentation/prosthetic/prosthetic.dm
Починил гиб фейкового от ЕМП. Проверил баг с его полным отсутствием #5284, но оказалось что он не работает только на апатиков, как это исправить я не знаю.
Обновил описание скилла, убрал информацию про отражение пуль
fixes #5458
fixes #5284
<details>
```yml
🆑
bugfix: Фейковый армблейд больше не гиббается от ЭМИ.
bugfix: Исправлено описание армблейда, убрана строчка про рефлект пуль.
/🆑
```
</details>
> fix(armblades): fixes description of arm_blade and EMP gib of fake_arm_blade

- baystation12.dme
- code/game/gamemodes/cult/cultify/de-cultify.dm
- code/game/gamemodes/cult/cultify/turf.dm
- code/game/objects/items/weapons/weaponry.dm
- code/game/turfs/flooring/flooring.dm
- code/game/turfs/flooring/flooring_premade.dm
- code/game/turfs/simulated/wall_types.dm
Починил работу нуллрода, теперь при декультификации будет возвращена оригинальная стена, которую культифицировали, культо стены хранят в себе тип старой стены. Если стену заспавнили педально, то она декультифицируется в обычную стену, все это также относиться к полу.
Убрал возможность открутить культо-пол так как нуллрод теперь нормально работает, слишком просто космонавтики могут избавиться от проклятого пола.
-  fixes  #4978
<details>
```yml
🆑
bugfix: Нулл род возвращает стены и пол после культификации в оригинальный вид.
tweak: Культо-пол больше нельзя снять гаечным ключом.
/🆑
```
</details>
> fix(nullrod): fixes nullrod inability to decultify properly

- code/game/objects/items/weapons/melee/energy.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
Железные зады теперь умеют в отражение снарядов при использовании лазерных мечей. 
В настоящее время это оружие присутствует только у взломанного стандартного киборга, а также у синдикатовского.
Мне кажется это вполне заслуженный апгрейд, учитывая тот скудный арсенал, что присутствует у стандартной модели. Да и само по себе оно не шибко помогает киборгу выжить, поскольку тот всё ещё может улететь к праотцам после одной православной флешки, или же от ионного выстрела, снаряд которого нельзя отразить и очень трудно избежать.
<details>
```yml
🆑
rscadd: Киборг с активированным лазерным мечом теперь способен отражать снаряды. Механика идентична обычным лазерным мечам.
/🆑
```
</details>
> General Grievous

- code/modules/power/pedal_gen.dm
Исправляет рантайм
`Runtime in pedal_gen.dm,104: undefined variable /mob/living/silicon/robot/drone/var/handcuffed`
> Pedalgen type check

- code/modules/mob/mob_helpers.dm
Исправил отображение сикея в стори логе при выходе/входе в тело, теперь пишет так:
```
[14:25:21] cc9-bSGO SAY: (DSAY) *no key*/(Sienna Rogers): <span class='name'>hardy-camel5/(Sienna Rogers)</span> no longer lurks in the realm of the dead. They now occupy their body again. 
[14:25:24] cc9-bSGO SAY: (DSAY) *no key*/(Sienna Rogers): The ghost of <span class='name'>hardy-camel5/(Sienna Rogers)</span> now stalks among the dead.  
```
> Fix ckey leaking

- code/game/objects/items/weapons/material/misc.dm
Вместо спрайта топорика у мачете родной спрайт.
fix #6173
<details>
```yml
🆑
bugfix: Иконка топорика у мачете в автолате заменена на иконку мачете.
/🆑
```
</details>
> fix(misc): Исправлен спрайт у мачеты в автолате

- code/modules/recycling/disposal.dm
Теперь в наручниках можно залезать в мусорку
close [#1332](https://github.com/ChaoticOnyx/OnyxBay/issues/1332)
<details>
```yml
🆑SerJo
bugfix: Теперь в наручниках можно залезать в мусорку
/🆑SerJo
```
</details>
> Теперь в наручниках можно залезать в мусорку

- code/game/objects/items/devices/scanners.dm
Модуль РИГ-а, позволяющий использовать health analyzer теперь не бесполезная штука. 
~Этот баг висел с 1-го июля 19-го года, вы серьезно?~ ._.
fix #591
fix #1989
<details>
```yml
🆑Oubi
bugfix: Исправлен модуль медицинского сканера для рига, теперь сканер работает.
/🆑
```
</details>
> fix(rig healthanalyzer): fix health analyzer display output

- code/game/gamemodes/events/holidays/Holidays.dm
Измен текст который появляется на рождество в начале раунда с Happy Christmas на Merry Christmas
close [#4095](https://github.com/ChaoticOnyx/OnyxBay/issues/4095)
<details>
```yml
🆑SerJo
bugfix: Happy Christmas изменен на Merry Christmas
/🆑
```
</details>
> Changed Happy Christmas to Merry Christmas

- code/game/gamemodes/traitor/fixer.dm
Из #5755 перенес фикс.
<details>
```yml
🆑
admin: Меню контрактов теперь отображает выполненные контракты.
/🆑
```
</details>
close #5601
> tweak(contracts) admin menu now display closed contracts

- code/game/gamemodes/vampire/vampire_powers.dm
В связи с жалобами Типса о том, что игроки слишком легко упускают из виду сообщение о потери памяти после того, как вампир высосал у них кровь, я слегка переиначил процесс: теперь это не сообщение в чате, а отдельное всплывающее окно как у повреждений мозга. Надеюсь, это будет значительно заметнее.
close #6290
<details>
```yml
🆑
tweak: Сообщение о потере памяти через укус вампира стало заметнее.
/🆑
```
</details>
> tweak(vampire): Changed memory loss message to alert

- code/modules/mob/living/carbon/human/update_icons.dm
Теперь хвост не отпадает
<details>
```yml
🆑Oubi
bugfix: Исправлено отпадание хвоста у ксеносов после смерти
/🆑
```
</details>
> fix(xenos): Fixed tail animatoin afther dead

- code/game/gamemodes/traitor/contracts.dm
Изменил описание контракта для триторов на кражу исследований.
close #6237
<details>
```yml
🆑
tweak: Изменил описание контракта на кражу исследований, а именно название нужного диска для выполнения контракта.
/🆑
```
</details>
> поправил описания контракта на кражу исследований у триторов

- code/modules/paperwork/handlabeler.dm
- code/modules/recycling/sortingmachinery.dm
close #5753
```yml
🆑 Artemonim
bugfix: Теперь при креплении этикетки на посылку появляется спрайт этикетки.
tweak: Для посылок теперь можно сделать этикетку с описанием, а не только строчку названия.
/🆑
```
Есть стойкое ощущение, что логика должна быть только в handlabeler.dm иначе нанесение новых заголовков и описаний дополняет, а не заменяет старые надписи.
> fix labels on deliveries

- code/modules/spells/spellbook.dm
Добавил обновление "has_sacrificed" после завершения инвестиции слота заклинания.
Теперь жертвоприношение книге не одноразовое, как и должно быть.
Доказательство:
var/has_sacrificed = 0 //whether we have **already got** our sacrifice bonus **for the current** investment.
<details>
```yml
🆑
bugfix: Теперь жертвоприношение книге для сокращения времени получения слота заклинаний у мага не одноразовое, как и должно быть.
/🆑
```
</details>
> fix(wizard): corrected sacrifice in spellbook

- code/game/machinery/computer/arcade_orion.dm
Какой-то умник решил, что return-ы не будут прерывать ход программы. Из-за такого финта ушами игнорировалась часть OnTopic(), которая обновляла окно игры после какого-либо действия игрока. Я просто заменил эти возвраты значения на изменение переменной для возврата - по идее теперь и функция возвращает что-то, и окно обновляется.
close #4256
<details>
```yml
🆑
tweak: Orion Trail теперь обновляется при каждом действий.
/🆑
```
</details>
> fix(orion): Now updates properly.

- code/controllers/configuration.dm
- code/game/world.dm
- code/modules/mob/mob.dm
- code/modules/mob/new_player/login.dm
- config/example/config.txt
- html/changelog.html
- html/templates/changelog.tmpl
- interface/interface.dm
Добавлена опция в конфиге для указания ссылки на чейнджлог.
<details>
```yml
🆑
experiment: Чейнджлог теперь открывается в браузере.
/🆑
```
</details>
> Чейнджлоги в окне браузера

- code/modules/mob/new_player/login.dm
fixes #6427 
<details>
```yml
🆑
bugfix: Чейнджлог больше не открывается постоянно.
/🆑
```
</details>
> Фикс сохранения хэша чейнджлога

- code/modules/power/solar.dm
Пофикшены дюп панелей, отсутствие платы трекера при разборке, возможность до посинения откручивать assembly от воздуха, всё это - держа её в руке.
close #5603
<details>
```yml
🆑
bugfix: Устранён дюп солнечных панелей и пара других багов при их сборке/разборке.
/🆑
```
</details>
> fix(solar panel): fix construction

- code/modules/surgery/generic.dm
Добавил код ретрактора к системе управления разрезами.
UPD:
Заменил код ретрактора, в том числе добавленный в СУР, готовой функцией.
Добавил возможность работы с начатым оперативным входом(сделанным разрезом).
Пофиксил работу гемостата в остановке кровотечения после разреза. Раньше он работал 1 раз на каждой зоне тела.
Решилось тем, что теперь при прижигании снимается статус "зажатый".
close #1488
<details>
```yml
🆑
bugfix: Теперь incision management system производит весь оперативный вход(скальпель, зажим, ретрактор).
bugfix: Исправлена однократная работа гемостата при остановке кровотечения после разреза.
/🆑
```
</details>
> fix(surgery): fixed surgery tools bugs

- code/datums/movement/mob.dm
Глаз теперь не путешествует по не станционным з-левелам.
Проверено на Исходе.
<details>
```yml
🆑
bugfix: Глаз ИИ больше не перемещается по "запрещенным" з-левелам.
/🆑
```
</details>
> tweak(eye movement) fix moving eye in admin zlevels

- code/controllers/configuration.dm
- code/controllers/subsystems/ticker.dm
- code/game/world.dm
- code/modules/admin/admin.dm
- config/example/config.txt
Добавлены конфигурационные  вары для отключение ООЦ и/или ЛООЦ в начале раунда.
close #6241
<details>
```yml
🆑
admin: В конфиг добавлена возможность отключить LOOC и OOC раундстартом.
/🆑
```
</details>
> feat(roundstart) add configuration vars to disable ooc at roundstart

- code/datums/movement/mob.dm
Оказывается, там нужно было не mobом перемещаться, mob.eye_obj, также сделал проверки только если направление вверх или вниз.
close #6461 
<details>
```yml
🆑
tweak: Теперь глаз ИИ может СВОБОДНО перемещаться по з-левелам станции.
/🆑
```
</details>
> tweak(ai eye) fix moving on another z-level

- code/game/objects/items/weapons/surgery_tools.dm
Исправление названий лазерных скальпелей
Теперь лазерные скальпели имеют разные названия
<details>
```yml
🆑
tweak: Теперь лазерные скальпели имеют разные названия
/🆑
```
</details>
close #4331
> Фикс названий скальпелей

- code/modules/mob/mob.dm
fix #6486 
<details>
```yml
🆑
bugfix: Исправлено отображение ссылок для следования призраком в эмоутах
/🆑
```
</details>
> Фикс фоллова за эмоутами

- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- code/modules/mob/living/carbon/brain/brain.dm
Теперь ММИ не могут крутить стулья через альт-клик (немного переделал, теперь ММИ были добавлены в список incapacitated)
<details>
```yml
🆑
bugfix: ММИ теперь не умеют крутить стулья
/🆑
```
</details>
close #3703
> Исправление раскрутки стульев ММИ. Сиквел

- code/modules/ventcrawl/ventcrawl_verb.dm
Теперь вёрб работает правильно, а не выбирает 1-й элемент в списке, плюя на выбор игрока от слова совсем.
close #5469
<details>
```yml
🆑
bugfix: Теперь вёрб "Crawl through Vent" работает правильно.
/🆑
```
</details>
> fix(verb): now "Crawl through Vent" verb works correctly and let to choose.
